export const fallbackStars = [
  {
    id: "sol", name: "太阳 / Sol", short: "Sol", octant: "原点", order: 0,
    distance: 0, arrival: 2278, xyz: [0, 0, 0],
    faction: "太阳系", rank: "-", className: "G2V",
    planets: "地球、月球、火星、金星、外太阳系卫星群",
    reality: "人类母星系；2278 内战源点。",
    setting: "2350 年仍是文明法理源头，但被禁运和内战掏空。",
    habitable: 1, status: "core",
    starCount: 1, confirmedPlanets: 8, candidatePlanets: 0, planetCount: 8,
    age: "~46 亿年", lifespan: "~100 亿年（主序）",
    hz_inner: 0.95, hz_outer: 1.67,
    disasters: "太阳耀斑（中等）；科林顿事件级 CME 约百年一遇"
  },
  {
    id: "barnard", name: "Barnard's Star / 巴纳德星", short: "Barnard", octant: "+++", order: 1,
    distance: 5.96, arrival: 2283.96, xyz: [5.0, 3.0, 1.5],
    faction: "巴纳德星际动力", rank: 8, className: "M4V",
    planets: "0 宜居；Barnard b (~3.2 M⊕, 0.40 AU, 争议) + 近轨候选。",
    reality: "现实最新口径偏近轨热小行星/低质量岩石行星，无稳健宜居带世界。",
    setting: "近邻工业星，太阳系军需外包、自动化母机、义体零件核心。",
    habitable: 0, status: "core",
    starCount: 1, confirmedPlanets: 1, candidatePlanets: 0, planetCount: 1,
    age: "~100 亿年", lifespan: ">1000 亿年",
    hz_inner: 0.06, hz_outer: 0.12,
    disasters: "中等耀斑活动；高自行速度"
  },
  {
    id: "wolf1061", name: "Wolf 1061", short: "Wolf 1061", octant: "+++", order: 2,
    distance: 14.05, arrival: 2292.05, xyz: [12.9, 0.8, 5.6],
    faction: "沃尔夫潮汐能源财团", rank: 10, className: "M3.5V",
    planets: "3 行星：b (1.91 M⊕, 0.038 AU), c (3.41 M⊕, 0.084 AU, 宜居带), d (7.7 M⊕, 0.204 AU)",
    reality: "Wolf 1061 c 常列内侧宜居带/临界候选。",
    setting: "潮汐热、地热、电池、冷却与风险地产财团。",
    habitable: 1, status: "core",
    starCount: 1, confirmedPlanets: 3, candidatePlanets: 0, planetCount: 3,
    age: "~数十亿年", lifespan: ">1000 亿年",
    hz_inner: 0.07, hz_outer: 0.13,
    disasters: "中等耀斑；潮汐锁定行星"
  },
  {
    id: "gj625", name: "GJ 625", short: "GJ 625", octant: "+++", order: 3,
    distance: 21.1, arrival: 2299.1, xyz: [1.8, 15.4, 14.3],
    faction: "许可/争议区", rank: "-", className: "M1.5V",
    planets: "1 行星：GJ 625 b (2.82 M⊕, 0.078 AU, 宜居带内缘)",
    reality: "GJ 625 b 为内侧宜居带边缘超级地球，可能偏热。",
    setting: "沃尔夫财团远端投资许可，本地采矿公社保留自治。",
    habitable: 1, status: "license",
    starCount: 1, confirmedPlanets: 1, candidatePlanets: 0, planetCount: 1,
    age: "~数十亿年", lifespan: ">1000 亿年",
    hz_inner: 0.12, hz_outer: 0.24
  },
  {
    id: "vega", name: "Vega / 织女星", short: "Vega", octant: "+++", order: 4,
    distance: 25.04, arrival: 2303.04, xyz: [9.1, 21.8, 8.3],
    faction: "外环水蛇-北落师门采掘同盟", rank: 14, className: "A0V",
    planets: "边界外附录；0 宜居；碎屑盘显著",
    reality: "无确认宜居行星；尘埃/碎屑盘显著。",
    setting: "外环采矿、观测和文化宣传边界。",
    habitable: 0, status: "outer",
    starCount: 1, confirmedPlanets: 0, candidatePlanets: 0, planetCount: 0,
    age: "~4.55 亿年（极年轻）", lifespan: "~10 亿年（A型短寿）",
    hz_inner: 7.68, hz_outer: 14.84,
    disasters: "高速自转（扁率大）；强紫外辐射"
  },
  {
    id: "gj887", name: "GJ 887 / Lacaille 9352 / 拉卡伊9352", short: "GJ 887", octant: "++-", order: 1,
    distance: 10.74, arrival: 2288.74, xyz: [4.4, 0.4, -9.8],
    faction: "拉卡伊冶金公会", rank: 9, className: "M0.5V",
    planets: "3 行星：b (4.2 M⊕, 0.068 AU), c (7.6 M⊕, 0.12 AU), d (候选宜居带)",
    reality: "已知多行星；GJ 887 d 为宜居带超级地球，偏大。",
    setting: "材料上游、中立供应商、军工原料核心。",
    habitable: 1, status: "core",
    starCount: 1, confirmedPlanets: 2, candidatePlanets: 1, planetCount: 3,
    age: "~数十亿年", lifespan: ">500 亿年",
    hz_inner: 0.19, hz_outer: 0.38,
    disasters: "异常低耀斑活动（罕见安静 M 矮星）"
  },
  {
    id: "fomalhaut", name: "Fomalhaut / 北落师门", short: "Fomalhaut", octant: "++-", order: 2,
    distance: 25.13, arrival: 2303.13, xyz: [10.0, 3.7, -22.8],
    faction: "外环水蛇-北落师门采掘同盟", rank: 14, className: "A3V",
    planets: "边界外附录；0 宜居；著名碎屑盘环",
    reality: "无稳健类地宜居确认；著名碎屑盘。",
    setting: "碎屑盘采掘、冰尘、观测站与外环合同。",
    habitable: 0, status: "outer",
    starCount: 1, confirmedPlanets: 0, candidatePlanets: 1, planetCount: 0,
    age: "~4.4 亿年（极年轻）", lifespan: "~10 亿年",
    hz_inner: 3.52, hz_outer: 7.08,
    disasters: "强紫外；碎屑盘碰撞风险"
  },
  {
    id: "ross128", name: "Ross 128", short: "Ross 128", octant: "+-+", order: 1,
    distance: 11.01, arrival: 2289.01, xyz: [0.0, -5.6, 9.5],
    faction: "Ross 128生态城邦", rank: 11, className: "M4V",
    planets: "1 行星：Ross 128 b (1.35 M⊕, 0.0496 AU, 宜居带)",
    reality: "Ross 128 b 为近邻温和岩石/超级地球候选，主星较安静。",
    setting: "独立生态城邦；美丽花园只有医疗、疗养许可证。",
    habitable: 1, status: "core",
    starCount: 1, confirmedPlanets: 1, candidatePlanets: 0, planetCount: 1,
    age: "~94.5 亿年", lifespan: ">1000 亿年",
    hz_inner: 0.04, hz_outer: 0.08,
    disasters: "极低耀斑活动（安静 M 矮星，稀有）"
  },
  {
    id: "gj667c", name: "GJ 667 C / Gliese 667 C", short: "GJ 667 C", octant: "+-+", order: 2,
    distance: 23.62, arrival: 2301.62, xyz: [23.4, -3.4, 0.6],
    faction: "南爪边境开发集团", rank: 13, className: "M1.5V 三合星C",
    planets: "2 确认 + 5 候选：Cb (5.6 M⊕), Cc (3.8 M⊕, 宜居带) 等",
    reality: "GJ 667 Cc 为著名宜居带超级地球；其他多行星解争议大。",
    setting: "边境主殖民行星、三体资源、多方股权与走私。",
    habitable: 1, status: "core",
    starCount: 3, confirmedPlanets: 2, candidatePlanets: 5, planetCount: 7,
    age: "~20-100 亿年", lifespan: ">500 亿年",
    hz_inner: 0.11, hz_outer: 0.21,
    disasters: "三体引力摄动；外层行星轨道不稳"
  },
  {
    id: "alpha", name: "Alpha Centauri AB + Proxima / 半人马座α三合星", short: "Alpha Cen", octant: "+--", order: 1,
    distance: 4.37, arrival: 2282.37, xyz: [3.1, -3.1, -0.1],
    faction: "近邻三角军工托管区", rank: 6, className: "G2V+K1V+M5.5Ve",
    planets: "Proxima b (1.17 M⊕, 0.049 AU, 宜居带); Proxima d (候选, 0.029 AU)",
    reality: "Proxima b 位于宜居带但受耀斑/潮汐锁定风险；AB 未有稳健宜居确认。",
    setting: "太阳系内战外延战区、殖民正统符号和军工试验场。",
    habitable: 1, status: "core",
    starCount: 3, confirmedPlanets: 1, candidatePlanets: 1, planetCount: 2,
    age: "~53 亿年", lifespan: "A: ~100 亿年; B: ~170 亿年; Proxima: >1000 亿年",
    hz_inner: 0.04, hz_outer: 0.08,
    disasters: "Proxima 超级耀斑频繁（可致命辐射）；AB 双星互扰行星稳定性"
  },
  {
    id: "epsilon-indi", name: "Epsilon Indi / 印第安座ε", short: "Epsilon Indi", octant: "+--", order: 2,
    distance: 11.87, arrival: 2289.87, xyz: [7.3, -3.2, -8.8],
    faction: "近邻三角军工托管区", rank: 6, className: "K5V + 褐矮星伴星",
    planets: "Epsilon Indi Ab (~3 M♃, 11.5 AU); 伴星系含两颗褐矮星 Ba+Bb",
    reality: "巨行星/褐矮星系统资源突出，无强宜居背书。",
    setting: "近邻托管区外围燃料与船坞许可。",
    habitable: 0, status: "license",
    starCount: 1, confirmedPlanets: 1, candidatePlanets: 0, planetCount: 1,
    age: "~37 亿年", lifespan: "~300 亿年",
    hz_inner: 0.27, hz_outer: 0.52,
    disasters: "褐矮星轨道扰动"
  },
  {
    id: "gj682", name: "GJ 682", short: "GJ 682", octant: "+--", order: 3,
    distance: 16.33, arrival: 2294.33, xyz: [15.7, -3.9, -1.9],
    faction: "南爪边境开发集团", rank: 13, className: "M3.5V",
    planets: "0-2 候选行星（争议）：b (~4.4 M⊕), c (~8.7 M⊕)",
    reality: "行星候选存在争议，宜居性不稳。",
    setting: "失败殖民、走私与边境承包。",
    habitable: 1, status: "core",
    starCount: 1, confirmedPlanets: 0, candidatePlanets: 2, planetCount: 2,
    age: "~数十亿年", lifespan: ">1000 亿年",
    hz_inner: 0.09, hz_outer: 0.17
  },
  {
    id: "beta-hydri", name: "Beta Hydri / 水蛇座β", short: "Beta Hydri", octant: "+--", order: 4,
    distance: 24.33, arrival: 2302.33, xyz: [10.7, -15.4, -15.6],
    faction: "外环水蛇-北落师门采掘同盟", rank: 14, className: "G2IV",
    planets: "0 宜居；亚巨星演化阶段，宜居带已外移",
    reality: "无确认宜居行星；主星演化阶段不适合长期新殖民核心。",
    setting: "老恒星边境和采掘同盟背景。",
    habitable: 0, status: "license",
    starCount: 1, confirmedPlanets: 0, candidatePlanets: 0, planetCount: 0,
    age: "~67 亿年", lifespan: "~90 亿年（已离开主序）",
    hz_inner: 1.6, hz_outer: 3.1,
    disasters: "亚巨星膨胀中；宜居带不稳定外移"
  },
  {
    id: "luyten726", name: "Luyten 726-8 / UV Ceti", short: "UV Ceti", octant: "-+-", order: 1,
    distance: 8.73, arrival: 2286.73, xyz: [-2.2, 0.2, -8.5],
    faction: "许可/争议区", rank: "-", className: "M5.5V+M6V",
    planets: "0 宜居；耀星双星系统",
    reality: "耀星双星，无强宜居背书。",
    setting: "S&F 与美丽花园早期保险争议区。",
    habitable: 0, status: "license",
    starCount: 2, confirmedPlanets: 0, candidatePlanets: 0, planetCount: 0,
    age: "~数十亿年", lifespan: ">1000 亿年",
    hz_inner: 0.02, hz_outer: 0.04,
    disasters: "UV Ceti B 为原型耀星——超级耀斑频率极高，可在分钟内亮度翻数倍"
  },
  {
    id: "groombridge34", name: "Groombridge 34 / 格鲁姆布里奇34", short: "Groombridge 34", octant: "-+-", order: 2,
    distance: 11.62, arrival: 2289.62, xyz: [-5.0, 9.9, -3.7],
    faction: "S&F", rank: 4, className: "M1V+M3V",
    planets: "0 确认宜居；寒冷矿业双星",
    reality: "近轨/冷行星候选，无稳健宜居带地表。",
    setting: "S&F 数据金融走廊内节点。",
    habitable: 0, status: "core",
    starCount: 2, confirmedPlanets: 0, candidatePlanets: 0, planetCount: 0,
    age: "~数十亿年", lifespan: ">500 亿年",
    hz_inner: 0.12, hz_outer: 0.24,
    disasters: "双星系统；GX And (A) 偶发耀斑"
  },
  {
    id: "tau-ceti", name: "Tau Ceti / 天仓五", short: "Tau Ceti", octant: "-+-", order: 3,
    distance: 11.91, arrival: 2289.91, xyz: [-3.4, 0.4, -11.4],
    faction: "美丽花园巨企", rank: 5, className: "G8.5V",
    planets: "4 候选行星：e (3.9 M⊕), f (3.9 M⊕, 宜居带), g (1.75 M⊕), h (1.83 M⊕)",
    reality: "e/f 等宜居讨论在 2026 口径下已明显削弱或视为伪信号。",
    setting: "美丽花园的文化首都、生态金融母盘之一。",
    habitable: 1, status: "core",
    starCount: 1, confirmedPlanets: 0, candidatePlanets: 4, planetCount: 4,
    age: "~58 亿年", lifespan: "~150 亿年",
    hz_inner: 0.55, hz_outer: 1.16,
    disasters: "碎屑盘密度为太阳系 ~10 倍——小行星撞击风险显著偏高"
  },
  {
    id: "teegarden", name: "Teegarden's Star / 提加登星", short: "Teegarden", octant: "-+-", order: 4,
    distance: 12.5, arrival: 2290.5, xyz: [-9.4, 3.4, -7.5],
    faction: "美丽花园巨企", rank: 5, className: "M7V",
    planets: "2 宜居：b (1.05 M⊕, 0.025 AU, 宜居带), c (1.11 M⊕, 0.044 AU, 外宜居带)",
    reality: "Teegarden b/c 为近邻地球质量级宜居带候选。",
    setting: "美丽花园最合理直属核心，人工花园技术展示地。",
    habitable: 2, status: "core",
    starCount: 1, confirmedPlanets: 2, candidatePlanets: 0, planetCount: 2,
    age: "~80 亿年", lifespan: ">1000 亿年",
    hz_inner: 0.02, hz_outer: 0.05,
    disasters: "超冷矮星；潮汐锁定"
  },
  {
    id: "gj1002", name: "GJ 1002", short: "GJ 1002", octant: "-+-", order: 5,
    distance: 15.81, arrival: 2293.81, xyz: [-0.3, 6.0, -14.6],
    faction: "星蓝元素", rank: 7, className: "M5.5V",
    planets: "2 宜居：b (1.08 M⊕, 0.0457 AU), c (1.36 M⊕, 0.0738 AU)",
    reality: "GJ 1002 b/c 为两颗地球质量级宜居带行星。",
    setting: "星蓝元素双宜居核心，兼爱、包容、新人类技术路线。",
    habitable: 2, status: "core",
    starCount: 1, confirmedPlanets: 2, candidatePlanets: 0, planetCount: 2,
    age: "~数十亿年", lifespan: ">1000 亿年",
    hz_inner: 0.04, hz_outer: 0.08,
    disasters: "低耀斑活动"
  },
  {
    id: "hd219134", name: "HD 219134", short: "HD 219134", octant: "-+-", order: 6,
    distance: 21.25, arrival: 2299.25, xyz: [-7.2, 20.0, -1.2],
    faction: "S&F", rank: 4, className: "K3V",
    planets: "6 行星 (全近轨热行星)：b-h，均 <0.4 AU",
    reality: "多颗近轨超级地球/热岩石行星，部分凌星。",
    setting: "S&F 核心数据仓与清算节点。",
    habitable: 0, status: "core",
    starCount: 1, confirmedPlanets: 6, candidatePlanets: 0, planetCount: 6,
    age: "~110 亿年", lifespan: "~250 亿年",
    hz_inner: 0.36, hz_outer: 0.71,
    disasters: "古老稳定系统"
  },
  {
    id: "107piscium", name: "107 Piscium / HD 10476", short: "107 Piscium", octant: "-+-", order: 7,
    distance: 24.4, arrival: 2302.4, xyz: [-13.9, 12.1, -16.0],
    faction: "S&F", rank: 4, className: "K1V",
    planets: "0 确认宜居",
    reality: "无稳健确认宜居行星。",
    setting: "S&F 外围金融/采掘许可，不算直属本土。",
    habitable: 0, status: "license",
    starCount: 1, confirmedPlanets: 0, candidatePlanets: 0, planetCount: 0,
    age: "~60 亿年", lifespan: "~200 亿年",
    hz_inner: 0.47, hz_outer: 0.92
  },
  {
    id: "wolf359", name: "Wolf 359", short: "Wolf 359", octant: "--+", order: 1,
    distance: 7.86, arrival: 2285.86, xyz: [-1.9, -3.9, 6.5],
    faction: "无限未来", rank: 1, className: "M6V",
    planets: "0 确认宜居；2 候选行星",
    reality: "行星候选不宜居；耀发环境极端。",
    setting: "无限未来近邻硬科技核心，实验禁区。",
    habitable: 0, status: "core",
    starCount: 1, confirmedPlanets: 0, candidatePlanets: 2, planetCount: 2,
    age: "~1-3.5 亿年（极年轻）", lifespan: ">1000 亿年",
    hz_inner: 0.02, hz_outer: 0.04,
    disasters: "剧烈耀斑活动（年轻 M 矮星）；超级耀斑周期性爆发"
  },
  {
    id: "lalande", name: "Lalande 21185 / 拉兰德21185", short: "Lalande 21185", octant: "--+", order: 2,
    distance: 8.31, arrival: 2286.31, xyz: [-3.4, -0.3, 7.6],
    faction: "无限未来", rank: 1, className: "M2V",
    planets: "1 确认：b (2.69 M⊕, 12.95 天周期); 1 候选",
    reality: "已知/候选近轨超级地球，无稳健开放地表宜居。",
    setting: "无限未来消费电子、娱乐终端和人口盘核心。",
    habitable: 1, status: "core",
    starCount: 1, confirmedPlanets: 1, candidatePlanets: 1, planetCount: 2,
    age: "~75 亿年", lifespan: ">500 亿年",
    hz_inner: 0.11, hz_outer: 0.21,
    disasters: "中等耀斑"
  },
  {
    id: "gj273", name: "GJ 273 / Luyten's Star / 鲁坦星", short: "GJ 273", octant: "--+", order: 3,
    distance: 12.35, arrival: 2290.35, xyz: [-10.3, -6.5, 2.2],
    faction: "无限未来", rank: 1, className: "M3.5V",
    planets: "2 行星：b (2.89 M⊕, 0.091 AU, 宜居带), c (候选)",
    reality: "GJ 273 b 为经典宜居带超级地球候选。",
    setting: "无限未来外缘主居住区，最大民用人口盘。",
    habitable: 1, status: "core",
    starCount: 1, confirmedPlanets: 2, candidatePlanets: 0, planetCount: 2,
    age: "~80 亿年", lifespan: ">1000 亿年",
    hz_inner: 0.07, hz_outer: 0.14,
    disasters: "低-中等耀斑"
  },
  {
    id: "gj251", name: "GJ 251", short: "GJ 251", octant: "--+", order: 4,
    distance: 18.22, arrival: 2296.22, xyz: [-17.6, -0.9, 4.8],
    faction: "无限未来", rank: 1, className: "M3V",
    planets: "1 确认：b (4.0 M⊕, 0.082 AU); 1 候选宜居带",
    reality: "GJ 251 c 为 2025 宜居带候选；仍需确认。",
    setting: "无限未来外围影响/专利锁定，可被战争切走。",
    habitable: 1, status: "license",
    starCount: 1, confirmedPlanets: 1, candidatePlanets: 1, planetCount: 2,
    age: "~数十亿年", lifespan: ">1000 亿年",
    hz_inner: 0.10, hz_outer: 0.20
  },
  {
    id: "epsilon-eridani", name: "Epsilon Eridani / 天苑四", short: "Epsilon Eri", octant: "---", order: 1,
    distance: 10.47, arrival: 2288.47, xyz: [-6.7, -1.9, -7.8],
    faction: "明日晨曦", rank: 3, className: "K2V",
    planets: "1 确认巨行星：Epsilon Eridani b (0.76 M♃, 3.48 AU); 碎屑盘",
    reality: "巨行星与碎屑盘资源强，无确认宜居类地。",
    setting: "天苑四造船联合体，明日晨曦舰队、债券和违禁武器来源。",
    habitable: 0, status: "core",
    starCount: 1, confirmedPlanets: 1, candidatePlanets: 0, planetCount: 1,
    age: "~4-8 亿年（年轻）", lifespan: "~200 亿年",
    hz_inner: 0.56, hz_outer: 1.08,
    disasters: "年轻系统——碎屑盘撞击极频繁；类小行星雨环境"
  },
  {
    id: "gj1061", name: "GJ 1061", short: "GJ 1061", octant: "---", order: 2,
    distance: 11.98, arrival: 2289.98, xyz: [-2.3, -6.9, -9.6],
    faction: "人类群星联合", rank: 2, className: "M5.5V",
    planets: "3 行星：b (1.38 M⊕, 0.021 AU), c (1.74 M⊕, 0.035 AU, 宜居带), d (1.64 M⊕, 0.054 AU, 宜居带)",
    reality: "GJ 1061 c/d 为双宜居带候选。",
    setting: "人类群星联合南方民生署生态核心。",
    habitable: 2, status: "core",
    starCount: 1, confirmedPlanets: 3, candidatePlanets: 0, planetCount: 3,
    age: "~数十亿年", lifespan: ">1000 亿年",
    hz_inner: 0.03, hz_outer: 0.06,
    disasters: "低-中等耀斑"
  },
  {
    id: "kapteyn", name: "Kapteyn's Star / 卡普坦星", short: "Kapteyn", octant: "---", order: 3,
    distance: 12.83, arrival: 2290.83, xyz: [-3.5, -9.8, -7.5],
    faction: "人类群星联合", rank: 2, className: "sdM1",
    planets: "2 候选行星（争议大）：b (4.8 M⊕, 0.168 AU), c (7.0 M⊕, 0.311 AU)",
    reality: "Kapteyn b 等早期宜居候选争议较大。",
    setting: "群星联合老军政节点和退役舰队基地。",
    habitable: 0, status: "core",
    starCount: 1, confirmedPlanets: 0, candidatePlanets: 2, planetCount: 2,
    age: "~115 亿年（银河系最古老近邻恒星之一）", lifespan: ">500 亿年",
    hz_inner: 0.13, hz_outer: 0.25,
    disasters: "次矮星；银晕捕获星——逆行轨道、高速运动"
  },
  {
    id: "40eridani", name: "40 Eridani A / 波江座40A", short: "40 Eridani", octant: "---", order: 4,
    distance: 16.26, arrival: 2294.26, xyz: [-12.0, -4.5, -10.0],
    faction: "人类群星联合", rank: 2, className: "K1V + 伴星",
    planets: "1 候选行星（争议/可能撤回）; 白矮星伴星 B + 红矮星伴星 C",
    reality: "早期行星候选争议/可能被排除；无稳健宜居确认。",
    setting: "群星联合行政-船坞节点。",
    habitable: 1, status: "core",
    starCount: 3, confirmedPlanets: 0, candidatePlanets: 1, planetCount: 1,
    age: "~57 亿年", lifespan: "~200 亿年",
    hz_inner: 0.47, hz_outer: 0.92,
    disasters: "三合星系统；白矮星 B 为已死亡恒星（科研价值极高）"
  },
  {
    id: "hd20794", name: "HD 20794 / 82 Eridani / 波江座82", short: "HD 20794", octant: "---", order: 5,
    distance: 19.7, arrival: 2297.7, xyz: [-3.6, -10.4, -16.4],
    faction: "人类群星联合", rank: 2, className: "G6V",
    planets: "4 行星：b (2.7 M⊕, 0.12 AU), c (2.4 M⊕, 0.20 AU), d (4.8 M⊕, 0.36 AU, 宜居带内缘), e (候选)",
    reality: "近年确认/强化一颗偏心宜居带超级地球。",
    setting: "人类群星联合正统旗舰与中央殖民信托。",
    habitable: 1, status: "core",
    starCount: 1, confirmedPlanets: 3, candidatePlanets: 1, planetCount: 4,
    age: "~63 亿年", lifespan: "~130 亿年",
    hz_inner: 0.63, hz_outer: 1.25,
    disasters: "稳定类太阳恒星；低风险"
  },
  {
    id: "li-hartman", name: "_李-哈特曼_ / _Li-Hartman_", short: "_Li-Hartman_", octant: "++-", order: 5.7,
    distance: 22.2, arrival: 2300.2, xyz: [0.6, 9.2, -20.2],
    faction: "远岭联营", rank: 12, className: "_K3V 橙矮星（架空）_",
    planets: "_原野星、草原星、釉海星、匣为主级宜居/准宜居；阙穹 76 卫星。_",
    reality: "_架空锚点，置于 GJ 1002 附近的 -+-/++- 象限交界处，坐标用于星蓝元素-自动舰接触线推演。_",
    setting: "_边境黄金压力锅：远岭联营经营权，母星方保留法理和黄金股。_",
    habitable: 4, status: "core",
    starCount: 1, confirmedPlanets: 5, candidatePlanets: 2, planetCount: 7,
    age: "_~52 亿年（架空）_", lifespan: "_~200 亿年_",
    hz_inner: 0.43, hz_outer: 0.85,
    disasters: "_低耀斑；阙穹引力对内行星轨道有长期摄动_"
  },
  {
    id: "ltt1445", name: "LTT 1445 A", short: "LTT 1445 A", octant: "---", order: 7,
    distance: 22.39, arrival: 2300.39, xyz: [-11.1, -4.1, -19.0],
    faction: "人类群星联合", rank: 2, className: "M2.5V 三合星主星",
    planets: "2 确认凌星：Ab (2.87 M⊕, 0.038 AU), Ac (1.54 M⊕, 0.027 AU); 1 候选 Ad (宜居带)",
    reality: "b/c 为近轨热行星；Ad 为宜居带候选但置信偏低。",
    setting: "群星联合科研许可区，明日晨曦船坞派也有合同。",
    habitable: 1, status: "license",
    starCount: 3, confirmedPlanets: 2, candidatePlanets: 1, planetCount: 3,
    age: "~数十亿年", lifespan: ">500 亿年",
    hz_inner: 0.10, hz_outer: 0.20,
    disasters: "三合星系统；外层伴星 B/C 互绕"
  },
  {
    id: "trappist-1", name: "TRAPPIST-1 / 特拉比斯特-1", short: "TRAPPIST-1", octant: "+--", order: 5,
    distance: 40.66, arrival: 2318.66, xyz: [21.9, -6.1, -33.8],
    faction: "星蓝元素", rank: "-", className: "M8V（超冷矮星）",
    planets: "7 凌星行星 b-h；e/f/g 位于宜居带，为已知最佳类地系统之一",
    reality: "7 颗地球大小级行星（3 颗位于宜居带），2017 年后持续确认和表征。",
    setting: "_星蓝元素极远外哨；因七行星系统的科研与殖民价值极高，属最高优先开发目标。_",
    habitable: 3, status: "outer",
    starCount: 1, confirmedPlanets: 7, candidatePlanets: 0, planetCount: 7,
    age: "~76 亿年", lifespan: ">10000 亿年（超冷矮星）",
    hz_inner: 0.022, hz_outer: 0.049,
    disasters: "频繁耀斑（超冷矮星）；全部行星潮汐锁定；轨道共振链（7:5:3 等）"
  },
  {
    id: "lhs1140", name: "LHS 1140", short: "LHS 1140", octant: "---", order: 8,
    distance: 40.7, arrival: 2318.7, xyz: [-20.7, -6.2, -34.5],
    faction: "星蓝元素", rank: "-", className: "M4.5V",
    planets: "2 确认：b (6.48 M⊕, 0.095 AU, 宜居带超级地球), c (1.81 M⊕, 0.027 AU)",
    reality: "LHS 1140 b 为最佳宜居超级地球候选之一，可能有大气层和液态水。",
    setting: "_星蓝元素远端科研前哨；b 行星大气层探测为最高优先课题。_",
    habitable: 1, status: "outer",
    starCount: 1, confirmedPlanets: 2, candidatePlanets: 0, planetCount: 2,
    age: "~50 亿年", lifespan: ">1000 亿年",
    hz_inner: 0.04, hz_outer: 0.08,
    disasters: "中等耀斑；b 行星可能潮汐锁定"
  },
  {
    id: "gj357", name: "GJ 357 / TOI-562", short: "GJ 357", octant: "--+", order: 5,
    distance: 30.8, arrival: 2308.8, xyz: [-10.5, -24.5, 15.4],
    faction: "美丽花园巨企", rank: "-", className: "M2.5V",
    planets: "3 行星：b (1.84 M⊕, 0.035 AU, 凌星热行星), c (3.4 M⊕, 0.061 AU), d (6.1 M⊕, 0.204 AU, 宜居带)",
    reality: "GJ 357 d 为宜居带超级地球候选（需确认不是伪信号）。",
    setting: "_美丽花园远端采集许可区；d 行星生态价值待评估。_",
    habitable: 1, status: "outer",
    starCount: 1, confirmedPlanets: 2, candidatePlanets: 1, planetCount: 3,
    age: "~50 亿年", lifespan: ">500 亿年",
    hz_inner: 0.12, hz_outer: 0.23,
    disasters: "低耀斑；稳定 M 矮星"
  },
  {
    id: "55cnc", name: "55 Cancri / 巨蟹座55", short: "55 Cancri", octant: "--+", order: 6,
    distance: 40.3, arrival: 2318.3, xyz: [-32.7, -9.5, 21.6],
    faction: "S&F", rank: "-", className: "K0IV-V + M矮星伴星",
    planets: "5 确认行星：b (0.80 M♃), c (0.17 M♃), d (3.88 M♃, 5.44 AU), e (超级地球 8.63 M⊕, 0.016 AU, 极热), f (0.14 M♃, 0.77 AU, 近宜居带)",
    reality: "少数拥有 5+ 确认行星的恒星系；e 为最早确认的凌星超级地球之一。",
    setting: "_S&F 远端资产管理前哨；多行星系统金融与保险模型范本。_",
    habitable: 0, status: "outer",
    starCount: 2, confirmedPlanets: 5, candidatePlanets: 0, planetCount: 5,
    age: "~103 亿年", lifespan: "~150 亿年",
    hz_inner: 0.67, hz_outer: 1.32,
    disasters: "古老系统；e 行星表面温度 ~2700K（熔岩世界）"
  }
];

export const fallbackBodies = {
  sol: [
    { id: "sol-primary", name: "太阳 / Sun", bodyType: "star", orbitAu: 0, radiusLabel: "1 R☉", massLabel: "1 M☉", habitable: 0, summary: "G2V 黄矮星；主序氢聚变阶段，剩余约 50 亿年。", sortOrder: 0 },
    { id: "sol-mercury", name: "水星 / Mercury", bodyType: "planet", orbitAu: 0.387, radiusLabel: "0.38 R⊕", massLabel: "0.055 M⊕", habitable: 0, summary: "无大气层；密度极高的铁核行星。昼夜温差 600°C。", sortOrder: 1 },
    { id: "sol-venus", name: "金星 / Venus", bodyType: "planet", orbitAu: 0.723, radiusLabel: "0.95 R⊕", massLabel: "0.815 M⊕", habitable: 0, summary: "厚重 CO₂ 大气；地表 ~460°C；逆行自转。曾有地球化改造讨论。", sortOrder: 2 },
    { id: "sol-earth", name: "地球 / Earth", bodyType: "planet", orbitAu: 1.0, radiusLabel: "1 R⊕", massLabel: "1 M⊕", habitable: 1, summary: "人类母星。2278 内战后人口锐减；2350 年仍是文明法理源头。", sortOrder: 3 },
    { id: "sol-moon", name: "月球 / Luna", bodyType: "moon", orbitAu: 0.00257, radiusLabel: "0.27 R⊕", massLabel: "0.012 M⊕", habitable: 0, summary: "地球唯一天然卫星；氦-3 采矿和军事基地。", sortOrder: 4, parentId: "sol-earth" },
    { id: "sol-mars", name: "火星 / Mars", bodyType: "planet", orbitAu: 1.524, radiusLabel: "0.53 R⊕", massLabel: "0.107 M⊕", habitable: 0, summary: "最早殖民地之一。稀薄 CO₂ 大气；地下城和穹顶城市。", sortOrder: 5 },
    { id: "sol-belt", name: "小行星带 / Asteroid Belt", bodyType: "belt", orbitAu: 2.7, radiusLabel: "-", massLabel: "-", habitable: 0, summary: "谷神星为最大天体；工业采矿和船坞。", sortOrder: 6 },
    { id: "sol-jupiter", name: "木星 / Jupiter", bodyType: "planet", orbitAu: 5.203, radiusLabel: "11.2 R⊕", massLabel: "317.8 M⊕", habitable: 0, summary: "气态巨行星；辐射带极强。79+ 已知卫星；聚变燃料来源。", sortOrder: 7 },
    { id: "sol-europa", name: "欧罗巴 / Europa", bodyType: "moon", orbitAu: 0.00449, radiusLabel: "0.25 R⊕", massLabel: "0.008 M⊕", habitable: 0, summary: "冰壳下有全球海洋；地外生命搜索重点目标。", sortOrder: 8, parentId: "sol-jupiter" },
    { id: "sol-ganymede", name: "盖尼米得 / Ganymede", bodyType: "moon", orbitAu: 0.00716, radiusLabel: "0.41 R⊕", massLabel: "0.025 M⊕", habitable: 0, summary: "太阳系最大卫星；有自身磁场。冰下海洋。", sortOrder: 9, parentId: "sol-jupiter" },
    { id: "sol-saturn", name: "土星 / Saturn", bodyType: "planet", orbitAu: 9.537, radiusLabel: "9.45 R⊕", massLabel: "95.2 M⊕", habitable: 0, summary: "环系壮观的气态巨行星；大量卫星；氦雨。", sortOrder: 10 },
    { id: "sol-titan", name: "泰坦 / Titan", bodyType: "moon", orbitAu: 0.00817, radiusLabel: "0.40 R⊕", massLabel: "0.023 M⊕", habitable: 0, summary: "厚 N₂ 大气层（太阳系唯一有稠密大气的卫星）；甲烷湖海。", sortOrder: 11, parentId: "sol-saturn" },
    { id: "sol-uranus", name: "天王星 / Uranus", bodyType: "planet", orbitAu: 19.19, radiusLabel: "4.01 R⊕", massLabel: "14.5 M⊕", habitable: 0, summary: "冰巨星；97° 轴倾斜（侧躺自转）；甲烷蓝色大气。", sortOrder: 12 },
    { id: "sol-neptune", name: "海王星 / Neptune", bodyType: "planet", orbitAu: 30.07, radiusLabel: "3.88 R⊕", massLabel: "17.1 M⊕", habitable: 0, summary: "最外行星；极端风暴（~2100 km/h）；深蓝色。", sortOrder: 13 }
  ],
  alpha: [
    { id: "alpha-a", name: "Alpha Centauri A", bodyType: "star", orbitAu: 0, radiusLabel: "1.22 R☉", massLabel: "1.10 M☉", habitable: 0, summary: "G2V 主星；与 B 互绕周期 ~80 年，平均间距 23 AU。", sortOrder: 0 },
    { id: "alpha-b", name: "Alpha Centauri B", bodyType: "star", orbitAu: 23.0, radiusLabel: "0.86 R☉", massLabel: "0.91 M☉", habitable: 0, summary: "K1V 伴星；与 A 构成目视双星。稍暗橙色。", sortOrder: 1 },
    { id: "alpha-proxima", name: "Proxima Centauri / 比邻星", bodyType: "star", orbitAu: 8700, radiusLabel: "0.15 R☉", massLabel: "0.12 M☉", habitable: 0, summary: "M5.5Ve 红矮星；距 AB 约 13000 AU，轨道周期 ~55 万年。最近恒星。", sortOrder: 2 },
    { id: "alpha-proxima-b", name: "Proxima b", bodyType: "planet", orbitAu: 0.0485, radiusLabel: "~1.08 R⊕", massLabel: "1.17 M⊕", habitable: 1, summary: "宜居带岩石行星；潮汐锁定；受 Proxima 超级耀斑威胁。", sortOrder: 3, parentId: "alpha-proxima" },
    { id: "alpha-proxima-d", name: "Proxima d（候选）", bodyType: "planet", orbitAu: 0.029, radiusLabel: "~0.8 R⊕", massLabel: "~0.26 M⊕", habitable: 0, summary: "候选近轨小行星；质量可能低于火星。待确认。", sortOrder: 4, parentId: "alpha-proxima" }
  ],
  "epsilon-eridani": [
    { id: "epsilon-eridani-primary", name: "天苑四 / Epsilon Eridani", bodyType: "star", orbitAu: 0, radiusLabel: "0.74 R☉", massLabel: "0.82 M☉", habitable: 0, summary: "K2V 橙矮星；非常年轻（~5 亿年），活跃碎屑盘。", sortOrder: 0 },
    { id: "epsilon-eridani-b", name: "Epsilon Eridani b", bodyType: "planet", orbitAu: 3.48, radiusLabel: "~1 R♃", massLabel: "0.76 M♃", habitable: 0, summary: "类木巨行星；偏心轨道（e=0.07）。卫星群为船坞和聚变燃料来源。", sortOrder: 1 },
    { id: "epsilon-eridani-belt1", name: "内碎屑盘", bodyType: "belt", orbitAu: 3.0, radiusLabel: "-", massLabel: "-", habitable: 0, summary: "类小行星带结构；~3 AU 处，密度约太阳系小行星带 100 倍。", sortOrder: 2 },
    { id: "epsilon-eridani-belt2", name: "外碎屑盘", bodyType: "belt", orbitAu: 20.0, radiusLabel: "-", massLabel: "-", habitable: 0, summary: "类柯伊伯带结构；~20 AU 处，著名的红外尘埃环。", sortOrder: 3 }
  ],
  "tau-ceti": [
    { id: "tau-ceti-primary", name: "天仓五 / Tau Ceti", bodyType: "star", orbitAu: 0, radiusLabel: "0.79 R☉", massLabel: "0.78 M☉", habitable: 0, summary: "G8.5V；最近的类太阳单星之一。碎屑盘密度偏高。", sortOrder: 0 },
    { id: "tau-ceti-g", name: "Tau Ceti g（候选）", bodyType: "planet", orbitAu: 0.133, radiusLabel: "~1.2 R⊕", massLabel: "1.75 M⊕", habitable: 0, summary: "候选近轨岩石行星。信号争议中。", sortOrder: 1 },
    { id: "tau-ceti-h", name: "Tau Ceti h（候选）", bodyType: "planet", orbitAu: 0.243, radiusLabel: "~1.3 R⊕", massLabel: "1.83 M⊕", habitable: 0, summary: "候选内行星。信号争议中。", sortOrder: 2 },
    { id: "tau-ceti-e", name: "Tau Ceti e（候选）", bodyType: "planet", orbitAu: 0.538, radiusLabel: "~1.6 R⊕", massLabel: "3.93 M⊕", habitable: 0, summary: "候选宜居带内缘超级地球；可能偏热。信号争议。", sortOrder: 3 },
    { id: "tau-ceti-f", name: "Tau Ceti f（候选）", bodyType: "planet", orbitAu: 1.334, radiusLabel: "~1.6 R⊕", massLabel: "3.93 M⊕", habitable: 1, summary: "_设定中美丽花园最重要的生态金融母盘。候选宜居带超级地球。_", sortOrder: 4 }
  ],
  teegarden: [
    { id: "teegarden-primary", name: "提加登星 / Teegarden's Star", bodyType: "star", orbitAu: 0, radiusLabel: "0.12 R☉", massLabel: "0.09 M☉", habitable: 0, summary: "M7V 超冷矮星；极暗（绝对星等 ~17）。安静型。", sortOrder: 0 },
    { id: "teegarden-b", name: "Teegarden b", bodyType: "planet", orbitAu: 0.0252, radiusLabel: "~1.0 R⊕", massLabel: "1.05 M⊕", habitable: 1, summary: "宜居带地球质量行星；温度估算 ~接近地球。美丽花园核心殖民地。", sortOrder: 1 },
    { id: "teegarden-c", name: "Teegarden c", bodyType: "planet", orbitAu: 0.0443, radiusLabel: "~1.0 R⊕", massLabel: "1.11 M⊕", habitable: 1, summary: "外宜居带行星；温度类似火星。人工生态穹顶。", sortOrder: 2 }
  ],
  gj1002: [
    { id: "gj1002-primary", name: "GJ 1002", bodyType: "star", orbitAu: 0, radiusLabel: "0.14 R☉", massLabel: "0.12 M☉", habitable: 0, summary: "M5.5V 红矮星；低耀斑活动。", sortOrder: 0 },
    { id: "gj1002-b", name: "GJ 1002 b", bodyType: "planet", orbitAu: 0.0457, radiusLabel: "~1.0 R⊕", massLabel: "1.08 M⊕", habitable: 1, summary: "内宜居带地球质量行星；星蓝元素主殖民地。", sortOrder: 1 },
    { id: "gj1002-c", name: "GJ 1002 c", bodyType: "planet", orbitAu: 0.0738, radiusLabel: "~1.1 R⊕", massLabel: "1.36 M⊕", habitable: 1, summary: "外宜居带超级地球；星蓝元素自治实验地。", sortOrder: 2 }
  ],
  ross128: [
    { id: "ross128-primary", name: "Ross 128", bodyType: "star", orbitAu: 0, radiusLabel: "0.20 R☉", massLabel: "0.17 M☉", habitable: 0, summary: "M4V 红矮星；异常安静（耀斑极少）。", sortOrder: 0 },
    { id: "ross128-b", name: "Ross 128 b", bodyType: "planet", orbitAu: 0.0496, radiusLabel: "~1.1 R⊕", massLabel: "1.35 M⊕", habitable: 1, summary: "宜居带地球类行星；主星安静使其成为最佳宜居候选之一。生态城邦核心。", sortOrder: 1 }
  ],
  gj273: [
    { id: "gj273-primary", name: "鲁坦星 / Luyten's Star", bodyType: "star", orbitAu: 0, radiusLabel: "0.29 R☉", massLabel: "0.26 M☉", habitable: 0, summary: "M3.5V 红矮星；低活动性。", sortOrder: 0 },
    { id: "gj273-b", name: "GJ 273 b", bodyType: "planet", orbitAu: 0.0911, radiusLabel: "~1.4 R⊕", massLabel: "2.89 M⊕", habitable: 1, summary: "宜居带超级地球；无限未来最大民用人口盘。", sortOrder: 1 },
    { id: "gj273-c", name: "GJ 273 c", bodyType: "planet", orbitAu: 0.036, radiusLabel: "~1.1 R⊕", massLabel: "1.18 M⊕", habitable: 0, summary: "近轨热行星；工业利用。", sortOrder: 2 }
  ],
  wolf1061: [
    { id: "wolf1061-primary", name: "Wolf 1061", bodyType: "star", orbitAu: 0, radiusLabel: "0.31 R☉", massLabel: "0.29 M☉", habitable: 0, summary: "M3.5V 红矮星；中等活动。", sortOrder: 0 },
    { id: "wolf1061-b", name: "Wolf 1061 b", bodyType: "planet", orbitAu: 0.0375, radiusLabel: "~1.2 R⊕", massLabel: "1.91 M⊕", habitable: 0, summary: "近轨热超级地球；潮汐加热提供地热资源。", sortOrder: 1 },
    { id: "wolf1061-c", name: "Wolf 1061 c", bodyType: "planet", orbitAu: 0.0843, radiusLabel: "~1.5 R⊕", massLabel: "3.41 M⊕", habitable: 1, summary: "宜居带内缘超级地球；可能偏热但有液态水条件。潮汐能源核心。", sortOrder: 2 },
    { id: "wolf1061-d", name: "Wolf 1061 d", bodyType: "planet", orbitAu: 0.204, radiusLabel: "~1.8 R⊕", massLabel: "7.7 M⊕", habitable: 0, summary: "外侧迷你海王星；可能有厚 H/He 大气。冷备份基地。", sortOrder: 3 }
  ],
  gj887: [
    { id: "gj887-primary", name: "拉卡伊9352 / GJ 887", bodyType: "star", orbitAu: 0, radiusLabel: "0.47 R☉", massLabel: "0.49 M☉", habitable: 0, summary: "M0.5V 红矮星；异常低耀斑活动（极稳定）。最亮 M 矮星之一。", sortOrder: 0 },
    { id: "gj887-b", name: "GJ 887 b", bodyType: "planet", orbitAu: 0.068, radiusLabel: "~1.6 R⊕", massLabel: "4.2 M⊕", habitable: 0, summary: "近轨超级地球；可能有大气层。工业行星。", sortOrder: 1 },
    { id: "gj887-c", name: "GJ 887 c", bodyType: "planet", orbitAu: 0.12, radiusLabel: "~1.8 R⊕", massLabel: "7.6 M⊕", habitable: 0, summary: "超级地球/迷你海王星边界。冶金原料。", sortOrder: 2 }
  ],
  gj1061: [
    { id: "gj1061-primary", name: "GJ 1061", bodyType: "star", orbitAu: 0, radiusLabel: "0.16 R☉", massLabel: "0.12 M☉", habitable: 0, summary: "M5.5V 红矮星。", sortOrder: 0 },
    { id: "gj1061-b", name: "GJ 1061 b", bodyType: "planet", orbitAu: 0.021, radiusLabel: "~1.1 R⊕", massLabel: "1.38 M⊕", habitable: 0, summary: "近轨热岩石行星；偏热。", sortOrder: 1 },
    { id: "gj1061-c", name: "GJ 1061 c", bodyType: "planet", orbitAu: 0.035, radiusLabel: "~1.2 R⊕", massLabel: "1.74 M⊕", habitable: 1, summary: "宜居带地球类行星；群星联合南方民生署核心。", sortOrder: 2 },
    { id: "gj1061-d", name: "GJ 1061 d", bodyType: "planet", orbitAu: 0.054, radiusLabel: "~1.2 R⊕", massLabel: "1.64 M⊕", habitable: 1, summary: "外宜居带行星；冷生态世界。", sortOrder: 3 }
  ],
  hd219134: [
    { id: "hd219134-primary", name: "HD 219134", bodyType: "star", orbitAu: 0, radiusLabel: "0.78 R☉", massLabel: "0.81 M☉", habitable: 0, summary: "K3V 橙矮星；古老稳定系统（~110 亿年）。", sortOrder: 0 },
    { id: "hd219134-b", name: "HD 219134 b", bodyType: "planet", orbitAu: 0.0388, radiusLabel: "1.60 R⊕", massLabel: "4.74 M⊕", habitable: 0, summary: "近轨凌星超级地球；密度高。最近的凌星系外行星之一。", sortOrder: 1 },
    { id: "hd219134-c", name: "HD 219134 c", bodyType: "planet", orbitAu: 0.0653, radiusLabel: "1.51 R⊕", massLabel: "4.36 M⊕", habitable: 0, summary: "凌星超级地球；可能为岩石质。", sortOrder: 2 },
    { id: "hd219134-f", name: "HD 219134 f", bodyType: "planet", orbitAu: 0.146, radiusLabel: "~1.6 R⊕", massLabel: "7.3 M⊕", habitable: 0, summary: "短周期超级地球。S&F 数据中继站。", sortOrder: 3 },
    { id: "hd219134-d", name: "HD 219134 d", bodyType: "planet", orbitAu: 0.237, radiusLabel: "~1.7 R⊕", massLabel: "16.2 M⊕", habitable: 0, summary: "高质量行星；可能为迷你海王星。", sortOrder: 4 },
    { id: "hd219134-g", name: "HD 219134 g", bodyType: "planet", orbitAu: 0.375, radiusLabel: "~2 R⊕", massLabel: "11 M⊕", habitable: 0, summary: "宜居带内缘附近行星。金融保险机房。", sortOrder: 5 },
    { id: "hd219134-h", name: "HD 219134 h", bodyType: "planet", orbitAu: 3.11, radiusLabel: "~3.5 R⊕", massLabel: "108 M⊕", habitable: 0, summary: "外层亚巨行星；长周期。", sortOrder: 6 }
  ],
  "55cnc": [
    { id: "55cnc-primary", name: "巨蟹座55A / 55 Cancri A", bodyType: "star", orbitAu: 0, radiusLabel: "0.94 R☉", massLabel: "0.91 M☉", habitable: 0, summary: "K0IV-V 亚巨/主序过渡星；古老系统（~103 亿年）。", sortOrder: 0 },
    { id: "55cnc-e", name: "55 Cancri e", bodyType: "planet", orbitAu: 0.0154, radiusLabel: "1.88 R⊕", massLabel: "8.63 M⊕", habitable: 0, summary: "超短周期超级地球（0.74 天）；表面 ~2700K（熔岩海洋世界）。", sortOrder: 1 },
    { id: "55cnc-b", name: "55 Cancri b", bodyType: "planet", orbitAu: 0.114, radiusLabel: "~12 R⊕", massLabel: "0.80 M♃", habitable: 0, summary: "热类木行星；14.65 天周期。", sortOrder: 2 },
    { id: "55cnc-c", name: "55 Cancri c", bodyType: "planet", orbitAu: 0.237, radiusLabel: "~8 R⊕", massLabel: "0.17 M♃", habitable: 0, summary: "暖土星类行星。", sortOrder: 3 },
    { id: "55cnc-f", name: "55 Cancri f", bodyType: "planet", orbitAu: 0.771, radiusLabel: "~7 R⊕", massLabel: "0.14 M♃", habitable: 0, summary: "近宜居带行星；偏心轨道。S&F 金融模型测试对象。", sortOrder: 4 },
    { id: "55cnc-d", name: "55 Cancri d", bodyType: "planet", orbitAu: 5.44, radiusLabel: "~12 R⊕", massLabel: "3.88 M♃", habitable: 0, summary: "远轨超级木星；巨大卫星系统可能存在。资源采矿。", sortOrder: 5 }
  ],
  "trappist-1": [
    { id: "trappist-1-primary", name: "TRAPPIST-1", bodyType: "star", orbitAu: 0, radiusLabel: "0.12 R☉", massLabel: "0.09 M☉", habitable: 0, summary: "M8V 超冷矮星；极低光度。7 行星轨道共振链（最密集已知行星系统）。", sortOrder: 0 },
    { id: "trappist-1-b", name: "TRAPPIST-1 b", bodyType: "planet", orbitAu: 0.0115, radiusLabel: "1.12 R⊕", massLabel: "1.02 M⊕", habitable: 0, summary: "最内行星；偏热（~400K）；可能失去大部分水。", sortOrder: 1 },
    { id: "trappist-1-c", name: "TRAPPIST-1 c", bodyType: "planet", orbitAu: 0.0158, radiusLabel: "1.10 R⊕", massLabel: "1.16 M⊕", habitable: 0, summary: "内侧行星；厚 CO₂ 大气可能（类金星）。", sortOrder: 2 },
    { id: "trappist-1-d", name: "TRAPPIST-1 d", bodyType: "planet", orbitAu: 0.0223, radiusLabel: "0.79 R⊕", massLabel: "0.30 M⊕", habitable: 0, summary: "最小行星（低于火星质量2倍）；内宜居带边缘。", sortOrder: 3 },
    { id: "trappist-1-e", name: "TRAPPIST-1 e", bodyType: "planet", orbitAu: 0.0293, radiusLabel: "0.92 R⊕", massLabel: "0.77 M⊕", habitable: 1, summary: "最佳宜居候选；地球类密度；温度适宜。JWST 重点表征目标。", sortOrder: 4 },
    { id: "trappist-1-f", name: "TRAPPIST-1 f", bodyType: "planet", orbitAu: 0.0385, radiusLabel: "1.05 R⊕", massLabel: "0.93 M⊕", habitable: 1, summary: "宜居带行星；密度偏低（可能含大量水/冰）。", sortOrder: 5 },
    { id: "trappist-1-g", name: "TRAPPIST-1 g", bodyType: "planet", orbitAu: 0.0469, radiusLabel: "1.13 R⊕", massLabel: "1.15 M⊕", habitable: 1, summary: "外宜居带行星；可能为冰雪世界或有温室大气维持液态水。", sortOrder: 6 },
    { id: "trappist-1-h", name: "TRAPPIST-1 h", bodyType: "planet", orbitAu: 0.0619, radiusLabel: "0.77 R⊕", massLabel: "0.33 M⊕", habitable: 0, summary: "最外行星；偏冷（~170K）。冰冻小世界。", sortOrder: 7 }
  ],
  "li-hartman": [
    { id: "li-hartman-primary", name: "_李-哈特曼_ / _Li-Hartman_", bodyType: "star", orbitAu: 0, radiusLabel: "_0.80 R☉_", massLabel: "_0.78 M☉_", habitable: 0, summary: "_K3V 橙矮星；架空恒星。稳定低耀斑，宜居条件优异。_", sortOrder: 0 },
    { id: "li-hartman-yuanye", name: "_原野星_", bodyType: "planet", orbitAu: 0.45, radiusLabel: "_0.9 R⊕_", massLabel: "_0.8 M⊕_", habitable: 1, summary: "_宜居带内缘；广袤草地与浅海。远岭联营首批殖民目标。_", sortOrder: 1 },
    { id: "li-hartman-caoyuan", name: "_草原星_", bodyType: "planet", orbitAu: 0.62, radiusLabel: "_1.05 R⊕_", massLabel: "_1.1 M⊕_", habitable: 1, summary: "_宜居带核心；最适宜行星。原生生态系统丰富。故事主舞台。_", sortOrder: 2 },
    { id: "li-hartman-youhai", name: "_釉海星_", bodyType: "planet", orbitAu: 0.78, radiusLabel: "_1.15 R⊕_", massLabel: "_1.4 M⊕_", habitable: 1, summary: "_宜居带外缘；大面积釉质海洋（高矿物质）。渔业与化工。_", sortOrder: 3 },
    { id: "li-hartman-xia", name: "_匣_", bodyType: "planet", orbitAu: 0.38, radiusLabel: "_0.85 R⊕_", massLabel: "_0.7 M⊕_", habitable: 1, summary: "_宜居带内侧；干燥行星，地下水系统。矿业与密封城市。_", sortOrder: 4 },
    { id: "li-hartman-queqiong", name: "_阙穹_", bodyType: "planet", orbitAu: 3.2, radiusLabel: "_10.5 R⊕_", massLabel: "_280 M⊕_", habitable: 0, summary: "_类木巨行星；76 颗已知卫星。聚变燃料来源和外行星区引力锚。_", sortOrder: 5 },
    { id: "li-hartman-queqiong-s1", name: "_阙穹-壹_", bodyType: "moon", orbitAu: 0.003, radiusLabel: "_0.35 R⊕_", massLabel: "_0.015 M⊕_", habitable: 0, summary: "_阙穹最大卫星；冰壳下可能有液态水。科研站。_", sortOrder: 6, parentId: "li-hartman-queqiong" },
    { id: "li-hartman-queqiong-s2", name: "_阙穹-贰_", bodyType: "moon", orbitAu: 0.005, radiusLabel: "_0.28 R⊕_", massLabel: "_0.008 M⊕_", habitable: 0, summary: "_阙穹第二大卫星；火山活动活跃。矿物采掘。_", sortOrder: 7, parentId: "li-hartman-queqiong" }
  ],
  hd20794: [
    { id: "hd20794-primary", name: "波江座82 / HD 20794", bodyType: "star", orbitAu: 0, radiusLabel: "0.92 R☉", massLabel: "0.70 M☉", habitable: 0, summary: "G6V 类太阳恒星；稳定。群星联合旗舰。", sortOrder: 0 },
    { id: "hd20794-b", name: "HD 20794 b", bodyType: "planet", orbitAu: 0.121, radiusLabel: "~1.3 R⊕", massLabel: "2.7 M⊕", habitable: 0, summary: "近轨超级地球；偏热。", sortOrder: 1 },
    { id: "hd20794-c", name: "HD 20794 c", bodyType: "planet", orbitAu: 0.204, radiusLabel: "~1.3 R⊕", massLabel: "2.4 M⊕", habitable: 0, summary: "短周期行星。", sortOrder: 2 },
    { id: "hd20794-d", name: "HD 20794 d", bodyType: "planet", orbitAu: 0.364, radiusLabel: "~1.6 R⊕", massLabel: "4.77 M⊕", habitable: 0, summary: "宜居带内缘超级地球；群星联合正统旗舰殖民信托核心。", sortOrder: 3 }
  ],
  lhs1140: [
    { id: "lhs1140-primary", name: "LHS 1140", bodyType: "star", orbitAu: 0, radiusLabel: "0.21 R☉", massLabel: "0.18 M☉", habitable: 0, summary: "M4.5V 红矮星；相对安静。", sortOrder: 0 },
    { id: "lhs1140-c", name: "LHS 1140 c", bodyType: "planet", orbitAu: 0.0266, radiusLabel: "1.27 R⊕", massLabel: "1.81 M⊕", habitable: 0, summary: "近轨热岩石行星。", sortOrder: 1 },
    { id: "lhs1140-b", name: "LHS 1140 b", bodyType: "planet", orbitAu: 0.0946, radiusLabel: "1.73 R⊕", massLabel: "6.48 M⊕", habitable: 1, summary: "宜居带超级地球；可能有大气层和液态水。JWST 重点目标。", sortOrder: 2 }
  ],
  gj357: [
    { id: "gj357-primary", name: "GJ 357", bodyType: "star", orbitAu: 0, radiusLabel: "0.34 R☉", massLabel: "0.34 M☉", habitable: 0, summary: "M2.5V 红矮星；低活动。", sortOrder: 0 },
    { id: "gj357-b", name: "GJ 357 b", bodyType: "planet", orbitAu: 0.035, radiusLabel: "1.22 R⊕", massLabel: "1.84 M⊕", habitable: 0, summary: "近轨凌星热行星。", sortOrder: 1 },
    { id: "gj357-c", name: "GJ 357 c", bodyType: "planet", orbitAu: 0.061, radiusLabel: "~1.5 R⊕", massLabel: "3.4 M⊕", habitable: 0, summary: "中轨行星。", sortOrder: 2 },
    { id: "gj357-d", name: "GJ 357 d（候选）", bodyType: "planet", orbitAu: 0.204, radiusLabel: "~1.7 R⊕", massLabel: "6.1 M⊕", habitable: 1, summary: "宜居带超级地球候选；需确认不是伪信号。", sortOrder: 3 }
  ],
  gj667c: [
    { id: "gj667c-a", name: "GJ 667 A", bodyType: "star", orbitAu: 0, radiusLabel: "0.76 R☉", massLabel: "0.73 M☉", habitable: 0, summary: "K3V 主星；三合星 A 组分。距 C 约 230 AU。", sortOrder: 0 },
    { id: "gj667c-primary", name: "GJ 667 C（主星）", bodyType: "star", orbitAu: 230, radiusLabel: "0.34 R☉", massLabel: "0.33 M☉", habitable: 0, summary: "M1.5V；行星系统所在恒星。三合星 C 组分。", sortOrder: 1 },
    { id: "gj667c-cb", name: "GJ 667 Cb", bodyType: "planet", orbitAu: 0.0505, radiusLabel: "~1.7 R⊕", massLabel: "5.6 M⊕", habitable: 0, summary: "近轨超级地球；偏热。", sortOrder: 2 },
    { id: "gj667c-cc", name: "GJ 667 Cc", bodyType: "planet", orbitAu: 0.125, radiusLabel: "~1.5 R⊕", massLabel: "3.8 M⊕", habitable: 1, summary: "宜居带超级地球；南爪边境主殖民行星。", sortOrder: 3 }
  ]
};
