from __future__ import annotations


FACTION_COLORS = {
    "太阳系": "#f4f2de",
    "无限未来": "#ff6575",
    "人类群星": "#68a8ff",
    "明日晨曦": "#ffc857",
    "S&F": "#b28cff",
    "美丽花园巨企": "#78dd8a",
    "半人马联合重工": "#e68a4e",
    "星蓝元素": "#2bd7ff",
    "巴纳德星际动力": "#b9bdc5",
    "拉卡伊冶金公会": "#d5eef2",
    "沃尔夫潮汐能源财团": "#6fd3c7",
    "Ross 128生态城邦": "#a3efb6",
    "远岭联营": "#e6b06f",
    "南爪边境开发集团": "#d070ff",
    "格利泽远星物流网络": "#c8b87a",
    "大衮远洋探索集团": "#5ba8c4",
    "安第斯大气工程公司": "#7ecba1",
    "外环水蛇-北落师门采掘同盟": "#b9b86b",
    "许可/争议区": "#93a0ad",
    "无/无所属": "#8ca6c8",
    "白矮星科研封存区": "#dfe8ff",
}


TIMELINE_MARKS = [
    {"year": 2278, "label": "太阳系内战消息开始外传"},
    {"year": 2300, "label": "巨企联合禁运太阳系"},
    {"year": 2348, "label": "恒开集团创立"},
    {"year": 2350, "label": "本图默认时间点"},
    {"year": 2362, "label": "恒开击败明日晨曦"},
    {"year": 2373, "label": "五巨企格局"},
    {"year": 2395, "label": "太合建立"},
    {"year": 2402, "label": "太阳邦联格局成形"},
]


STAR_OVERRIDES = {
    "sol": {
        "objectType": "star_system",
        "spectralClass": "G",
        "starCount": 1,
        "planetCount": 8,
        "confirmedPlanets": 8,
        "candidatePlanets": 0,
        "factionType": "母星政体",
        "age": "约 46 亿年",
        "lifespan": "主序期约 100 亿年；约 50 亿年后进入红巨星阶段并最终成为白矮星。",
        "disasters": "太阳风、耀斑、日冕物质抛射；红巨星阶段会吞没水星和金星，并可能波及地球。",
        "hz_inner": 0.95,
        "hz_outer": 1.67,
        "rule_info_time": 0.30,
        "info_speed": 1.0,
        "ftl_speed": 1.0,
    },
    "alpha": {"spectralClass": "G/K/M", "starCount": 3, "planetCount": 3, "confirmedPlanets": 2, "candidatePlanets": 1, "factionType": "军工/重工"},
    "barnard": {"spectralClass": "M", "planetCount": 4, "confirmedPlanets": 4, "factionType": "军工/动力"},
    "wolf1061": {"spectralClass": "M", "planetCount": 3, "confirmedPlanets": 3, "factionType": "能源财团"},
    "gj625": {"spectralClass": "M", "planetCount": 1, "confirmedPlanets": 1, "factionType": "许可/矿业"},
    "vega": {"spectralClass": "A", "planetCount": 0, "confirmedPlanets": 0, "objectType": "star_system", "factionType": "外环采掘", "displayUntil": None},
    "gj887": {"spectralClass": "M", "planetCount": 4, "confirmedPlanets": 3, "candidatePlanets": 1, "factionType": "材料/冶金"},
    "fomalhaut": {"spectralClass": "A", "planetCount": 0, "confirmedPlanets": 0, "factionType": "外环采掘"},
    "ross128": {"spectralClass": "M", "planetCount": 1, "confirmedPlanets": 1, "factionType": "生态城邦"},
    "gj667c": {"spectralClass": "K/M", "starCount": 3, "planetCount": 5, "confirmedPlanets": 2, "candidatePlanets": 3, "factionType": "边境开发"},
    "epsilon-indi": {"spectralClass": "K/T", "starCount": 3, "planetCount": 1, "confirmedPlanets": 1, "factionType": "军工/燃料"},
    "gj682": {"spectralClass": "M", "planetCount": 2, "confirmedPlanets": 0, "candidatePlanets": 2, "factionType": "边境开发"},
    "beta-hydri": {"spectralClass": "G", "planetCount": 0, "confirmedPlanets": 0, "factionType": "外环科研"},
    "uv-ceti": {"spectralClass": "M", "starCount": 2, "planetCount": 1, "candidatePlanets": 1, "factionType": "保险/科研争议区"},
    "groombridge34": {"spectralClass": "M", "starCount": 2, "planetCount": 2, "confirmedPlanets": 2, "factionType": "金融数据"},
    "tau-ceti": {
        "spectralClass": "G",
        "planetCount": 4,
        "confirmedPlanets": 4,
        "candidatePlanets": 4,
        "factionType": "生态/医药",
        "age": "约 58 亿年",
        "lifespan": "G8.5V 主序寿命约 120-140 亿年。",
        "disasters": "相对安静但碎屑盘尘埃丰度偏高，长期航道需要微陨石防护。",
        "hz_inner": 0.55,
        "hz_outer": 1.16,
        "rule_info_time": 0.22,
        "info_speed": 1.0,
        "ftl_speed": 1.0,
    },
    "teegarden": {
        "spectralClass": "M",
        "planetCount": 3,
        "confirmedPlanets": 3,
        "factionType": "生态/医药",
        "age": "约 80 亿年以上",
        "lifespan": "低质量 M 型红矮星，主序寿命可达数千亿年量级。",
        "disasters": "近轨宜居带潮汐锁定、恒星风与红矮星耀斑风险；老年低活动期利于生态工程。",
        "hz_inner": 0.025,
        "hz_outer": 0.05,
        "rule_info_time": 0.18,
        "info_speed": 1.0,
        "ftl_speed": 1.0,
    },
    "gj1002": {
        "spectralClass": "M",
        "planetCount": 2,
        "confirmedPlanets": 2,
        "factionType": "新路线生态",
        "age": "成熟红矮星；现实资料强调活动较低但未给出统一精确年龄。",
        "lifespan": "M5.5V 红矮星，主序寿命远超太阳，可达数千亿年量级。",
        "disasters": "红矮星宜居带近轨潮汐锁定；年轻期耀斑/紫外风险高，成熟期相对安静。",
        "hz_inner": 0.045,
        "hz_outer": 0.075,
        "rule_info_time": 0.18,
        "info_speed": 1.0,
        "ftl_speed": 1.0,
    },
    "hd219134": {
        "spectralClass": "K",
        "planetCount": 6,
        "confirmedPlanets": 6,
        "factionType": "金融数据",
        "age": "约 110 亿年以上的老 K 型星",
        "lifespan": "K3V 主序寿命通常长于太阳，可达约 200-300 亿年量级。",
        "disasters": "近轨热岩石行星受强辐照；老年 K 型主星整体活动较温和。",
        "hz_inner": 0.40,
        "hz_outer": 0.75,
        "rule_info_time": 0.24,
        "info_speed": 1.0,
        "ftl_speed": 1.0,
    },
    "107piscium": {"spectralClass": "K", "planetCount": 0, "confirmedPlanets": 0, "candidatePlanets": 1, "factionType": "金融许可"},
    "wolf359": {"spectralClass": "M", "planetCount": 1, "candidatePlanets": 1, "factionType": "封闭科技"},
    "lalande": {"spectralClass": "M", "planetCount": 2, "confirmedPlanets": 2, "factionType": "消费电子/封闭生态"},
    "gj273": {"spectralClass": "M", "planetCount": 4, "confirmedPlanets": 2, "candidatePlanets": 2, "factionType": "人口盘"},
    "gj251": {"spectralClass": "M", "planetCount": 1, "confirmedPlanets": 1, "factionType": "外围工厂"},
    "epsilon-eridani": {
        "spectralClass": "K",
        "planetCount": 1,
        "confirmedPlanets": 1,
        "candidatePlanets": 2,
        "factionType": "造船/债券",
        "age": "约 4-8 亿年，年轻 K 型星。",
        "lifespan": "K2V 主序寿命约 200 亿年量级。",
        "disasters": "年轻恒星活动强、恒星风和碎屑盘尘埃风险高；适合造船资源，不适合无防护殖民。",
        "hz_inner": 0.50,
        "hz_outer": 0.95,
        "rule_info_time": 0.20,
        "info_speed": 1.0,
        "ftl_speed": 1.0,
    },
    "gj1061": {"spectralClass": "M", "planetCount": 3, "confirmedPlanets": 3, "factionType": "群星生态"},
    "kapteyn": {"spectralClass": "M", "planetCount": 0, "candidatePlanets": 2, "factionType": "老殖民/军政"},
    "40eridani": {"spectralClass": "K/DA/M", "starCount": 3, "planetCount": 1, "candidatePlanets": 1, "factionType": "行政/科研"},
    "hd20794": {"spectralClass": "G", "planetCount": 3, "confirmedPlanets": 3, "candidatePlanets": 1, "factionType": "正统殖民"},
    "li-hartman": {
        "name": "_李-哈特曼_ / _Li-Hartman_",
        "short": "_Li-Hartman_",
        "octant": "++-",
        "order": 5.7,
        "distance": 22.2,
        "arrival": 2300.2,
        "xyz": [0.6, 9.2, -20.2],
        "spectralClass": "K",
        "planetCount": 8,
        "confirmedPlanets": 8,
        "factionType": "地方联营",
        "className": "_K3V 橙矮星（架空）_",
        "planets": "_原野星、草原星、釉海星、匣为主级宜居/准宜居；阙穹 76 卫星。_",
        "reality": "_架空锚点，置于 GJ 1002 附近的 -+-/++- 象限交界处，坐标用于星蓝元素-自动舰接触线推演。_",
        "setting": "_边境黄金压力锅：远岭联营经营权，母星方保留法理和黄金股。_",
        "age": "_约 60 亿年，黑子少、耀斑罕见。_",
        "lifespan": "_K3V 橙矮星，主序寿命约 200-300 亿年；2350 年仍处稳定中年期。_",
        "disasters": "_低耀斑但宜居带紧凑，多行星交通拥挤；小行星带、海盗和地球化设备故障是主要灾害。_",
        "hz_inner": 0.36,
        "hz_outer": 0.62,
        "rule_info_time": 0.35,
        "info_speed": 1.0,
        "ftl_speed": 1.0,
    },
    "ltt1445": {"spectralClass": "M", "starCount": 3, "planetCount": 3, "confirmedPlanets": 3, "candidatePlanets": 1, "factionType": "科研许可"},
}


STAR_OVERRIDES.update(
    {
        "trappist-1": {
            "age": "约 70-80 亿年量级的老年超冷红矮星。",
            "lifespan": "M8V 超低质量红矮星，主序寿命可达数万亿年量级。",
            "disasters": "极紧凑轨道、潮汐锁定、早期耀斑和长时间高能辐射史；行星间扰动强。",
            "hz_inner": 0.024,
            "hz_outer": 0.050,
            "rule_info_time": 0.20,
        },
        "lhs1140": {
            "age": "老年低质量红矮星，活动相对温和但年龄口径仍有区间。",
            "lifespan": "M4.5V 红矮星主序寿命远超太阳，可达数千亿年量级。",
            "disasters": "宜居带贴近主星，潮汐锁定和早期红矮星高能辐射是主要风险。",
            "hz_inner": 0.075,
            "hz_outer": 0.145,
            "rule_info_time": 0.20,
        },
        "gj357": {
            "age": "成熟 M 型红矮星，现实年龄约束不如行星轨道稳健。",
            "lifespan": "M2.5V 红矮星主序寿命数百亿年至千亿年量级。",
            "disasters": "宜居带近轨潮汐锁定；外侧候选需厚大气，内侧行星高温。",
            "hz_inner": 0.12,
            "hz_outer": 0.24,
            "rule_info_time": 0.16,
        },
        "55cnc": {
            "age": "约 80-100 亿年量级的老年 K 型主星系统。",
            "lifespan": "K0 主星寿命长于太阳，但伴星和多巨行星会增加长期动力学复杂度。",
            "disasters": "超热超级地球、近轨巨行星与多巨行星摄动；稳定类地宜居轨道需要谨慎评估。",
            "hz_inner": 0.80,
            "hz_outer": 1.60,
            "rule_info_time": 0.16,
        },
        "hd40307": {
            "age": "K 型主星，中老年低活动口径较常见。",
            "lifespan": "K2.5V 主序寿命显著长于太阳，约数百亿年量级。",
            "disasters": "多超级地球紧凑内侧系统；外侧 g 候选信号和性质存在争议。",
            "hz_inner": 0.50,
            "hz_outer": 0.95,
            "rule_info_time": 0.18,
        },
        "hd85512": {
            "age": "K6V 老年低质量主星，活动通常低于年轻红矮星。",
            "lifespan": "K6V 主序寿命可达数百亿年量级。",
            "disasters": "候选行星接近宜居带内缘，云量、反照率和温室效应决定宜居性。",
            "hz_inner": 0.22,
            "hz_outer": 0.45,
            "rule_info_time": 0.14,
        },
        "l98-59": {
            "age": "成熟 M 型红矮星，多岩石行星系统。",
            "lifespan": "M3V 红矮星主序寿命远超太阳。",
            "disasters": "紧凑内侧轨道、潮汐锁定和水分流失风险；不列稳健宜居。",
            "hz_inner": 0.08,
            "hz_outer": 0.17,
            "rule_info_time": 0.10,
        },
        "gliese486": {
            "age": "成熟 M 型红矮星。",
            "lifespan": "M3.5V 红矮星寿命远超太阳。",
            "disasters": "热超级地球受强辐照，适合研究大气剥蚀，不适合宜居殖民。",
            "hz_inner": 0.07,
            "hz_outer": 0.15,
            "rule_info_time": 0.08,
        },
        "gliese436": {
            "age": "老年 M 型红矮星系统。",
            "lifespan": "M2.5V 红矮星主序寿命数百亿年以上。",
            "disasters": "热海王星大气逃逸和强辐照；无稳健宜居世界。",
            "hz_inner": 0.12,
            "hz_outer": 0.24,
            "rule_info_time": 0.12,
        },
        "61vir": {
            "age": "约 60 亿年以上的太阳型近邻。",
            "lifespan": "G5V 主序寿命略长于太阳。",
            "disasters": "已知低质量行星偏内侧，温和区缺少确认类地行星。",
            "hz_inner": 0.70,
            "hz_outer": 1.35,
            "rule_info_time": 0.10,
        },
        "hd69830": {
            "age": "K0V 中老年主星，带多海王星质量行星和尘埃盘。",
            "lifespan": "K0V 主序寿命长于太阳。",
            "disasters": "尘埃盘微陨石风险和多海王星轨道摄动；不列稳健宜居。",
            "hz_inner": 0.65,
            "hz_outer": 1.25,
            "rule_info_time": 0.12,
        },
        "ups-and": {
            "age": "F 型主星，多巨行星系统。",
            "lifespan": "F8V 主序寿命短于太阳或接近太阳量级下限。",
            "disasters": "高偏心巨行星和伴星摄动显著；宜居类地轨道稳定性差。",
            "hz_inner": 1.20,
            "hz_outer": 2.30,
            "rule_info_time": 0.08,
        },
        "47uma": {
            "age": "类太阳 G 型星，外侧巨行星系统。",
            "lifespan": "G1V 主序寿命与太阳同量级。",
            "disasters": "多巨行星结构类似外太阳系，但未确认类地宜居行星。",
            "hz_inner": 0.95,
            "hz_outer": 1.75,
            "rule_info_time": 0.08,
        },
        "gj433": {
            "age": "成熟 M 型红矮星。",
            "lifespan": "M2V 红矮星主序寿命远超太阳。",
            "disasters": "内侧热超级地球与外侧寒冷行星为主，不列稳健宜居。",
            "hz_inner": 0.14,
            "hz_outer": 0.28,
            "rule_info_time": 0.12,
        },
        "gj180": {
            "age": "成熟 M 型红矮星，行星清单仍含候选不确定性。",
            "lifespan": "M2V 红矮星主序寿命远超太阳。",
            "disasters": "红矮星近轨宜居带和候选置信争议；殖民宣传需保守。",
            "hz_inner": 0.11,
            "hz_outer": 0.23,
            "rule_info_time": 0.16,
        },
    }
)


EXTRA_STARS = [
    {
        "id": "luhman16",
        "name": "Luhman 16 / WISE 1049-5319",
        "short": "Luhman 16",
        "octant": "+-+",
        "order": 1.1,
        "distance": 6.51,
        "arrival": 2284.51,
        "xyz": [1.7, -6.3, 0.6],
        "faction": "无/无所属",
        "rank": "-",
        "className": "L/T 褐矮星双星",
        "planets": "0 宜居；褐矮星天气、磁层与冷资源观测价值高。",
        "reality": "太阳近邻褐矮星双星，位于 25 光年内，无已知宜居行星。",
        "setting": "近太阳深空导航与低温传感器校准站，商业价值低但科研和军用被动探测价值高。",
        "habitable": 0,
        "status": "minor",
        "objectType": "brown_dwarf",
        "spectralClass": "L/T",
        "starCount": 2,
        "planetCount": 0,
        "confirmedPlanets": 0,
        "candidatePlanets": 0,
        "factionType": "自然/科研",
    },
    {
        "id": "wise0855",
        "name": "WISE 0855-0714",
        "short": "WISE 0855",
        "octant": "--+",
        "order": 0.5,
        "distance": 7.43,
        "arrival": 2285.43,
        "xyz": [-3.9, -5.6, 2.9],
        "faction": "无/无所属",
        "rank": "-",
        "className": "Y 型亚褐矮星",
        "planets": "0 宜居；极低温亚恒星天体。",
        "reality": "太阳近邻亚褐矮星/行星质量天体，无行星系统确认。",
        "setting": "无限未来走廊旁的冷暗导航盲点，适合监听、隐蔽仓和无人探针剧情。",
        "habitable": 0,
        "status": "minor",
        "objectType": "substellar_object",
        "spectralClass": "Y",
        "starCount": 1,
        "planetCount": 0,
        "confirmedPlanets": 0,
        "candidatePlanets": 0,
        "factionType": "自然/科研",
    },
    {
        "id": "sirius",
        "name": "Sirius / 天狼星",
        "short": "Sirius",
        "octant": "---",
        "order": 0.5,
        "distance": 8.60,
        "arrival": 2286.60,
        "xyz": [-5.8, -6.2, -1.3],
        "faction": "无/无所属",
        "rank": "-",
        "className": "A1V + DA 白矮星",
        "planets": "0 宜居；强光主星与白矮星伴星，适合光学、材料和白矮星科研。",
        "reality": "著名近邻双星，无确认行星。",
        "setting": "太阳周边最醒目的灯塔星，2350 年更像航标和高能材料科研节点，不给强巨企本土。",
        "habitable": 0,
        "status": "minor",
        "objectType": "star_system",
        "spectralClass": "A/DA",
        "starCount": 2,
        "planetCount": 0,
        "confirmedPlanets": 0,
        "candidatePlanets": 0,
        "factionType": "自然/科研",
    },
    {
        "id": "ez-aqr",
        "name": "EZ Aquarii",
        "short": "EZ Aqr",
        "octant": "-+-",
        "order": 0.8,
        "distance": 11.27,
        "arrival": 2289.27,
        "xyz": [-2.8, 0.8, -10.9],
        "faction": "无/无所属",
        "rank": "-",
        "className": "M 型三合星",
        "planets": "0 宜居；紧密红矮星三体动力学复杂。",
        "reality": "近邻红矮星三合星，无稳健行星确认。",
        "setting": "位于美丽花园/S&F 走廊旁，适合做三体导航实验和早期失败殖民保险标的。",
        "habitable": 0,
        "status": "minor",
        "objectType": "star_system",
        "spectralClass": "M",
        "starCount": 3,
        "planetCount": 0,
        "confirmedPlanets": 0,
        "candidatePlanets": 0,
        "factionType": "自然/科研",
    },
    {
        "id": "61cyg",
        "name": "61 Cygni",
        "short": "61 Cyg",
        "octant": "++-",
        "order": 1.5,
        "distance": 11.40,
        "arrival": 2289.40,
        "xyz": [1.5, 11.2, -1.2],
        "faction": "无/无所属",
        "rank": "-",
        "className": "K5V + K7V",
        "planets": "0 宜居确认；K 型双星，长期稳定观测价值高。",
        "reality": "近邻 K 型双星，无确认宜居行星。",
        "setting": "拉卡伊冶金与外环航线之间的老牌航标和测距基准。",
        "habitable": 0,
        "status": "minor",
        "objectType": "star_system",
        "spectralClass": "K",
        "starCount": 2,
        "planetCount": 0,
        "confirmedPlanets": 0,
        "candidatePlanets": 0,
        "factionType": "自然/科研",
    },
    {
        "id": "procyon",
        "name": "Procyon / 南河三",
        "short": "Procyon",
        "octant": "--+",
        "order": 0.7,
        "distance": 11.46,
        "arrival": 2289.46,
        "xyz": [-9.3, -6.2, 2.6],
        "faction": "无/无所属",
        "rank": "-",
        "className": "F5IV-V + DQZ 白矮星",
        "planets": "0 宜居；亚巨星演化与白矮星伴星使长期殖民吸引力有限。",
        "reality": "近邻双星，无确认行星。",
        "setting": "无限未来外侧的高亮航标，商业叙事以观测、光帆测试和白矮星材料为主。",
        "habitable": 0,
        "status": "minor",
        "objectType": "star_system",
        "spectralClass": "F/D",
        "starCount": 2,
        "planetCount": 0,
        "confirmedPlanets": 0,
        "candidatePlanets": 0,
        "factionType": "自然/科研",
    },
    {
        "id": "struve2398",
        "name": "Struve 2398 / Gliese 725",
        "short": "Struve 2398",
        "octant": "+++",
        "order": 1.4,
        "distance": 11.52,
        "arrival": 2289.52,
        "xyz": [0.2, 10.3, 5.2],
        "faction": "无/无所属",
        "rank": "-",
        "className": "M3V + M3.5V",
        "planets": "0 宜居确认；双红矮星冷工业站潜力。",
        "reality": "近邻红矮星双星，无确认行星。",
        "setting": "+++ 空洞中的维修、监听和机器人补给点，避免破坏沃尔夫/Barnard 的核心势力连续性。",
        "habitable": 0,
        "status": "minor",
        "objectType": "star_system",
        "spectralClass": "M",
        "starCount": 2,
        "planetCount": 0,
        "confirmedPlanets": 0,
        "candidatePlanets": 0,
        "factionType": "自然/科研",
    },
    {
        "id": "dx-cancri",
        "name": "DX Cancri",
        "short": "DX Cnc",
        "octant": "--+",
        "order": 2.5,
        "distance": 11.82,
        "arrival": 2289.82,
        "xyz": [-9.3, -3.0, 6.7],
        "faction": "无/无所属",
        "rank": "-",
        "className": "M6V",
        "planets": "0 宜居确认；低质量红矮星。",
        "reality": "近邻红矮星，无确认行星。",
        "setting": "无限未来走廊里的廉价中继与无人仓储点。",
        "habitable": 0,
        "status": "minor",
        "objectType": "star_system",
        "spectralClass": "M",
        "starCount": 1,
        "planetCount": 0,
        "confirmedPlanets": 0,
        "candidatePlanets": 0,
        "factionType": "自然/科研",
    },
    {
        "id": "yz-ceti",
        "name": "YZ Ceti",
        "short": "YZ Ceti",
        "octant": "-+-",
        "order": 2.6,
        "distance": 12.11,
        "arrival": 2290.11,
        "xyz": [-2.1, 1.2, -11.9],
        "faction": "无/无所属",
        "rank": "-",
        "className": "M4.5V",
        "planets": "3 近轨岩石行星；0 宜居。",
        "reality": "已知多颗近轨行星，整体偏热。",
        "setting": "Tau Ceti 附近的热岩石资源与磁层实验场，常被美丽花园包装成生态技术副项目。",
        "habitable": 0,
        "status": "minor",
        "objectType": "star_system",
        "spectralClass": "M",
        "starCount": 1,
        "planetCount": 3,
        "confirmedPlanets": 3,
        "candidatePlanets": 0,
        "factionType": "自然/科研",
    },
    {
        "id": "scr1845",
        "name": "SCR 1845-6357",
        "short": "SCR 1845",
        "octant": "+--",
        "order": 2.5,
        "distance": 13.05,
        "arrival": 2291.05,
        "xyz": [10.5, -5.7, -5.2],
        "faction": "无/无所属",
        "rank": "-",
        "className": "M8.5V + T6",
        "planets": "0 宜居；超冷红矮星与褐矮星伴星。",
        "reality": "近邻低温双体系统，无确认行星。",
        "setting": "近邻三角外围的冷暗科研节点，可作为隐蔽航线标记。",
        "habitable": 0,
        "status": "minor",
        "objectType": "brown_dwarf",
        "spectralClass": "M/T",
        "starCount": 2,
        "planetCount": 0,
        "confirmedPlanets": 0,
        "candidatePlanets": 0,
        "factionType": "自然/科研",
    },
    {
        "id": "denis1048",
        "name": "DENIS 1048-3956",
        "short": "DENIS 1048",
        "octant": "+-+",
        "order": 1.4,
        "distance": 13.17,
        "arrival": 2291.17,
        "xyz": [1.9, -12.4, 3.9],
        "faction": "无/无所属",
        "rank": "-",
        "className": "M8.5V",
        "planets": "0 宜居；超冷红矮星。",
        "reality": "太阳近邻低质量恒星，无确认行星。",
        "setting": "Ross 128 外侧的冷暗补给点，生态城邦与科研站共同使用。",
        "habitable": 0,
        "status": "minor",
        "objectType": "star_system",
        "spectralClass": "M",
        "starCount": 1,
        "planetCount": 0,
        "confirmedPlanets": 0,
        "candidatePlanets": 0,
        "factionType": "自然/科研",
    },
    {
        "id": "kruger60",
        "name": "Kruger 60",
        "short": "Kruger 60",
        "octant": "-+-",
        "order": 2.8,
        "distance": 13.15,
        "arrival": 2291.15,
        "xyz": [-3.3, 12.7, 0.0],
        "faction": "无/无所属",
        "rank": "-",
        "className": "M3V + M4V",
        "planets": "0 宜居确认；红矮星双星。",
        "reality": "近邻双红矮星，无确认行星。",
        "setting": "S&F 数据走廊边缘的低价中继和冷备份点。",
        "habitable": 0,
        "status": "minor",
        "objectType": "star_system",
        "spectralClass": "M",
        "starCount": 2,
        "planetCount": 0,
        "confirmedPlanets": 0,
        "candidatePlanets": 0,
        "factionType": "自然/科研",
    },
    {
        "id": "van-maanen",
        "name": "Van Maanen 2",
        "short": "Van Maanen",
        "octant": "-+-",
        "order": 3.2,
        "distance": 14.07,
        "arrival": 2292.07,
        "xyz": [-4.0, 6.4, -11.9],
        "faction": "白矮星科研封存区",
        "rank": "-",
        "className": "DZ 白矮星",
        "planets": "0 宜居；白矮星碎屑污染与行星遗骸研究。",
        "reality": "近邻孤立白矮星，无确认现存宜居行星。",
        "setting": "S&F 与美丽花园都采购过的白矮星法证科研点，常用于判断古老行星碎片成分。",
        "habitable": 0,
        "status": "minor",
        "objectType": "white_dwarf",
        "spectralClass": "DZ",
        "starCount": 1,
        "planetCount": 0,
        "confirmedPlanets": 0,
        "candidatePlanets": 0,
        "factionType": "白矮星科研",
    },
    {
        "id": "gliese1",
        "name": "Gliese 1",
        "short": "Gliese 1",
        "octant": "+--",
        "order": 3.5,
        "distance": 14.17,
        "arrival": 2292.17,
        "xyz": [3.3, -1.0, -13.7],
        "faction": "无/无所属",
        "rank": "-",
        "className": "M1.5V",
        "planets": "0 宜居确认；近邻红矮星。",
        "reality": "近邻红矮星，无确认行星。",
        "setting": "近邻三角与南方群星之间的中性导航点。",
        "habitable": 0,
        "status": "minor",
        "objectType": "star_system",
        "spectralClass": "M",
        "starCount": 1,
        "planetCount": 0,
        "confirmedPlanets": 0,
        "candidatePlanets": 0,
        "factionType": "自然/科研",
    },
    {
        "id": "wolf424",
        "name": "Wolf 424 / FL Virginis",
        "short": "Wolf 424",
        "octant": "+-+",
        "order": 1.6,
        "distance": 14.32,
        "arrival": 2292.32,
        "xyz": [0.9, -4.6, 13.5],
        "faction": "无/无所属",
        "rank": "-",
        "className": "M dwarf binary",
        "planets": "0 宜居确认；双红矮星。",
        "reality": "近邻红矮星双星，无确认宜居行星。",
        "setting": "Ross 128 上方的高纬监听点，适合生态城邦防务预警。",
        "habitable": 0,
        "status": "minor",
        "objectType": "star_system",
        "spectralClass": "M",
        "starCount": 2,
        "planetCount": 0,
        "confirmedPlanets": 0,
        "candidatePlanets": 0,
        "factionType": "自然/科研",
    },
    {
        "id": "gj674",
        "name": "GJ 674",
        "short": "GJ 674",
        "octant": "+--",
        "order": 4.2,
        "distance": 14.84,
        "arrival": 2292.84,
        "xyz": [14.1, -4.3, -1.8],
        "faction": "无/无所属",
        "rank": "-",
        "className": "M2.5V",
        "planets": "1 近轨类海王星；0 宜居。",
        "reality": "已知一颗短周期行星，非宜居。",
        "setting": "南爪边境前哨旁的行星形成与潮汐工程训练地。",
        "habitable": 0,
        "status": "minor",
        "objectType": "star_system",
        "spectralClass": "M",
        "starCount": 1,
        "planetCount": 1,
        "confirmedPlanets": 1,
        "candidatePlanets": 0,
        "factionType": "自然/科研",
    },
    {
        "id": "gj876",
        "name": "Gliese 876",
        "short": "GJ 876",
        "octant": "++-",
        "order": 1.8,
        "distance": 15.20,
        "arrival": 2293.20,
        "xyz": [4.7, 6.1, -13.1],
        "faction": "无/无所属",
        "rank": "-",
        "className": "M4V",
        "planets": "4 确认行星；共振巨行星系统，0 稳健宜居。",
        "reality": "著名多行星红矮星系统，存在强轨道共振。",
        "setting": "拉卡伊冶金公会常用的轨道动力学靶场和船坞模拟数据源。",
        "habitable": 0,
        "status": "minor",
        "objectType": "star_system",
        "spectralClass": "M",
        "starCount": 1,
        "planetCount": 4,
        "confirmedPlanets": 4,
        "candidatePlanets": 0,
        "factionType": "自然/科研",
    },
    {
        "id": "ad-leonis",
        "name": "AD Leonis / Gliese 388",
        "short": "AD Leo",
        "octant": "--+",
        "order": 4.5,
        "distance": 16.19,
        "arrival": 2294.19,
        "xyz": [-7.5, -5.6, 13.2],
        "faction": "无/无所属",
        "rank": "-",
        "className": "M3.5V 耀星",
        "planets": "0 宜居确认；耀发极强。",
        "reality": "著名活跃红矮星，无确认宜居行星。",
        "setting": "无限未来外围的防辐射材料和脑机抗干扰测试场。",
        "habitable": 0,
        "status": "minor",
        "objectType": "star_system",
        "spectralClass": "M",
        "starCount": 1,
        "planetCount": 0,
        "confirmedPlanets": 0,
        "candidatePlanets": 0,
        "factionType": "自然/科研",
    },
    {
        "id": "70oph",
        "name": "70 Ophiuchi",
        "short": "70 Oph",
        "octant": "+++",
        "order": 2.7,
        "distance": 16.64,
        "arrival": 2294.64,
        "xyz": [14.1, 8.1, 3.3],
        "faction": "无/无所属",
        "rank": "-",
        "className": "K0V + K5V",
        "planets": "0 宜居确认；近邻 K 型双星。",
        "reality": "近邻双星，无稳健行星确认。",
        "setting": "+++ 方向的大型光学基准站，服务沃尔夫和巴纳德外围航线。",
        "habitable": 0,
        "status": "minor",
        "objectType": "star_system",
        "spectralClass": "K",
        "starCount": 2,
        "planetCount": 0,
        "confirmedPlanets": 0,
        "candidatePlanets": 0,
        "factionType": "自然/科研",
    },
    {
        "id": "altair",
        "name": "Altair / 河鼓二",
        "short": "Altair",
        "octant": "++-",
        "order": 3.4,
        "distance": 16.73,
        "arrival": 2294.73,
        "xyz": [11.1, 12.2, -2.6],
        "faction": "无/无所属",
        "rank": "-",
        "className": "A7V",
        "planets": "0 宜居确认；高速自转亮星。",
        "reality": "明亮近邻 A 型星，无确认行星。",
        "setting": "外环宣传航线上的可见灯塔，商业价值偏文化和光学基准。",
        "habitable": 0,
        "status": "minor",
        "objectType": "star_system",
        "spectralClass": "A",
        "starCount": 1,
        "planetCount": 0,
        "confirmedPlanets": 0,
        "candidatePlanets": 0,
        "factionType": "自然/科研",
    },
    {
        "id": "stein2051",
        "name": "Stein 2051",
        "short": "Stein 2051",
        "octant": "-++",
        "order": 1,
        "distance": 18.06,
        "arrival": 2296.06,
        "xyz": [-15.3, 9.2, 2.6],
        "faction": "白矮星科研封存区",
        "rank": "-",
        "className": "M4V + DC 白矮星",
        "planets": "0 宜居；红矮星与白矮星双星。",
        "reality": "近邻双星，无确认行星。",
        "setting": "-++ 空洞区的科研封存点，可放自动舰隐藏节点但不放强巨企本土。",
        "habitable": 0,
        "status": "minor",
        "objectType": "white_dwarf",
        "spectralClass": "M/DC",
        "starCount": 2,
        "planetCount": 0,
        "confirmedPlanets": 0,
        "candidatePlanets": 0,
        "factionType": "白矮星科研",
    },
    {
        "id": "sigma-dra",
        "name": "Sigma Draconis",
        "short": "Sigma Dra",
        "octant": "-++",
        "order": 2,
        "distance": 18.77,
        "arrival": 2296.77,
        "xyz": [-3.4, 17.1, 7.0],
        "faction": "无/无所属",
        "rank": "-",
        "className": "K0V",
        "planets": "0 宜居确认；稳定 K 型星。",
        "reality": "近邻 K 型星，无确认行星。",
        "setting": "-++ 象限的稳定恒星基准，保留为空洞区中继。",
        "habitable": 0,
        "status": "minor",
        "objectType": "star_system",
        "spectralClass": "K",
        "starCount": 1,
        "planetCount": 0,
        "confirmedPlanets": 0,
        "candidatePlanets": 0,
        "factionType": "自然/科研",
    },
    {
        "id": "gliese229",
        "name": "Gliese 229",
        "short": "GJ 229",
        "octant": "---",
        "order": 0.8,
        "distance": 18.80,
        "arrival": 2296.80,
        "xyz": [-11.8, -13.4, -5.9],
        "faction": "无/无所属",
        "rank": "-",
        "className": "M1V + T 褐矮星",
        "planets": "0 宜居；褐矮星伴星科研价值高。",
        "reality": "著名红矮星 + 褐矮星伴星系统。",
        "setting": "人类群星联合南方走廊外侧的冷天体实验室。",
        "habitable": 0,
        "status": "minor",
        "objectType": "brown_dwarf",
        "spectralClass": "M/T",
        "starCount": 2,
        "planetCount": 0,
        "confirmedPlanets": 0,
        "candidatePlanets": 0,
        "factionType": "自然/科研",
    },
    {
        "id": "gliese570",
        "name": "Gliese 570",
        "short": "GJ 570",
        "octant": "+-+",
        "order": 1.9,
        "distance": 19.00,
        "arrival": 2297.00,
        "xyz": [14.1, -6.8, 10.8],
        "faction": "无/无所属",
        "rank": "-",
        "className": "K4V + M + T 褐矮星",
        "planets": "0 宜居确认；多星与褐矮星伴星。",
        "reality": "近邻多星系统，含 T 型褐矮星。",
        "setting": "Ross 128 与南爪边境之间的复杂多星导航训练点。",
        "habitable": 0,
        "status": "minor",
        "objectType": "brown_dwarf",
        "spectralClass": "K/M/T",
        "starCount": 4,
        "planetCount": 0,
        "confirmedPlanets": 0,
        "candidatePlanets": 0,
        "factionType": "自然/科研",
    },
    {
        "id": "v1216sgr",
        "name": "V1216 Sagittarii / GJ 729",
        "short": "V1216 Sgr",
        "octant": "++-",
        "order": 3.8,
        "distance": 19.20,
        "arrival": 2297.20,
        "xyz": [18.5, 3.7, -3.4],
        "faction": "无/无所属",
        "rank": "-",
        "className": "M3.5V 耀星",
        "planets": "0 宜居确认；活跃红矮星。",
        "reality": "近邻耀星，无确认行星。",
        "setting": "外环航路中的耀发预警与防护材料测试点。",
        "habitable": 0,
        "status": "minor",
        "objectType": "star_system",
        "spectralClass": "M",
        "starCount": 1,
        "planetCount": 0,
        "confirmedPlanets": 0,
        "candidatePlanets": 0,
        "factionType": "自然/科研",
    },
    {
        "id": "eta-cas",
        "name": "Eta Cassiopeiae",
        "short": "Eta Cas",
        "octant": "-+-",
        "order": 3.9,
        "distance": 19.42,
        "arrival": 2297.42,
        "xyz": [-10.4, 16.3, -1.7],
        "faction": "无/无所属",
        "rank": "-",
        "className": "G0V + K7V",
        "planets": "0 宜居确认；太阳型双星。",
        "reality": "近邻 G/K 双星，无确认行星。",
        "setting": "S&F 北侧的老牌航标和光谱标定站。",
        "habitable": 0,
        "status": "minor",
        "objectType": "star_system",
        "spectralClass": "G/K",
        "starCount": 2,
        "planetCount": 0,
        "confirmedPlanets": 0,
        "candidatePlanets": 0,
        "factionType": "自然/科研",
    },
    {
        "id": "36oph",
        "name": "36 Ophiuchi",
        "short": "36 Oph",
        "octant": "+-+",
        "order": 2.1,
        "distance": 19.50,
        "arrival": 2297.50,
        "xyz": [19.4, -0.6, 2.3],
        "faction": "无/无所属",
        "rank": "-",
        "className": "K dwarf triple",
        "planets": "0 宜居确认；K 型三合星。",
        "reality": "近邻 K 型多星系统。",
        "setting": "南爪边境与 Ross 128 方向之间的多星稳定性研究点。",
        "habitable": 0,
        "status": "minor",
        "objectType": "star_system",
        "spectralClass": "K",
        "starCount": 3,
        "planetCount": 0,
        "confirmedPlanets": 0,
        "candidatePlanets": 0,
        "factionType": "自然/科研",
    },
    {
        "id": "delta-pav",
        "name": "Delta Pavonis",
        "short": "Delta Pav",
        "octant": "+--",
        "order": 4.5,
        "distance": 19.92,
        "arrival": 2297.92,
        "xyz": [14.5, -8.5, -10.7],
        "faction": "无/无所属",
        "rank": "-",
        "className": "G8IV",
        "planets": "0 宜居确认；老化类太阳星。",
        "reality": "近邻类太阳亚巨星，无确认行星。",
        "setting": "南方外环的恒星演化与撤离工程案例库。",
        "habitable": 0,
        "status": "minor",
        "objectType": "star_system",
        "spectralClass": "G",
        "starCount": 1,
        "planetCount": 0,
        "confirmedPlanets": 0,
        "candidatePlanets": 0,
        "factionType": "自然/科研",
    },
    {
        "id": "eq-peg",
        "name": "EQ Pegasi",
        "short": "EQ Peg",
        "octant": "-+-",
        "order": 4.2,
        "distance": 20.43,
        "arrival": 2298.43,
        "xyz": [-2.4, 15.7, -12.9],
        "faction": "无/无所属",
        "rank": "-",
        "className": "M dwarf binary",
        "planets": "0 宜居确认；活跃红矮星双星。",
        "reality": "近邻红矮星双星，无确认行星。",
        "setting": "S&F 与 GJ1002 之间的危险耀发中继点。",
        "habitable": 0,
        "status": "minor",
        "objectType": "star_system",
        "spectralClass": "M",
        "starCount": 2,
        "planetCount": 0,
        "confirmedPlanets": 0,
        "candidatePlanets": 0,
        "factionType": "自然/科研",
    },
    {
        "id": "gliese581",
        "name": "Gliese 581",
        "short": "GJ 581",
        "octant": "+-+",
        "order": 2.2,
        "distance": 20.55,
        "arrival": 2298.55,
        "xyz": [15.7, -1.6, 13.2],
        "faction": "许可/争议区",
        "rank": "-",
        "className": "M3V",
        "planets": "3 确认行星；早年宜居宣传争议大，2350 设为失败生物圈和清算区。",
        "reality": "历史上多宜居候选争议，后续许多候选被削弱或否定。",
        "setting": "美丽花园旧时代投机项目失败后，被 S&F 清算并改为医学与生态法证试验区。",
        "habitable": 0,
        "status": "license",
        "objectType": "star_system",
        "spectralClass": "M",
        "starCount": 1,
        "planetCount": 3,
        "confirmedPlanets": 3,
        "candidatePlanets": 0,
        "factionType": "争议/清算",
    },
    {
        "id": "xi-bootis",
        "name": "Xi Bootis",
        "short": "Xi Boo",
        "octant": "+++",
        "order": 4.5,
        "distance": 21.80,
        "arrival": 2299.80,
        "xyz": [9.6, 4.1, 19.1],
        "faction": "无/无所属",
        "rank": "-",
        "className": "G8V + K4V",
        "planets": "0 宜居确认；G/K 双星。",
        "reality": "近邻双星，无确认行星。",
        "setting": "+++ 高纬的观测基准站，避免设为强巨企本土。",
        "habitable": 0,
        "status": "minor",
        "objectType": "star_system",
        "spectralClass": "G/K",
        "starCount": 2,
        "planetCount": 0,
        "confirmedPlanets": 0,
        "candidatePlanets": 0,
        "factionType": "自然/科研",
    },
    {
        "id": "gliese832",
        "name": "Gliese 832",
        "short": "GJ 832",
        "octant": "+--",
        "order": 2.8,
        "distance": 16.20,
        "arrival": 2294.20,
        "xyz": [11.0, -2.1, -11.7],
        "faction": "无/无所属",
        "rank": "-",
        "className": "M1.5V",
        "planets": "1 巨行星确认；旧宜居候选后续被削弱。",
        "reality": "已知巨行星系统，曾有宜居候选争议。",
        "setting": "Epsilon Indi 到 GJ 682 之间的冷冻物流与燃料带。",
        "habitable": 0,
        "status": "minor",
        "objectType": "star_system",
        "spectralClass": "M",
        "starCount": 1,
        "planetCount": 1,
        "confirmedPlanets": 1,
        "candidatePlanets": 0,
        "factionType": "自然/科研",
    },
    {
        "id": "gliese486",
        "name": "Gliese 486 / GJ 486",
        "short": "GJ 486",
        "octant": "+-+",
        "order": 20,
        "distance": 26.40,
        "arrival": 2304.40,
        "xyz": [4.0, -6.8, 25.2],
        "faction": "无/无所属",
        "rank": "-",
        "className": "M3.5V",
        "planets": "1 确认热超级地球；0 宜居。",
        "reality": "近邻 M 型星，已知热超级地球 GJ 486 b。",
        "setting": "内环热岩石大气剥蚀与红矮星行星气候实验站。",
        "habitable": 0,
        "status": "outer",
        "objectType": "star_system",
        "spectralClass": "M",
        "starCount": 1,
        "planetCount": 1,
        "confirmedPlanets": 1,
        "candidatePlanets": 0,
        "factionType": "自然/科研",
    },
    {
        "id": "61vir",
        "name": "61 Virginis",
        "short": "61 Vir",
        "octant": "+-+",
        "order": 21,
        "distance": 27.90,
        "arrival": 2305.90,
        "xyz": [13.4, -14.9, 19.4],
        "faction": "无/无所属",
        "rank": "-",
        "className": "G5V",
        "planets": "3 确认低质量行星；0 稳健宜居。",
        "reality": "近太阳型多行星系统，已知行星多在内侧轨道。",
        "setting": "太阳型低质量行星样本库，作为内太阳系殖民失败模型对照。",
        "habitable": 0,
        "status": "outer",
        "objectType": "star_system",
        "spectralClass": "G",
        "starCount": 1,
        "planetCount": 3,
        "confirmedPlanets": 3,
        "candidatePlanets": 0,
        "factionType": "自然/科研",
    },
    {
        "id": "gj433",
        "name": "Gliese 433 / GJ 433",
        "short": "GJ 433",
        "octant": "+-+",
        "order": 22,
        "distance": 29.50,
        "arrival": 2307.50,
        "xyz": [6.7, -25.3, 13.7],
        "faction": "Ross 128生态城邦",
        "rank": 11,
        "className": "M2V",
        "planets": "3 确认行星；0 稳健宜居，外侧冷超级地球有气候研究价值。",
        "reality": "近邻红矮星多行星系统，已知行星以热/冷超级地球和海王星类为主。",
        "setting": "Ross 128 生态城邦外侧气候档案站，保留生态工程失败样本。",
        "habitable": 0,
        "status": "outer",
        "objectType": "star_system",
        "spectralClass": "M",
        "starCount": 1,
        "planetCount": 3,
        "confirmedPlanets": 3,
        "candidatePlanets": 0,
        "factionType": "生态/科研",
    },
    {
        "id": "gliese436",
        "name": "Gliese 436 / GJ 436",
        "short": "GJ 436",
        "octant": "--+",
        "order": 20,
        "distance": 31.80,
        "arrival": 2309.80,
        "xyz": [-7.3, -4.3, 30.7],
        "faction": "S&F",
        "rank": 4,
        "className": "M2.5V",
        "planets": "1 确认热海王星；0 宜居。",
        "reality": "著名热海王星 GJ 436 b 系统，轨道很近且有逃逸大气研究价值。",
        "setting": "S&F 外环保险精算样本，专门评估大气逃逸、热海王星迁移与资产风险。",
        "habitable": 0,
        "status": "outer",
        "objectType": "star_system",
        "spectralClass": "M",
        "starCount": 1,
        "planetCount": 1,
        "confirmedPlanets": 1,
        "candidatePlanets": 0,
        "factionType": "金融数据",
    },
    {
        "id": "gj357",
        "name": "Gliese 357 / GJ 357",
        "short": "GJ 357",
        "octant": "--+",
        "order": 21,
        "distance": 30.70,
        "arrival": 2308.70,
        "xyz": [-7.9, -27.3, 11.5],
        "faction": "美丽花园巨企",
        "rank": 6,
        "className": "M2.5V",
        "planets": "3 确认行星；GJ 357 d 为外侧宜居带候选。",
        "reality": "GJ 357 b 为近轨热超级地球；GJ 357 d 常列为潜在宜居候选。",
        "setting": "美丽花园巨企在外环下注的冷生态候选，因红矮星气候风险长期未完全商品化。",
        "habitable": 1,
        "status": "outer",
        "objectType": "star_system",
        "spectralClass": "M",
        "starCount": 1,
        "planetCount": 3,
        "confirmedPlanets": 3,
        "candidatePlanets": 0,
        "factionType": "生态/医药",
    },
    {
        "id": "hd69830",
        "name": "HD 69830",
        "short": "HD 69830",
        "octant": "--+",
        "order": 22,
        "distance": 40.70,
        "arrival": 2318.70,
        "xyz": [-23.0, -32.3, 9.0],
        "faction": "S&F",
        "rank": 4,
        "className": "K0V",
        "planets": "3 确认海王星质量行星；碎屑/尘埃盘；0 稳健宜居。",
        "reality": "K 型多行星与尘埃盘系统，行星多为海王星质量。",
        "setting": "S&F 外环抵押品评估星系，尘埃盘资源和三海王星系统用于风险打包。",
        "habitable": 0,
        "status": "outer",
        "objectType": "star_system",
        "spectralClass": "K",
        "starCount": 1,
        "planetCount": 3,
        "confirmedPlanets": 3,
        "candidatePlanets": 0,
        "factionType": "金融数据",
    },
    {
        "id": "55cnc",
        "name": "55 Cancri / Copernicus",
        "short": "55 Cnc",
        "octant": "--+",
        "order": 23,
        "distance": 40.90,
        "arrival": 2318.90,
        "xyz": [-31.0, -9.4, 25.0],
        "faction": "S&F",
        "rank": 4,
        "className": "K0IV-V + M dwarf",
        "planets": "5 确认行星；热超级地球与多颗巨行星；0 稳健宜居。",
        "reality": "著名近邻多行星系统，至少五颗围绕 55 Cancri A 的行星。",
        "setting": "S&F 外环旗舰资产证券化样本，热超级地球和巨行星轨道让保险模型极度复杂。",
        "habitable": 0,
        "status": "outer",
        "objectType": "star_system",
        "spectralClass": "K/M",
        "starCount": 2,
        "planetCount": 5,
        "confirmedPlanets": 5,
        "candidatePlanets": 0,
        "factionType": "金融数据",
    },
    {
        "id": "gamma-pav",
        "name": "Gamma Pavonis",
        "short": "Gamma Pav",
        "octant": "+--",
        "order": 20,
        "distance": 30.20,
        "arrival": 2308.20,
        "xyz": [19.6, -12.2, -19.5],
        "faction": "无/无所属",
        "rank": "-",
        "className": "F6V",
        "planets": "0 确认行星；0 宜居确认。",
        "reality": "近邻 F 型恒星，未列入稳健宜居行星系统。",
        "setting": "外环 F 型恒星基准灯塔，用于校准快速自转、紫外环境和航标测光。",
        "habitable": 0,
        "status": "outer",
        "objectType": "star_system",
        "spectralClass": "F",
        "starCount": 1,
        "planetCount": 0,
        "confirmedPlanets": 0,
        "candidatePlanets": 0,
        "factionType": "自然/科研",
    },
    {
        "id": "l98-59",
        "name": "L 98-59 / TOI-175",
        "short": "L 98-59",
        "octant": "+--",
        "order": 21,
        "distance": 34.60,
        "arrival": 2312.60,
        "xyz": [6.8, -32.3, -10.5],
        "faction": "无/无所属",
        "rank": "-",
        "className": "M3V",
        "planets": "4-5 近轨岩石/低密度行星；0 稳健宜居。",
        "reality": "TESS 近邻多岩石行星系统，行星多在内侧紧凑轨道。",
        "setting": "紧凑多岩石行星实验场，适合研究内侧行星大气保持与海洋流失。",
        "habitable": 0,
        "status": "outer",
        "objectType": "star_system",
        "spectralClass": "M",
        "starCount": 1,
        "planetCount": 5,
        "confirmedPlanets": 4,
        "candidatePlanets": 1,
        "factionType": "自然/科研",
    },
    {
        "id": "gj180",
        "name": "Gliese 180 / GJ 180",
        "short": "GJ 180",
        "octant": "---",
        "order": 20,
        "distance": 39.50,
        "arrival": 2317.50,
        "xyz": [-26.2, -19.8, -21.9],
        "faction": "人类群星联合",
        "rank": 2,
        "className": "M2V",
        "planets": "3 候选/确认低质量行星；1 低置信宜居带候选。",
        "reality": "近邻红矮星多行星候选系统，GJ 180 c 曾列为宜居带超级地球候选。",
        "setting": "人类群星联合外环档案殖民地，因行星置信争议长期只保留测绘与移民债券。",
        "habitable": 1,
        "status": "outer",
        "objectType": "star_system",
        "spectralClass": "M",
        "starCount": 1,
        "planetCount": 3,
        "confirmedPlanets": 2,
        "candidatePlanets": 1,
        "factionType": "正统殖民",
    },
    {
        "id": "hd40307",
        "name": "HD 40307",
        "short": "HD 40307",
        "octant": "---",
        "order": 21,
        "distance": 42.00,
        "arrival": 2320.00,
        "xyz": [-0.8, -36.2, -21.2],
        "faction": "人类群星联合",
        "rank": 2,
        "className": "K2.5V",
        "planets": "6 候选/确认超级地球；HD 40307 g 为低置信宜居带候选。",
        "reality": "多超级地球系统，外侧 g 候选曾被提出为宜居带超级地球但仍需保守处理。",
        "setting": "群星联合远端宣传星系，债券文本比殖民工程更成熟。",
        "habitable": 1,
        "status": "outer",
        "objectType": "star_system",
        "spectralClass": "K",
        "starCount": 1,
        "planetCount": 6,
        "confirmedPlanets": 3,
        "candidatePlanets": 3,
        "factionType": "正统殖民",
    },
    {
        "id": "trappist-1",
        "name": "TRAPPIST-1",
        "short": "TRAPPIST-1",
        "octant": "++-",
        "order": 20,
        "distance": 40.66,
        "arrival": 2318.66,
        "xyz": [7.8, 21.0, -34.0],
        "faction": "星蓝元素",
        "rank": 5,
        "className": "M8V 超冷红矮星",
        "planets": "7 确认类地行星；3 颗常列入宜居带/温和候选。",
        "reality": "约 40 光年外的七类地行星系统，是最著名的紧凑宜居带红矮星系统之一。",
        "setting": "星蓝元素外环蓝生计划二线样板，因潮汐锁定和耀斑历史被自动舰接触线重点监控。",
        "habitable": 3,
        "status": "outer",
        "objectType": "star_system",
        "spectralClass": "M",
        "starCount": 1,
        "planetCount": 7,
        "confirmedPlanets": 7,
        "candidatePlanets": 0,
        "factionType": "新路线生态",
    },
    {
        "id": "lhs1140",
        "name": "LHS 1140",
        "short": "LHS 1140",
        "octant": "-+-",
        "order": 20,
        "distance": 48.80,
        "arrival": 2326.80,
        "xyz": [-4.3, 9.1, -47.7],
        "faction": "星蓝元素",
        "rank": 5,
        "className": "M4.5V",
        "planets": "2 确认行星；LHS 1140 b 为宜居带超级地球/水世界候选。",
        "reality": "LHS 1140 b 位于 M 型星宜居带，轨道约 0.096 AU，是重点大气观测目标。",
        "setting": "星蓝元素在 -+- 外缘保留的冷宜居候选，作为 GJ 1002 接触线后的备份生态方案。",
        "habitable": 1,
        "status": "outer",
        "objectType": "star_system",
        "spectralClass": "M",
        "starCount": 1,
        "planetCount": 2,
        "confirmedPlanets": 2,
        "candidatePlanets": 0,
        "factionType": "新路线生态",
    },
    {
        "id": "ups-and",
        "name": "Upsilon Andromedae",
        "short": "Upsilon And",
        "octant": "-+-",
        "order": 21,
        "distance": 44.30,
        "arrival": 2322.30,
        "xyz": [-27.7, 30.8, -15.6],
        "faction": "无/无所属",
        "rank": "-",
        "className": "F8V + M dwarf",
        "planets": "4 确认巨行星；0 稳健宜居。",
        "reality": "近邻多巨行星系统，主星为 F 型星并有伴星。",
        "setting": "外环巨行星动力学试验场，给巨企航道保险提供高偏心轨道风险案例。",
        "habitable": 0,
        "status": "outer",
        "objectType": "star_system",
        "spectralClass": "F/M",
        "starCount": 2,
        "planetCount": 4,
        "confirmedPlanets": 4,
        "candidatePlanets": 0,
        "factionType": "自然/科研",
    },
    {
        "id": "47uma",
        "name": "47 Ursae Majoris",
        "short": "47 UMa",
        "octant": "-++",
        "order": 20,
        "distance": 45.90,
        "arrival": 2323.90,
        "xyz": [-20.5, 1.5, 41.0],
        "faction": "无/无所属",
        "rank": "-",
        "className": "G1V",
        "planets": "3 确认巨行星；0 稳健宜居类地。",
        "reality": "类太阳多巨行星系统，适合作为外太阳系类比。",
        "setting": "巨行星卫星开发和太阳型主星稳定性研究外环站。",
        "habitable": 0,
        "status": "outer",
        "objectType": "star_system",
        "spectralClass": "G",
        "starCount": 1,
        "planetCount": 3,
        "confirmedPlanets": 3,
        "candidatePlanets": 0,
        "factionType": "自然/科研",
    },
    {
        "id": "hd85512",
        "name": "HD 85512",
        "short": "HD 85512",
        "octant": "+-+",
        "order": 23,
        "distance": 36.50,
        "arrival": 2314.50,
        "xyz": [1.1, -36.1, 5.2],
        "faction": "许可/争议区",
        "rank": "-",
        "className": "K6V",
        "planets": "1 确认/候选超级地球；宜居性争议大。",
        "reality": "HD 85512 b 曾被列为宜居带超级地球候选，但气候和轨道口径需保守。",
        "setting": "许可证争议区，生态宣传价值高于实际殖民把握。",
        "habitable": 1,
        "status": "outer",
        "objectType": "star_system",
        "spectralClass": "K",
        "starCount": 1,
        "planetCount": 1,
        "confirmedPlanets": 1,
        "candidatePlanets": 0,
        "factionType": "许可/争议",
    },
]


SYSTEM_BODY_SEEDS = {
    "sol": [
        {"id": "sol-star", "name": "太阳", "bodyType": "star", "orbitAu": 0.0, "radiusLabel": "G2V；46 亿年", "summary": "人类母星系主星；主序期约 100 亿年，约 50 亿年后进入红巨星阶段。", "sortOrder": 0, "rule_info_time": 0.30},
        {"id": "mercury", "name": "水星", "bodyType": "planet", "orbitAu": 0.39, "radiusLabel": "岩石行星", "massLabel": "0.055 M⊕", "summary": "内侧高温岩石行星；现实平均轨道距离约 0.39 AU。", "sortOrder": 10},
        {"id": "venus", "name": "金星", "bodyType": "planet", "orbitAu": 0.72, "radiusLabel": "岩石行星", "massLabel": "0.815 M⊕", "summary": "高温浓厚大气世界；现实平均轨道距离约 0.72 AU。", "sortOrder": 20},
        {"id": "earth", "name": "地球", "bodyType": "planet", "orbitAu": 1.0, "radiusLabel": "类地行星", "massLabel": "1.0 M⊕", "habitable": 1, "terraformStatus": "natural_habitable", "habitabilityScore": 1.0, "summary": "人类母星；现实平均轨道距离 1 AU。", "sortOrder": 30, "rule_info_time": 0.18},
        {"id": "moon", "parentId": "earth", "name": "月球", "bodyType": "moon", "orbitAu": 1.00257, "radiusLabel": "地球卫星", "massLabel": "0.0123 M⊕；距地约 384,000 km", "terraformStatus": "terraformable", "habitabilityScore": 0.48, "summary": "地球卫星与早期深空工业基地；轨道距离折算约 0.00257 AU。", "sortOrder": 31, "rule_info_time": 0.08},
        {"id": "mars", "name": "火星", "bodyType": "planet", "orbitAu": 1.52, "radiusLabel": "岩石行星", "massLabel": "0.107 M⊕", "terraformStatus": "terraforming", "habitabilityScore": 0.72, "summary": "早期殖民与内战重要节点；现实平均轨道距离约 1.52 AU。", "sortOrder": 40},
        {"id": "asteroid-belt", "name": "主小行星带", "bodyType": "belt", "orbitAu": 2.80, "radiusLabel": "小行星带", "summary": "火星与木星之间的金属、水冰和小天体资源带。", "sortOrder": 50},
        {"id": "jupiter", "name": "木星", "bodyType": "planet", "orbitAu": 5.20, "radiusLabel": "气巨星", "massLabel": "317.8 M⊕", "summary": "外太阳系卫星群和深空工业重心；现实平均轨道距离约 5.20 AU。", "sortOrder": 60},
        {"id": "io", "parentId": "jupiter", "name": "木卫一 / Io", "bodyType": "moon", "orbitAu": 5.2028, "radiusLabel": "火山卫星", "summary": "强潮汐加热与火山活动卫星；木星近侧能源/地质实验节点。", "sortOrder": 61},
        {"id": "europa", "parentId": "jupiter", "name": "木卫二 / Europa", "bodyType": "moon", "orbitAu": 5.2045, "radiusLabel": "冰壳海洋卫星", "terraformStatus": "terraformable", "habitabilityScore": 0.62, "summary": "冰壳下海洋卫星；外太阳系生物与冰下工程研究重点。", "sortOrder": 62},
        {"id": "ganymede", "parentId": "jupiter", "name": "木卫三 / Ganymede", "bodyType": "moon", "orbitAu": 5.2072, "radiusLabel": "太阳系最大卫星", "terraformStatus": "terraformable", "habitabilityScore": 0.58, "summary": "太阳系最大卫星，距木星约 1,070,000 km；重要外太阳系工业节点。", "sortOrder": 63},
        {"id": "callisto", "parentId": "jupiter", "name": "木卫四 / Callisto", "bodyType": "moon", "orbitAu": 5.2126, "radiusLabel": "冰岩卫星", "terraformStatus": "terraformable", "habitabilityScore": 0.52, "summary": "辐射环境较温和的外侧大卫星，适合长期基地与补给。", "sortOrder": 64},
        {"id": "saturn", "name": "土星", "bodyType": "planet", "orbitAu": 9.58, "radiusLabel": "气巨星", "massLabel": "95.2 M⊕", "summary": "环系与卫星资源；现实平均轨道距离约 9.58 AU。", "sortOrder": 70},
        {"id": "titan", "parentId": "saturn", "name": "泰坦 / Titan", "bodyType": "moon", "orbitAu": 9.588, "radiusLabel": "厚大气大型卫星", "terraformStatus": "terraformable", "habitabilityScore": 0.68, "summary": "土星最大卫星，距土星约 1.2 百万 km；厚氮气大气与烃循环使其成为重要殖民/化工节点。", "sortOrder": 71, "rule_info_time": 0.07},
        {"id": "uranus", "name": "天王星", "bodyType": "planet", "orbitAu": 19.20, "radiusLabel": "冰巨星", "massLabel": "14.5 M⊕", "summary": "外太阳系冰巨星；现实平均轨道距离约 19.20 AU。", "sortOrder": 80},
        {"id": "neptune", "name": "海王星", "bodyType": "planet", "orbitAu": 30.05, "radiusLabel": "冰巨星", "massLabel": "17.1 M⊕", "summary": "外侧冰巨星；现实平均轨道距离约 30.05 AU。", "sortOrder": 90},
        {"id": "kuiper-belt", "name": "柯伊伯带", "bodyType": "belt", "orbitAu": 39.0, "radiusLabel": "冰小天体带", "summary": "外缘冰资源、远日点站群和长周期航道储备。", "sortOrder": 100},
    ],
    "alpha": [
        {"id": "alpha-a", "name": "Alpha Centauri A", "bodyType": "star", "orbitAu": 0.0, "radiusLabel": "G2V", "summary": "类太阳主星，旧太阳系军工反复争夺。", "sortOrder": 0},
        {"id": "alpha-b", "name": "Alpha Centauri B", "bodyType": "star", "orbitAu": 23.4, "radiusLabel": "K1V", "summary": "K 型伴星。", "sortOrder": 1},
        {"id": "proxima-star", "name": "Proxima Centauri", "bodyType": "star", "orbitAu": 13000.0, "radiusLabel": "M5.5Ve", "summary": "远距伴星。", "sortOrder": 2},
        {"id": "proxima-b", "parentId": "proxima-star", "name": "Proxima b", "bodyType": "planet", "orbitAu": 0.049, "radiusLabel": "岩石行星", "habitable": 1, "summary": "极端宜居带行星，耀斑与潮汐锁定风险高。", "sortOrder": 3},
        {"id": "alpha-ab-yard", "name": "_AB 船坞带_", "bodyType": "station", "orbitAu": 1.2, "radiusLabel": "轨道设施", "summary": "_半人马联合重工核心船坞与试验场。_", "sortOrder": 4},
    ],
    "li-hartman": [
        {"id": "li-star", "name": "_李-哈特曼_主星", "bodyType": "star", "orbitAu": 0.0, "radiusLabel": "K3V；0.74 M☉；0.21 L☉", "summary": "_60 亿年橙矮星，黑子少、耀斑罕见，宜居带 0.36-0.62 AU。_", "sortOrder": 0, "rule_info_time": 0.35, "terraformStatus": "none", "habitabilityScore": 0},
        {"id": "wihiga", "name": "_炽页_ / _Vihiga_", "bodyType": "planet", "orbitAu": 0.18, "radiusLabel": "水星级岩石行星", "summary": "_水星类潮汐锁定热岩石球，反射镜阵与无人采能站。_", "sortOrder": 10, "terraformStatus": "none", "habitabilityScore": 0},
        {"id": "pa-caoyuan", "name": "_草原星_ / _Pa-Caoyuan_", "bodyType": "planet", "orbitAu": 0.42, "radiusLabel": "半地球化类地；0.93 M⊕；1.04 g", "habitable": 1, "summary": "_地球化未完工约 78%，全星约 52 万人，本作主舞台。_", "sortOrder": 20, "rule_info_time": 0.16, "terraformStatus": "terraforming", "habitabilityScore": 0.72},
        {"id": "caoyuan-suo", "parentId": "pa-caoyuan", "name": "_朔_ / _Suo_", "bodyType": "moon", "orbitAu": 0.422, "radiusLabel": "草原星小卫星", "summary": "_朔顶穹顶城与草原星通勤居住点所在，夜空常呈细弧朔相。_", "sortOrder": 21, "rule_info_time": 0.06, "terraformStatus": "terraformable", "habitabilityScore": 0.28},
        {"id": "yuan-ye", "name": "_原野星_ / _Yuanye_", "bodyType": "planet", "orbitAu": 0.50, "radiusLabel": "天然类地；第一宜居", "habitable": 1, "summary": "_天生类地，主居住地，约 3050 万人口，多个本地国家。_", "sortOrder": 30, "rule_info_time": 0.20, "terraformStatus": "natural_habitable", "habitabilityScore": 0.96},
        {"id": "glaze", "name": "_釉海星_ / _Glaze_", "bodyType": "planet", "orbitAu": 0.58, "radiusLabel": "厚大气浮空文明", "habitable": 1, "summary": "_第二大居住地，约 1200 万浮空城市民，厚云海和 50-60 km 浮空带。_", "sortOrder": 40, "rule_info_time": 0.16, "terraformStatus": "habitable", "habitabilityScore": 0.78},
        {"id": "glaze-hu", "parentId": "glaze", "name": "_瑚_ / _Hu_", "bodyType": "moon", "orbitAu": 0.582, "radiusLabel": "釉海星可改造卫星", "habitable": 1, "summary": "_釉海星卫星，穹顶与部分裸露地球化工程节点。_", "sortOrder": 41, "terraformStatus": "terraforming", "habitabilityScore": 0.55},
        {"id": "inner-belt", "name": "_内带小行星带_", "bodyType": "belt", "orbitAu": 0.95, "radiusLabel": "0.8-1.1 AU 小行星带", "summary": "_铁镍和贵金属资源带。_", "sortOrder": 50},
        {"id": "ringbox", "name": "_环匣_ / _Ringbox_", "bodyType": "planet", "orbitAu": 1.30, "radiusLabel": "迷你海王星", "summary": "_金融中心，主卫星匣可半地球化，匣都人口约 600 万。_", "sortOrder": 60, "rule_info_time": 0.14, "terraformStatus": "none", "habitabilityScore": 0},
        {"id": "ringbox-xia", "parentId": "ringbox", "name": "_匣_ / _Xia_", "bodyType": "moon", "orbitAu": 1.306, "radiusLabel": "半地球化主卫星", "habitable": 1, "summary": "_环匣主卫星，金融、保险和结算设施高度集中。_", "sortOrder": 61, "rule_info_time": 0.12, "terraformStatus": "terraforming", "habitabilityScore": 0.62},
        {"id": "qiong", "name": "_阙穹_ / _Quevon_", "bodyType": "planet", "orbitAu": 3.40, "radiusLabel": "气巨星；76 卫星", "summary": "_氦-3 心脏、环系空间站群和 76 颗卫星的外侧重心。_", "sortOrder": 70, "rule_info_time": 0.10, "terraformStatus": "none", "habitabilityScore": 0},
        {"id": "qiong-mo", "parentId": "qiong", "name": "_阙穹-墨_", "bodyType": "moon", "orbitAu": 3.43, "radiusLabel": "可改造卫星", "habitable": 1, "summary": "_气巨星卫星中最有改造价值的一颗。_", "sortOrder": 71, "rule_info_time": 0.08, "terraformStatus": "terraformable", "habitabilityScore": 0.43},
        {"id": "qiong-qing", "parentId": "qiong", "name": "_阙穹-罄_", "bodyType": "moon", "orbitAu": 3.46, "radiusLabel": "可改造卫星", "habitable": 1, "summary": "_阙穹卫星群中另一颗具穹顶和早期地球化价值的卫星。_", "sortOrder": 72, "terraformStatus": "terraformable", "habitabilityScore": 0.40},
        {"id": "middle-belt", "name": "_中带小行星带_", "bodyType": "belt", "orbitAu": 5.2, "radiusLabel": "4.5-5.5 AU 冰岩带", "summary": "_受阙穹摄动，轨道复杂，海盗与走私活跃。_", "sortOrder": 80},
        {"id": "mota", "name": "_穆塔_ / _Mota_", "bodyType": "planet", "orbitAu": 7.8, "radiusLabel": "冰巨星", "summary": "_开发初期的外侧冰巨星。_", "sortOrder": 90},
        {"id": "sokai", "name": "_锁阶_ / _Sokai_", "bodyType": "planet", "orbitAu": 11.2, "radiusLabel": "冰巨星", "summary": "_测绘哨站和外缘补给点。_", "sortOrder": 100},
        {"id": "li-outer-belt", "name": "_外带柯伊伯带_", "bodyType": "belt", "orbitAu": 18.0, "radiusLabel": "13-40 AU 冰小天体带", "summary": "_长周期彗星、外缘测绘和远期未开发储备。_", "sortOrder": 110},
    ],
    "gj1002": [
        {"id": "gj1002-star", "name": "GJ 1002", "bodyType": "star", "orbitAu": 0.0, "radiusLabel": "M5.5V；成熟低活动红矮星", "summary": "成熟近邻红矮星；现实发现两颗地球质量级宜居带行星。", "sortOrder": 0},
        {"id": "gj1002-b", "name": "GJ 1002 b", "bodyType": "planet", "orbitAu": 0.046, "radiusLabel": "地球质量级；约 10 日公转", "habitable": 1, "summary": "温暖宜居带行星，现实口径为地球质量级；_星蓝元素蓝生计划核心。_", "sortOrder": 1},
        {"id": "gj1002-c", "name": "GJ 1002 c", "bodyType": "planet", "orbitAu": 0.074, "radiusLabel": "地球质量级；约 20 日公转", "habitable": 1, "summary": "较冷宜居带行星，现实口径为地球质量级；_智械/义体自治实验区。_", "sortOrder": 2},
    ],
    "teegarden": [
        {"id": "teegarden-star", "name": "Teegarden's Star", "bodyType": "star", "orbitAu": 0.0, "radiusLabel": "M6.5V", "summary": "超冷红矮星。", "sortOrder": 0},
        {"id": "teegarden-b", "name": "Teegarden b", "bodyType": "planet", "orbitAu": 0.025, "radiusLabel": "地球质量级", "habitable": 1, "summary": "美丽花园的顶级生态地产。", "sortOrder": 1},
        {"id": "teegarden-c", "name": "Teegarden c", "bodyType": "planet", "orbitAu": 0.044, "radiusLabel": "地球质量级", "habitable": 1, "summary": "冷生态与长期封闭农业世界。", "sortOrder": 2},
        {"id": "teegarden-garden-ring", "name": "_花园轨道群_", "bodyType": "station", "orbitAu": 0.06, "radiusLabel": "轨道设施", "summary": "_医疗、延寿与生态保全设施。_", "sortOrder": 3},
    ],
    "tau-ceti": [
        {"id": "tau-star", "name": "Tau Ceti", "bodyType": "star", "orbitAu": 0.0, "radiusLabel": "G8.5V", "summary": "类太阳近邻恒星。", "sortOrder": 0},
        {"id": "tau-e", "name": "Tau Ceti e", "bodyType": "planet", "orbitAu": 0.55, "radiusLabel": "超级地球候选", "habitable": 1, "summary": "_半宜居海洋/花园化世界。_现实口径保留争议。", "sortOrder": 1},
        {"id": "tau-f", "name": "Tau Ceti f", "bodyType": "planet", "orbitAu": 1.35, "radiusLabel": "冷超级地球候选", "summary": "冷边界世界。", "sortOrder": 2},
        {"id": "tau-dust", "name": "Tau Ceti 碎屑盘", "bodyType": "belt", "orbitAu": 35.0, "radiusLabel": "碎屑盘", "summary": "尘埃盘和生态工业原料。", "sortOrder": 3},
    ],
    "epsilon-eridani": [
        {"id": "eps-eri-star", "name": "Epsilon Eridani", "bodyType": "star", "orbitAu": 0.0, "radiusLabel": "K2V", "summary": "年轻活跃 K 型星。", "sortOrder": 0},
        {"id": "eps-eri-b", "name": "Epsilon Eridani b", "bodyType": "planet", "orbitAu": 3.5, "radiusLabel": "巨行星", "summary": "_造船联合体的卫星船坞群核心。_", "sortOrder": 1},
        {"id": "eps-eri-debris", "name": "碎屑盘", "bodyType": "belt", "orbitAu": 20.0, "radiusLabel": "碎屑盘", "summary": "现实碎屑盘；_聚变燃料、冰尘和船坞材料来源。_", "sortOrder": 2},
    ],
    "hd219134": [
        {"id": "hd219134-star", "name": "HD 219134", "bodyType": "star", "orbitAu": 0.0, "radiusLabel": "K3V；老年低活动", "summary": "近邻 K 型多行星系统；_S&F 数据核心的主星。_", "sortOrder": 0},
        {"id": "hd219134-b", "name": "HD 219134 b", "bodyType": "planet", "orbitAu": 0.03876, "radiusLabel": "热超级地球；3.1 日公转", "massLabel": "约 4.74 M⊕", "summary": "现实凌星热岩石行星；_数据与资产抵押样本。_", "sortOrder": 1},
        {"id": "hd219134-c", "name": "HD 219134 c", "bodyType": "planet", "orbitAu": 0.065, "radiusLabel": "热超级地球", "summary": "热行星；_金融避难站轨道资产。_", "sortOrder": 2},
        {"id": "hd219134-data-vault", "name": "_S&F 数据穹顶_", "bodyType": "station", "orbitAu": 0.4, "radiusLabel": "数据设施", "summary": "_保险、清算与核心档案节点。_", "sortOrder": 3},
    ],
    "trappist-1": [
        {"id": "trappist-star", "name": "TRAPPIST-1", "bodyType": "star", "orbitAu": 0.0, "radiusLabel": "M8V；超冷红矮星", "summary": "约 40 光年外的七类地行星系统主星；现实研究常把 d/e/f/g 作为温和区间重点。", "sortOrder": 0},
        {"id": "trappist-b", "name": "TRAPPIST-1 b", "bodyType": "planet", "orbitAu": 0.0115, "radiusLabel": "类地；内侧热行星", "summary": "近轨高辐照行星；0 宜居。", "sortOrder": 1},
        {"id": "trappist-c", "name": "TRAPPIST-1 c", "bodyType": "planet", "orbitAu": 0.0158, "radiusLabel": "类地；内侧热行星", "summary": "近轨高辐照行星；0 宜居。", "sortOrder": 2},
        {"id": "trappist-d", "name": "TRAPPIST-1 d", "bodyType": "planet", "orbitAu": 0.0223, "radiusLabel": "类地；内缘温和候选", "habitable": 1, "summary": "内缘温和候选；宜居性依赖大气与水量。", "sortOrder": 3},
        {"id": "trappist-e", "name": "TRAPPIST-1 e", "bodyType": "planet", "orbitAu": 0.0293, "radiusLabel": "类地；宜居带核心候选", "habitable": 1, "summary": "常列为系统内最稳健的温和类地候选之一；_星蓝元素生态样板。_", "sortOrder": 4},
        {"id": "trappist-f", "name": "TRAPPIST-1 f", "bodyType": "planet", "orbitAu": 0.0385, "radiusLabel": "类地；冷宜居带候选", "habitable": 1, "summary": "冷温和候选，可能需要温室大气维持表面液态水。", "sortOrder": 5},
        {"id": "trappist-g", "name": "TRAPPIST-1 g", "bodyType": "planet", "orbitAu": 0.0469, "radiusLabel": "类地；冷边缘候选", "habitable": 1, "summary": "外侧冷边缘候选；保守统计可列准宜居。", "sortOrder": 6},
        {"id": "trappist-h", "name": "TRAPPIST-1 h", "bodyType": "planet", "orbitAu": 0.0619, "radiusLabel": "类地；外侧寒冷行星", "summary": "外侧寒冷行星；0 稳健宜居。", "sortOrder": 7},
    ],
    "lhs1140": [
        {"id": "lhs1140-star", "name": "LHS 1140", "bodyType": "star", "orbitAu": 0.0, "radiusLabel": "M4.5V；红矮星", "summary": "低质量红矮星，拥有宜居带超级地球/水世界候选 LHS 1140 b。", "sortOrder": 0},
        {"id": "lhs1140-c", "name": "LHS 1140 c", "bodyType": "planet", "orbitAu": 0.027, "radiusLabel": "近轨超级地球", "summary": "内侧热行星；0 宜居。", "sortOrder": 1},
        {"id": "lhs1140-b", "name": "LHS 1140 b", "bodyType": "planet", "orbitAu": 0.0957, "radiusLabel": "宜居带超级地球/水世界候选", "massLabel": "约 6.4 M⊕", "habitable": 1, "summary": "宜居带重点大气观测目标；_星蓝元素外缘备份生态方案。_", "sortOrder": 2},
    ],
    "gj357": [
        {"id": "gj357-star", "name": "GJ 357", "bodyType": "star", "orbitAu": 0.0, "radiusLabel": "M2.5V", "summary": "近邻红矮星，拥有热超级地球和外侧宜居带候选。", "sortOrder": 0},
        {"id": "gj357-b", "name": "GJ 357 b", "bodyType": "planet", "orbitAu": 0.035, "radiusLabel": "热超级地球；TESS 凌星", "summary": "近轨高温行星；0 宜居。", "sortOrder": 1},
        {"id": "gj357-c", "name": "GJ 357 c", "bodyType": "planet", "orbitAu": 0.061, "radiusLabel": "温热超级地球", "summary": "中间轨道行星，温度偏高；0 稳健宜居。", "sortOrder": 2},
        {"id": "gj357-d", "name": "GJ 357 d", "bodyType": "planet", "orbitAu": 0.204, "radiusLabel": "冷宜居带候选", "habitable": 1, "summary": "外侧宜居带候选，是否类地和有无厚大气仍需保守。", "sortOrder": 3},
    ],
    "55cnc": [
        {"id": "55cnc-a", "name": "55 Cancri A", "bodyType": "star", "orbitAu": 0.0, "radiusLabel": "K0IV-V", "summary": "近太阳型主星，拥有著名五行星系统。", "sortOrder": 0},
        {"id": "55cnc-bstar", "name": "55 Cancri B", "bodyType": "star", "orbitAu": 1065.0, "radiusLabel": "M dwarf companion", "summary": "远距红矮星伴星。", "sortOrder": 1},
        {"id": "55cnc-e", "name": "55 Cancri e / Janssen", "bodyType": "planet", "orbitAu": 0.0154, "radiusLabel": "超热超级地球", "summary": "著名超短周期热超级地球；0 宜居。", "sortOrder": 2},
        {"id": "55cnc-b", "name": "55 Cancri b / Galileo", "bodyType": "planet", "orbitAu": 0.113, "radiusLabel": "热巨行星", "summary": "近轨巨行星；0 宜居。", "sortOrder": 3},
        {"id": "55cnc-c", "name": "55 Cancri c / Brahe", "bodyType": "planet", "orbitAu": 0.24, "radiusLabel": "巨行星", "summary": "内侧巨行星；0 宜居。", "sortOrder": 4},
        {"id": "55cnc-f", "name": "55 Cancri f / Harriot", "bodyType": "planet", "orbitAu": 0.77, "radiusLabel": "巨行星；宽泛宜居带附近", "summary": "气态行星位于温和辐照区间附近，但不是类地宜居世界。", "sortOrder": 5},
        {"id": "55cnc-d", "name": "55 Cancri d / Lipperhey", "bodyType": "planet", "orbitAu": 5.77, "radiusLabel": "外侧巨行星", "summary": "外侧巨行星；0 宜居。", "sortOrder": 6},
    ],
    "hd40307": [
        {"id": "hd40307-star", "name": "HD 40307", "bodyType": "star", "orbitAu": 0.0, "radiusLabel": "K2.5V", "summary": "K 型多超级地球系统主星。", "sortOrder": 0},
        {"id": "hd40307-b", "name": "HD 40307 b", "bodyType": "planet", "orbitAu": 0.047, "radiusLabel": "内侧超级地球", "summary": "近轨高温超级地球；0 宜居。", "sortOrder": 1},
        {"id": "hd40307-c", "name": "HD 40307 c", "bodyType": "planet", "orbitAu": 0.081, "radiusLabel": "内侧超级地球", "summary": "近轨超级地球；0 宜居。", "sortOrder": 2},
        {"id": "hd40307-d", "name": "HD 40307 d", "bodyType": "planet", "orbitAu": 0.134, "radiusLabel": "内侧超级地球", "summary": "内侧超级地球；0 宜居。", "sortOrder": 3},
        {"id": "hd40307-e", "name": "HD 40307 e", "bodyType": "planet", "orbitAu": 0.188, "radiusLabel": "候选超级地球", "summary": "内侧候选；0 稳健宜居。", "sortOrder": 4},
        {"id": "hd40307-f", "name": "HD 40307 f", "bodyType": "planet", "orbitAu": 0.247, "radiusLabel": "候选超级地球", "summary": "内侧候选；0 稳健宜居。", "sortOrder": 5},
        {"id": "hd40307-g", "name": "HD 40307 g", "bodyType": "planet", "orbitAu": 0.60, "radiusLabel": "低置信宜居带候选", "habitable": 1, "summary": "外侧宜居带候选，信号和性质仍需谨慎。", "sortOrder": 6},
    ],
    "l98-59": [
        {"id": "l98-59-star", "name": "L 98-59", "bodyType": "star", "orbitAu": 0.0, "radiusLabel": "M3V", "summary": "TESS 近邻紧凑多岩石行星系统。", "sortOrder": 0},
        {"id": "l98-59-b", "name": "L 98-59 b", "bodyType": "planet", "orbitAu": 0.0228, "radiusLabel": "小型岩石行星", "summary": "内侧热岩石行星；0 宜居。", "sortOrder": 1},
        {"id": "l98-59-c", "name": "L 98-59 c", "bodyType": "planet", "orbitAu": 0.0317, "radiusLabel": "岩石行星", "summary": "内侧热行星；0 宜居。", "sortOrder": 2},
        {"id": "l98-59-d", "name": "L 98-59 d", "bodyType": "planet", "orbitAu": 0.0486, "radiusLabel": "低密度/可能富水行星", "summary": "内侧温热行星；0 稳健宜居。", "sortOrder": 3},
        {"id": "l98-59-e", "name": "L 98-59 e", "bodyType": "planet", "orbitAu": 0.0717, "radiusLabel": "候选行星", "summary": "外侧候选，但仍不作为稳健宜居世界。", "sortOrder": 4},
    ],
    "gliese486": [
        {"id": "gliese486-star", "name": "GJ 486", "bodyType": "star", "orbitAu": 0.0, "radiusLabel": "M3.5V", "summary": "近邻红矮星，拥有热超级地球。", "sortOrder": 0},
        {"id": "gliese486-b", "name": "GJ 486 b", "bodyType": "planet", "orbitAu": 0.0173, "radiusLabel": "热超级地球", "summary": "高温近轨岩石行星；0 宜居。", "sortOrder": 1},
    ],
    "gliese436": [
        {"id": "gliese436-star", "name": "GJ 436", "bodyType": "star", "orbitAu": 0.0, "radiusLabel": "M2.5V", "summary": "热海王星系统主星。", "sortOrder": 0},
        {"id": "gliese436-b", "name": "GJ 436 b", "bodyType": "planet", "orbitAu": 0.029, "radiusLabel": "热海王星", "summary": "近轨热海王星，大气逃逸研究价值高；0 宜居。", "sortOrder": 1},
    ],
    "61vir": [
        {"id": "61vir-star", "name": "61 Virginis", "bodyType": "star", "orbitAu": 0.0, "radiusLabel": "G5V", "summary": "近太阳型多低质量行星系统。", "sortOrder": 0},
        {"id": "61vir-b", "name": "61 Vir b", "bodyType": "planet", "orbitAu": 0.050, "radiusLabel": "超级地球/迷你海王星", "summary": "内侧热行星；0 宜居。", "sortOrder": 1},
        {"id": "61vir-c", "name": "61 Vir c", "bodyType": "planet", "orbitAu": 0.217, "radiusLabel": "低质量行星", "summary": "内侧温热行星；0 宜居。", "sortOrder": 2},
        {"id": "61vir-d", "name": "61 Vir d", "bodyType": "planet", "orbitAu": 0.476, "radiusLabel": "低质量行星", "summary": "外侧低质量行星；0 稳健宜居。", "sortOrder": 3},
    ],
    "hd69830": [
        {"id": "hd69830-star", "name": "HD 69830", "bodyType": "star", "orbitAu": 0.0, "radiusLabel": "K0V", "summary": "K 型多海王星质量行星与尘埃盘系统。", "sortOrder": 0},
        {"id": "hd69830-b", "name": "HD 69830 b", "bodyType": "planet", "orbitAu": 0.079, "radiusLabel": "海王星质量行星", "summary": "内侧热海王星质量行星；0 宜居。", "sortOrder": 1},
        {"id": "hd69830-c", "name": "HD 69830 c", "bodyType": "planet", "orbitAu": 0.186, "radiusLabel": "海王星质量行星", "summary": "中间轨道海王星质量行星；0 宜居。", "sortOrder": 2},
        {"id": "hd69830-d", "name": "HD 69830 d", "bodyType": "planet", "orbitAu": 0.63, "radiusLabel": "海王星质量行星", "summary": "温和轨道海王星质量行星；不是类地宜居世界。", "sortOrder": 3},
        {"id": "hd69830-dust", "name": "HD 69830 尘埃盘", "bodyType": "belt", "orbitAu": 1.0, "radiusLabel": "热尘埃/碎屑盘", "summary": "现实尘埃盘；_S&F 资源抵押物。_", "sortOrder": 4},
    ],
    "ups-and": [
        {"id": "ups-and-a", "name": "Upsilon Andromedae A", "bodyType": "star", "orbitAu": 0.0, "radiusLabel": "F8V", "summary": "多巨行星系统主星。", "sortOrder": 0},
        {"id": "ups-and-bstar", "name": "Upsilon Andromedae B", "bodyType": "star", "orbitAu": 750.0, "radiusLabel": "M dwarf companion", "summary": "远距红矮星伴星。", "sortOrder": 1},
        {"id": "ups-and-b", "name": "Upsilon And b", "bodyType": "planet", "orbitAu": 0.059, "radiusLabel": "热木星", "summary": "近轨热巨行星；0 宜居。", "sortOrder": 2},
        {"id": "ups-and-c", "name": "Upsilon And c", "bodyType": "planet", "orbitAu": 0.83, "radiusLabel": "巨行星", "summary": "巨行星；0 类地宜居。", "sortOrder": 3},
        {"id": "ups-and-d", "name": "Upsilon And d", "bodyType": "planet", "orbitAu": 2.51, "radiusLabel": "巨行星", "summary": "外侧巨行星；0 类地宜居。", "sortOrder": 4},
        {"id": "ups-and-e", "name": "Upsilon And e", "bodyType": "planet", "orbitAu": 5.25, "radiusLabel": "巨行星", "summary": "远侧巨行星；0 宜居。", "sortOrder": 5},
    ],
    "47uma": [
        {"id": "47uma-star", "name": "47 Ursae Majoris", "bodyType": "star", "orbitAu": 0.0, "radiusLabel": "G1V", "summary": "类太阳巨行星系统主星。", "sortOrder": 0},
        {"id": "47uma-b", "name": "47 UMa b", "bodyType": "planet", "orbitAu": 2.10, "radiusLabel": "巨行星", "summary": "木星类外侧行星；0 类地宜居。", "sortOrder": 1},
        {"id": "47uma-c", "name": "47 UMa c", "bodyType": "planet", "orbitAu": 3.60, "radiusLabel": "巨行星", "summary": "外侧巨行星；0 宜居。", "sortOrder": 2},
        {"id": "47uma-d", "name": "47 UMa d", "bodyType": "planet", "orbitAu": 11.6, "radiusLabel": "巨行星", "summary": "远侧巨行星；0 宜居。", "sortOrder": 3},
    ],
    "hd85512": [
        {"id": "hd85512-star", "name": "HD 85512", "bodyType": "star", "orbitAu": 0.0, "radiusLabel": "K6V", "summary": "K 型星，拥有宜居性争议较大的超级地球候选。", "sortOrder": 0},
        {"id": "hd85512-b", "name": "HD 85512 b", "bodyType": "planet", "orbitAu": 0.26, "radiusLabel": "超级地球候选", "habitable": 1, "summary": "曾被列入宜居带候选，但气候模型与观测置信需保守。", "sortOrder": 1},
    ],
    "gj433": [
        {"id": "gj433-star", "name": "GJ 433", "bodyType": "star", "orbitAu": 0.0, "radiusLabel": "M2V", "summary": "红矮星多行星系统。", "sortOrder": 0},
        {"id": "gj433-b", "name": "GJ 433 b", "bodyType": "planet", "orbitAu": 0.062, "radiusLabel": "超级地球", "summary": "内侧热超级地球；0 宜居。", "sortOrder": 1},
        {"id": "gj433-c", "name": "GJ 433 c", "bodyType": "planet", "orbitAu": 4.7, "radiusLabel": "冷超级地球/海王星类", "summary": "远侧寒冷行星；0 稳健宜居。", "sortOrder": 2},
        {"id": "gj433-d", "name": "GJ 433 d", "bodyType": "planet", "orbitAu": 0.18, "radiusLabel": "超级地球", "summary": "中间轨道行星；0 稳健宜居。", "sortOrder": 3},
    ],
    "gj180": [
        {"id": "gj180-star", "name": "GJ 180", "bodyType": "star", "orbitAu": 0.0, "radiusLabel": "M2V", "summary": "红矮星候选多行星系统。", "sortOrder": 0},
        {"id": "gj180-b", "name": "GJ 180 b", "bodyType": "planet", "orbitAu": 0.092, "radiusLabel": "超级地球候选", "summary": "内侧温热候选；0 稳健宜居。", "sortOrder": 1},
        {"id": "gj180-c", "name": "GJ 180 c", "bodyType": "planet", "orbitAu": 0.129, "radiusLabel": "宜居带超级地球候选", "habitable": 1, "summary": "低置信宜居带候选；现实口径需保守。", "sortOrder": 2},
        {"id": "gj180-d", "name": "GJ 180 d", "bodyType": "planet", "orbitAu": 0.31, "radiusLabel": "外侧候选", "summary": "外侧较冷候选；0 稳健宜居。", "sortOrder": 3},
    ],
}
