from __future__ import annotations


FACTION_COLORS = {
    "太阳系": "#f4f2de",
    "无限未来": "#ff6575",
    "人类群星联合": "#68a8ff",
    "明日晨曦": "#ffc857",
    "S&F": "#b28cff",
    "美丽花园巨企": "#78dd8a",
    "近邻三角军工托管区": "#e68a4e",
    "星蓝元素": "#2bd7ff",
    "巴纳德星际动力": "#b9bdc5",
    "拉卡伊冶金公会": "#d5eef2",
    "沃尔夫潮汐能源财团": "#6fd3c7",
    "Ross 128生态城邦": "#a3efb6",
    "远岭联营": "#e6b06f",
    "南爪边境开发集团": "#d070ff",
    "外环水蛇-北落师门采掘同盟": "#b9b86b",
    "许可/争议区": "#93a0ad",
    "自然天体/科研区": "#8ca6c8",
    "本地星际介质": "#74c0d8",
    "白矮星科研封存区": "#dfe8ff",
}


TIMELINE_MARKS = [
    {"year": 2278, "label": "太阳系内战消息开始外传"},
    {"year": 2300, "label": "巨企联合禁运太阳系"},
    {"year": 2348, "label": "恒开集团创立"},
    {"year": 2350, "label": "本图默认时间点"},
    {"year": 2362, "label": "恒开击败明日晨曦"},
    {"year": 2373, "label": "五巨企格局"},
    {"year": 2395, "label": "太合建立"},
    {"year": 2402, "label": "太阳邦联格局成形"},
]


STAR_OVERRIDES = {
    "sol": {
        "objectType": "star_system",
        "spectralClass": "G",
        "starCount": 1,
        "planetCount": 8,
        "confirmedPlanets": 8,
        "candidatePlanets": 0,
        "factionType": "母星政体",
        "age": "约 46 亿年",
        "lifespan": "主序期约 100 亿年；约 50 亿年后进入红巨星阶段并最终成为白矮星。",
        "disasters": "太阳风、耀斑、日冕物质抛射；红巨星阶段会吞没水星和金星，并可能波及地球。",
        "hz_inner": 0.95,
        "hz_outer": 1.67,
        "rule_info_time": 0.30,
        "info_speed": 1.0,
        "ftl_speed": 1.0,
    },
    "alpha": {"spectralClass": "G/K/M", "starCount": 3, "planetCount": 3, "confirmedPlanets": 2, "candidatePlanets": 1, "factionType": "军工托管"},
    "barnard": {"spectralClass": "M", "planetCount": 4, "confirmedPlanets": 4, "factionType": "军工/动力"},
    "wolf1061": {"spectralClass": "M", "planetCount": 3, "confirmedPlanets": 3, "factionType": "能源财团"},
    "gj625": {"spectralClass": "M", "planetCount": 1, "confirmedPlanets": 1, "factionType": "许可/矿业"},
    "vega": {"spectralClass": "A", "planetCount": 0, "confirmedPlanets": 0, "objectType": "star_system", "factionType": "外环采掘", "displayUntil": None},
    "gj887": {"spectralClass": "M", "planetCount": 4, "confirmedPlanets": 3, "candidatePlanets": 1, "factionType": "材料/冶金"},
    "fomalhaut": {"spectralClass": "A", "planetCount": 0, "confirmedPlanets": 0, "factionType": "外环采掘"},
    "ross128": {"spectralClass": "M", "planetCount": 1, "confirmedPlanets": 1, "factionType": "生态城邦"},
    "gj667c": {"spectralClass": "K/M", "starCount": 3, "planetCount": 5, "confirmedPlanets": 2, "candidatePlanets": 3, "factionType": "边境开发"},
    "epsilon-indi": {"spectralClass": "K/T", "starCount": 3, "planetCount": 1, "confirmedPlanets": 1, "factionType": "燃料/科研"},
    "gj682": {"spectralClass": "M", "planetCount": 2, "confirmedPlanets": 0, "candidatePlanets": 2, "factionType": "边境开发"},
    "beta-hydri": {"spectralClass": "G", "planetCount": 0, "confirmedPlanets": 0, "factionType": "外环科研"},
    "uv-ceti": {"spectralClass": "M", "starCount": 2, "planetCount": 1, "candidatePlanets": 1, "factionType": "保险/科研争议区"},
    "groombridge34": {"spectralClass": "M", "starCount": 2, "planetCount": 2, "confirmedPlanets": 2, "factionType": "金融数据"},
    "tau-ceti": {
        "spectralClass": "G",
        "planetCount": 4,
        "confirmedPlanets": 4,
        "candidatePlanets": 4,
        "factionType": "生态/医药",
        "age": "约 58 亿年",
        "lifespan": "G8.5V 主序寿命约 120-140 亿年。",
        "disasters": "相对安静但碎屑盘尘埃丰度偏高，长期航道需要微陨石防护。",
        "hz_inner": 0.55,
        "hz_outer": 1.16,
        "rule_info_time": 0.22,
        "info_speed": 1.0,
        "ftl_speed": 1.0,
    },
    "teegarden": {
        "spectralClass": "M",
        "planetCount": 3,
        "confirmedPlanets": 3,
        "factionType": "生态/医药",
        "age": "约 80 亿年以上",
        "lifespan": "低质量 M 型红矮星，主序寿命可达数千亿年量级。",
        "disasters": "近轨宜居带潮汐锁定、恒星风与红矮星耀斑风险；老年低活动期利于生态工程。",
        "hz_inner": 0.025,
        "hz_outer": 0.05,
        "rule_info_time": 0.18,
        "info_speed": 1.0,
        "ftl_speed": 1.0,
    },
    "gj1002": {
        "spectralClass": "M",
        "planetCount": 2,
        "confirmedPlanets": 2,
        "factionType": "新路线生态",
        "age": "成熟红矮星；现实资料强调活动较低但未给出统一精确年龄。",
        "lifespan": "M5.5V 红矮星，主序寿命远超太阳，可达数千亿年量级。",
        "disasters": "红矮星宜居带近轨潮汐锁定；年轻期耀斑/紫外风险高，成熟期相对安静。",
        "hz_inner": 0.045,
        "hz_outer": 0.075,
        "rule_info_time": 0.18,
        "info_speed": 1.0,
        "ftl_speed": 1.0,
    },
    "hd219134": {
        "spectralClass": "K",
        "planetCount": 6,
        "confirmedPlanets": 6,
        "factionType": "金融数据",
        "age": "约 110 亿年以上的老 K 型星",
        "lifespan": "K3V 主序寿命通常长于太阳，可达约 200-300 亿年量级。",
        "disasters": "近轨热岩石行星受强辐照；老年 K 型主星整体活动较温和。",
        "hz_inner": 0.40,
        "hz_outer": 0.75,
        "rule_info_time": 0.24,
        "info_speed": 1.0,
        "ftl_speed": 1.0,
    },
    "107piscium": {"spectralClass": "K", "planetCount": 0, "confirmedPlanets": 0, "candidatePlanets": 1, "factionType": "金融许可"},
    "wolf359": {"spectralClass": "M", "planetCount": 1, "candidatePlanets": 1, "factionType": "封闭科技"},
    "lalande": {"spectralClass": "M", "planetCount": 2, "confirmedPlanets": 2, "factionType": "消费电子/封闭生态"},
    "gj273": {"spectralClass": "M", "planetCount": 4, "confirmedPlanets": 2, "candidatePlanets": 2, "factionType": "人口盘"},
    "gj251": {"spectralClass": "M", "planetCount": 1, "confirmedPlanets": 1, "factionType": "外围工厂"},
    "epsilon-eridani": {
        "spectralClass": "K",
        "planetCount": 1,
        "confirmedPlanets": 1,
        "candidatePlanets": 2,
        "factionType": "造船/债券",
        "age": "约 4-8 亿年，年轻 K 型星。",
        "lifespan": "K2V 主序寿命约 200 亿年量级。",
        "disasters": "年轻恒星活动强、恒星风和碎屑盘尘埃风险高；适合造船资源，不适合无防护殖民。",
        "hz_inner": 0.50,
        "hz_outer": 0.95,
        "rule_info_time": 0.20,
        "info_speed": 1.0,
        "ftl_speed": 1.0,
    },
    "gj1061": {"spectralClass": "M", "planetCount": 3, "confirmedPlanets": 3, "factionType": "群星生态"},
    "kapteyn": {"spectralClass": "M", "planetCount": 0, "candidatePlanets": 2, "factionType": "老殖民/军政"},
    "40eridani": {"spectralClass": "K/DA/M", "starCount": 3, "planetCount": 1, "candidatePlanets": 1, "factionType": "行政/科研"},
    "hd20794": {"spectralClass": "G", "planetCount": 3, "confirmedPlanets": 3, "candidatePlanets": 1, "factionType": "正统殖民"},
    "li-hartman": {
        "name": "_李-哈特曼_ / _Li-Hartman_",
        "short": "_Li-Hartman_",
        "spectralClass": "K",
        "planetCount": 8,
        "confirmedPlanets": 8,
        "factionType": "地方联营",
        "className": "_设定_ K3V",
        "planets": "_原野星_、_草原星_、_釉海星_、_匣_为主级宜居/准宜居；_阙穹_ 76 卫星。",
        "reality": "_架空锚点_，置于 HD 20794 与 LTT 1445 A 邻近外缘，坐标用于设定推演。",
        "setting": "_边境黄金压力锅_：远岭联营经营权，母星方保留法理和黄金股。",
        "age": "_设定_约 60 亿年，黑子少、耀斑罕见。",
        "lifespan": "_设定_K3V 橙矮星，主序寿命约 200-300 亿年；2350 年仍处稳定中年期。",
        "disasters": "_设定_低耀斑但宜居带紧凑，多行星交通拥挤；小行星带、海盗和地球化设备故障是主要灾害。",
        "hz_inner": 0.36,
        "hz_outer": 0.62,
        "rule_info_time": 0.35,
        "info_speed": 1.0,
        "ftl_speed": 1.0,
    },
    "ltt1445": {"spectralClass": "M", "starCount": 3, "planetCount": 3, "confirmedPlanets": 3, "candidatePlanets": 1, "factionType": "科研许可"},
}


EXTRA_STARS = [
    {
        "id": "luhman16",
        "name": "Luhman 16 / WISE 1049-5319",
        "short": "Luhman 16",
        "octant": "+-+",
        "order": 1.1,
        "distance": 6.51,
        "arrival": 2284.51,
        "xyz": [1.7, -6.3, 0.6],
        "faction": "自然天体/科研区",
        "rank": "-",
        "className": "L/T 褐矮星双星",
        "planets": "0 宜居；褐矮星天气、磁层与冷资源观测价值高。",
        "reality": "太阳近邻褐矮星双星，位于 25 光年内，无已知宜居行星。",
        "setting": "近太阳深空导航与低温传感器校准站，商业价值低但科研和军用被动探测价值高。",
        "habitable": 0,
        "status": "minor",
        "objectType": "brown_dwarf",
        "spectralClass": "L/T",
        "starCount": 2,
        "planetCount": 0,
        "confirmedPlanets": 0,
        "candidatePlanets": 0,
        "factionType": "自然/科研",
    },
    {
        "id": "wise0855",
        "name": "WISE 0855-0714",
        "short": "WISE 0855",
        "octant": "--+",
        "order": 0.5,
        "distance": 7.43,
        "arrival": 2285.43,
        "xyz": [-3.9, -5.6, 2.9],
        "faction": "自然天体/科研区",
        "rank": "-",
        "className": "Y 型亚褐矮星",
        "planets": "0 宜居；极低温亚恒星天体。",
        "reality": "太阳近邻亚褐矮星/行星质量天体，无行星系统确认。",
        "setting": "无限未来走廊旁的冷暗导航盲点，适合监听、隐蔽仓和无人探针剧情。",
        "habitable": 0,
        "status": "minor",
        "objectType": "substellar_object",
        "spectralClass": "Y",
        "starCount": 1,
        "planetCount": 0,
        "confirmedPlanets": 0,
        "candidatePlanets": 0,
        "factionType": "自然/科研",
    },
    {
        "id": "sirius",
        "name": "Sirius / 天狼星",
        "short": "Sirius",
        "octant": "---",
        "order": 0.5,
        "distance": 8.60,
        "arrival": 2286.60,
        "xyz": [-5.8, -6.2, -1.3],
        "faction": "自然天体/科研区",
        "rank": "-",
        "className": "A1V + DA 白矮星",
        "planets": "0 宜居；强光主星与白矮星伴星，适合光学、材料和白矮星科研。",
        "reality": "著名近邻双星，无确认行星。",
        "setting": "太阳周边最醒目的灯塔星，2350 年更像航标和高能材料科研节点，不给强巨企本土。",
        "habitable": 0,
        "status": "minor",
        "objectType": "star_system",
        "spectralClass": "A/DA",
        "starCount": 2,
        "planetCount": 0,
        "confirmedPlanets": 0,
        "candidatePlanets": 0,
        "factionType": "自然/科研",
    },
    {
        "id": "ez-aqr",
        "name": "EZ Aquarii",
        "short": "EZ Aqr",
        "octant": "-+-",
        "order": 0.8,
        "distance": 11.27,
        "arrival": 2289.27,
        "xyz": [-2.8, 0.8, -10.9],
        "faction": "自然天体/科研区",
        "rank": "-",
        "className": "M 型三合星",
        "planets": "0 宜居；紧密红矮星三体动力学复杂。",
        "reality": "近邻红矮星三合星，无稳健行星确认。",
        "setting": "位于美丽花园/S&F 走廊旁，适合做三体导航实验和早期失败殖民保险标的。",
        "habitable": 0,
        "status": "minor",
        "objectType": "star_system",
        "spectralClass": "M",
        "starCount": 3,
        "planetCount": 0,
        "confirmedPlanets": 0,
        "candidatePlanets": 0,
        "factionType": "自然/科研",
    },
    {
        "id": "61cyg",
        "name": "61 Cygni",
        "short": "61 Cyg",
        "octant": "++-",
        "order": 1.5,
        "distance": 11.40,
        "arrival": 2289.40,
        "xyz": [1.5, 11.2, -1.2],
        "faction": "自然天体/科研区",
        "rank": "-",
        "className": "K5V + K7V",
        "planets": "0 宜居确认；K 型双星，长期稳定观测价值高。",
        "reality": "近邻 K 型双星，无确认宜居行星。",
        "setting": "拉卡伊冶金与外环航线之间的老牌航标和测距基准。",
        "habitable": 0,
        "status": "minor",
        "objectType": "star_system",
        "spectralClass": "K",
        "starCount": 2,
        "planetCount": 0,
        "confirmedPlanets": 0,
        "candidatePlanets": 0,
        "factionType": "自然/科研",
    },
    {
        "id": "procyon",
        "name": "Procyon / 南河三",
        "short": "Procyon",
        "octant": "--+",
        "order": 0.7,
        "distance": 11.46,
        "arrival": 2289.46,
        "xyz": [-9.3, -6.2, 2.6],
        "faction": "自然天体/科研区",
        "rank": "-",
        "className": "F5IV-V + DQZ 白矮星",
        "planets": "0 宜居；亚巨星演化与白矮星伴星使长期殖民吸引力有限。",
        "reality": "近邻双星，无确认行星。",
        "setting": "无限未来外侧的高亮航标，商业叙事以观测、光帆测试和白矮星材料为主。",
        "habitable": 0,
        "status": "minor",
        "objectType": "star_system",
        "spectralClass": "F/D",
        "starCount": 2,
        "planetCount": 0,
        "confirmedPlanets": 0,
        "candidatePlanets": 0,
        "factionType": "自然/科研",
    },
    {
        "id": "struve2398",
        "name": "Struve 2398 / Gliese 725",
        "short": "Struve 2398",
        "octant": "+++",
        "order": 1.4,
        "distance": 11.52,
        "arrival": 2289.52,
        "xyz": [0.2, 10.3, 5.2],
        "faction": "自然天体/科研区",
        "rank": "-",
        "className": "M3V + M3.5V",
        "planets": "0 宜居确认；双红矮星冷工业站潜力。",
        "reality": "近邻红矮星双星，无确认行星。",
        "setting": "+++ 空洞中的维修、监听和机器人补给点，避免破坏沃尔夫/Barnard 的核心势力连续性。",
        "habitable": 0,
        "status": "minor",
        "objectType": "star_system",
        "spectralClass": "M",
        "starCount": 2,
        "planetCount": 0,
        "confirmedPlanets": 0,
        "candidatePlanets": 0,
        "factionType": "自然/科研",
    },
    {
        "id": "dx-cancri",
        "name": "DX Cancri",
        "short": "DX Cnc",
        "octant": "--+",
        "order": 2.5,
        "distance": 11.82,
        "arrival": 2289.82,
        "xyz": [-9.3, -3.0, 6.7],
        "faction": "自然天体/科研区",
        "rank": "-",
        "className": "M6V",
        "planets": "0 宜居确认；低质量红矮星。",
        "reality": "近邻红矮星，无确认行星。",
        "setting": "无限未来走廊里的廉价中继与无人仓储点。",
        "habitable": 0,
        "status": "minor",
        "objectType": "star_system",
        "spectralClass": "M",
        "starCount": 1,
        "planetCount": 0,
        "confirmedPlanets": 0,
        "candidatePlanets": 0,
        "factionType": "自然/科研",
    },
    {
        "id": "yz-ceti",
        "name": "YZ Ceti",
        "short": "YZ Ceti",
        "octant": "-+-",
        "order": 2.6,
        "distance": 12.11,
        "arrival": 2290.11,
        "xyz": [-2.1, 1.2, -11.9],
        "faction": "自然天体/科研区",
        "rank": "-",
        "className": "M4.5V",
        "planets": "3 近轨岩石行星；0 宜居。",
        "reality": "已知多颗近轨行星，整体偏热。",
        "setting": "Tau Ceti 附近的热岩石资源与磁层实验场，常被美丽花园包装成生态技术副项目。",
        "habitable": 0,
        "status": "minor",
        "objectType": "star_system",
        "spectralClass": "M",
        "starCount": 1,
        "planetCount": 3,
        "confirmedPlanets": 3,
        "candidatePlanets": 0,
        "factionType": "自然/科研",
    },
    {
        "id": "scr1845",
        "name": "SCR 1845-6357",
        "short": "SCR 1845",
        "octant": "+--",
        "order": 2.5,
        "distance": 13.05,
        "arrival": 2291.05,
        "xyz": [10.5, -5.7, -5.2],
        "faction": "自然天体/科研区",
        "rank": "-",
        "className": "M8.5V + T6",
        "planets": "0 宜居；超冷红矮星与褐矮星伴星。",
        "reality": "近邻低温双体系统，无确认行星。",
        "setting": "近邻三角外围的冷暗科研节点，可作为隐蔽航线标记。",
        "habitable": 0,
        "status": "minor",
        "objectType": "brown_dwarf",
        "spectralClass": "M/T",
        "starCount": 2,
        "planetCount": 0,
        "confirmedPlanets": 0,
        "candidatePlanets": 0,
        "factionType": "自然/科研",
    },
    {
        "id": "denis1048",
        "name": "DENIS 1048-3956",
        "short": "DENIS 1048",
        "octant": "+-+",
        "order": 1.4,
        "distance": 13.17,
        "arrival": 2291.17,
        "xyz": [1.9, -12.4, 3.9],
        "faction": "自然天体/科研区",
        "rank": "-",
        "className": "M8.5V",
        "planets": "0 宜居；超冷红矮星。",
        "reality": "太阳近邻低质量恒星，无确认行星。",
        "setting": "Ross 128 外侧的冷暗补给点，生态城邦与科研站共同使用。",
        "habitable": 0,
        "status": "minor",
        "objectType": "star_system",
        "spectralClass": "M",
        "starCount": 1,
        "planetCount": 0,
        "confirmedPlanets": 0,
        "candidatePlanets": 0,
        "factionType": "自然/科研",
    },
    {
        "id": "kruger60",
        "name": "Kruger 60",
        "short": "Kruger 60",
        "octant": "-+-",
        "order": 2.8,
        "distance": 13.15,
        "arrival": 2291.15,
        "xyz": [-3.3, 12.7, 0.0],
        "faction": "自然天体/科研区",
        "rank": "-",
        "className": "M3V + M4V",
        "planets": "0 宜居确认；红矮星双星。",
        "reality": "近邻双红矮星，无确认行星。",
        "setting": "S&F 数据走廊边缘的低价中继和冷备份点。",
        "habitable": 0,
        "status": "minor",
        "objectType": "star_system",
        "spectralClass": "M",
        "starCount": 2,
        "planetCount": 0,
        "confirmedPlanets": 0,
        "candidatePlanets": 0,
        "factionType": "自然/科研",
    },
    {
        "id": "van-maanen",
        "name": "Van Maanen 2",
        "short": "Van Maanen",
        "octant": "-+-",
        "order": 3.2,
        "distance": 14.07,
        "arrival": 2292.07,
        "xyz": [-4.0, 6.4, -11.9],
        "faction": "白矮星科研封存区",
        "rank": "-",
        "className": "DZ 白矮星",
        "planets": "0 宜居；白矮星碎屑污染与行星遗骸研究。",
        "reality": "近邻孤立白矮星，无确认现存宜居行星。",
        "setting": "S&F 与美丽花园都采购过的白矮星法证科研点，常用于判断古老行星碎片成分。",
        "habitable": 0,
        "status": "minor",
        "objectType": "white_dwarf",
        "spectralClass": "DZ",
        "starCount": 1,
        "planetCount": 0,
        "confirmedPlanets": 0,
        "candidatePlanets": 0,
        "factionType": "白矮星科研",
    },
    {
        "id": "gliese1",
        "name": "Gliese 1",
        "short": "Gliese 1",
        "octant": "+--",
        "order": 3.5,
        "distance": 14.17,
        "arrival": 2292.17,
        "xyz": [3.3, -1.0, -13.7],
        "faction": "自然天体/科研区",
        "rank": "-",
        "className": "M1.5V",
        "planets": "0 宜居确认；近邻红矮星。",
        "reality": "近邻红矮星，无确认行星。",
        "setting": "近邻三角与南方群星之间的中性导航点。",
        "habitable": 0,
        "status": "minor",
        "objectType": "star_system",
        "spectralClass": "M",
        "starCount": 1,
        "planetCount": 0,
        "confirmedPlanets": 0,
        "candidatePlanets": 0,
        "factionType": "自然/科研",
    },
    {
        "id": "wolf424",
        "name": "Wolf 424 / FL Virginis",
        "short": "Wolf 424",
        "octant": "+-+",
        "order": 1.6,
        "distance": 14.32,
        "arrival": 2292.32,
        "xyz": [0.9, -4.6, 13.5],
        "faction": "自然天体/科研区",
        "rank": "-",
        "className": "M dwarf binary",
        "planets": "0 宜居确认；双红矮星。",
        "reality": "近邻红矮星双星，无确认宜居行星。",
        "setting": "Ross 128 上方的高纬监听点，适合生态城邦防务预警。",
        "habitable": 0,
        "status": "minor",
        "objectType": "star_system",
        "spectralClass": "M",
        "starCount": 2,
        "planetCount": 0,
        "confirmedPlanets": 0,
        "candidatePlanets": 0,
        "factionType": "自然/科研",
    },
    {
        "id": "gj674",
        "name": "GJ 674",
        "short": "GJ 674",
        "octant": "+--",
        "order": 4.2,
        "distance": 14.84,
        "arrival": 2292.84,
        "xyz": [14.1, -4.3, -1.8],
        "faction": "自然天体/科研区",
        "rank": "-",
        "className": "M2.5V",
        "planets": "1 近轨类海王星；0 宜居。",
        "reality": "已知一颗短周期行星，非宜居。",
        "setting": "南爪边境前哨旁的行星形成与潮汐工程训练地。",
        "habitable": 0,
        "status": "minor",
        "objectType": "star_system",
        "spectralClass": "M",
        "starCount": 1,
        "planetCount": 1,
        "confirmedPlanets": 1,
        "candidatePlanets": 0,
        "factionType": "自然/科研",
    },
    {
        "id": "gj876",
        "name": "Gliese 876",
        "short": "GJ 876",
        "octant": "++-",
        "order": 1.8,
        "distance": 15.20,
        "arrival": 2293.20,
        "xyz": [4.7, 6.1, -13.1],
        "faction": "自然天体/科研区",
        "rank": "-",
        "className": "M4V",
        "planets": "4 确认行星；共振巨行星系统，0 稳健宜居。",
        "reality": "著名多行星红矮星系统，存在强轨道共振。",
        "setting": "拉卡伊冶金公会常用的轨道动力学靶场和船坞模拟数据源。",
        "habitable": 0,
        "status": "minor",
        "objectType": "star_system",
        "spectralClass": "M",
        "starCount": 1,
        "planetCount": 4,
        "confirmedPlanets": 4,
        "candidatePlanets": 0,
        "factionType": "自然/科研",
    },
    {
        "id": "ad-leonis",
        "name": "AD Leonis / Gliese 388",
        "short": "AD Leo",
        "octant": "--+",
        "order": 4.5,
        "distance": 16.19,
        "arrival": 2294.19,
        "xyz": [-7.5, -5.6, 13.2],
        "faction": "自然天体/科研区",
        "rank": "-",
        "className": "M3.5V 耀星",
        "planets": "0 宜居确认；耀发极强。",
        "reality": "著名活跃红矮星，无确认宜居行星。",
        "setting": "无限未来外围的防辐射材料和脑机抗干扰测试场。",
        "habitable": 0,
        "status": "minor",
        "objectType": "star_system",
        "spectralClass": "M",
        "starCount": 1,
        "planetCount": 0,
        "confirmedPlanets": 0,
        "candidatePlanets": 0,
        "factionType": "自然/科研",
    },
    {
        "id": "70oph",
        "name": "70 Ophiuchi",
        "short": "70 Oph",
        "octant": "+++",
        "order": 2.7,
        "distance": 16.64,
        "arrival": 2294.64,
        "xyz": [14.1, 8.1, 3.3],
        "faction": "自然天体/科研区",
        "rank": "-",
        "className": "K0V + K5V",
        "planets": "0 宜居确认；近邻 K 型双星。",
        "reality": "近邻双星，无稳健行星确认。",
        "setting": "+++ 方向的大型光学基准站，服务沃尔夫和巴纳德外围航线。",
        "habitable": 0,
        "status": "minor",
        "objectType": "star_system",
        "spectralClass": "K",
        "starCount": 2,
        "planetCount": 0,
        "confirmedPlanets": 0,
        "candidatePlanets": 0,
        "factionType": "自然/科研",
    },
    {
        "id": "altair",
        "name": "Altair / 河鼓二",
        "short": "Altair",
        "octant": "++-",
        "order": 3.4,
        "distance": 16.73,
        "arrival": 2294.73,
        "xyz": [11.1, 12.2, -2.6],
        "faction": "自然天体/科研区",
        "rank": "-",
        "className": "A7V",
        "planets": "0 宜居确认；高速自转亮星。",
        "reality": "明亮近邻 A 型星，无确认行星。",
        "setting": "外环宣传航线上的可见灯塔，商业价值偏文化和光学基准。",
        "habitable": 0,
        "status": "minor",
        "objectType": "star_system",
        "spectralClass": "A",
        "starCount": 1,
        "planetCount": 0,
        "confirmedPlanets": 0,
        "candidatePlanets": 0,
        "factionType": "自然/科研",
    },
    {
        "id": "stein2051",
        "name": "Stein 2051",
        "short": "Stein 2051",
        "octant": "-++",
        "order": 1,
        "distance": 18.06,
        "arrival": 2296.06,
        "xyz": [-15.3, 9.2, 2.6],
        "faction": "白矮星科研封存区",
        "rank": "-",
        "className": "M4V + DC 白矮星",
        "planets": "0 宜居；红矮星与白矮星双星。",
        "reality": "近邻双星，无确认行星。",
        "setting": "-++ 空洞区的科研封存点，可放自动舰隐藏节点但不放强巨企本土。",
        "habitable": 0,
        "status": "minor",
        "objectType": "white_dwarf",
        "spectralClass": "M/DC",
        "starCount": 2,
        "planetCount": 0,
        "confirmedPlanets": 0,
        "candidatePlanets": 0,
        "factionType": "白矮星科研",
    },
    {
        "id": "sigma-dra",
        "name": "Sigma Draconis",
        "short": "Sigma Dra",
        "octant": "-++",
        "order": 2,
        "distance": 18.77,
        "arrival": 2296.77,
        "xyz": [-3.4, 17.1, 7.0],
        "faction": "自然天体/科研区",
        "rank": "-",
        "className": "K0V",
        "planets": "0 宜居确认；稳定 K 型星。",
        "reality": "近邻 K 型星，无确认行星。",
        "setting": "-++ 象限的稳定恒星基准，保留为空洞区中继。",
        "habitable": 0,
        "status": "minor",
        "objectType": "star_system",
        "spectralClass": "K",
        "starCount": 1,
        "planetCount": 0,
        "confirmedPlanets": 0,
        "candidatePlanets": 0,
        "factionType": "自然/科研",
    },
    {
        "id": "gliese229",
        "name": "Gliese 229",
        "short": "GJ 229",
        "octant": "---",
        "order": 0.8,
        "distance": 18.80,
        "arrival": 2296.80,
        "xyz": [-11.8, -13.4, -5.9],
        "faction": "自然天体/科研区",
        "rank": "-",
        "className": "M1V + T 褐矮星",
        "planets": "0 宜居；褐矮星伴星科研价值高。",
        "reality": "著名红矮星 + 褐矮星伴星系统。",
        "setting": "人类群星联合南方走廊外侧的冷天体实验室。",
        "habitable": 0,
        "status": "minor",
        "objectType": "brown_dwarf",
        "spectralClass": "M/T",
        "starCount": 2,
        "planetCount": 0,
        "confirmedPlanets": 0,
        "candidatePlanets": 0,
        "factionType": "自然/科研",
    },
    {
        "id": "gliese570",
        "name": "Gliese 570",
        "short": "GJ 570",
        "octant": "+-+",
        "order": 1.9,
        "distance": 19.00,
        "arrival": 2297.00,
        "xyz": [14.1, -6.8, 10.8],
        "faction": "自然天体/科研区",
        "rank": "-",
        "className": "K4V + M + T 褐矮星",
        "planets": "0 宜居确认；多星与褐矮星伴星。",
        "reality": "近邻多星系统，含 T 型褐矮星。",
        "setting": "Ross 128 与南爪边境之间的复杂多星导航训练点。",
        "habitable": 0,
        "status": "minor",
        "objectType": "brown_dwarf",
        "spectralClass": "K/M/T",
        "starCount": 4,
        "planetCount": 0,
        "confirmedPlanets": 0,
        "candidatePlanets": 0,
        "factionType": "自然/科研",
    },
    {
        "id": "v1216sgr",
        "name": "V1216 Sagittarii / GJ 729",
        "short": "V1216 Sgr",
        "octant": "++-",
        "order": 3.8,
        "distance": 19.20,
        "arrival": 2297.20,
        "xyz": [18.5, 3.7, -3.4],
        "faction": "自然天体/科研区",
        "rank": "-",
        "className": "M3.5V 耀星",
        "planets": "0 宜居确认；活跃红矮星。",
        "reality": "近邻耀星，无确认行星。",
        "setting": "外环航路中的耀发预警与防护材料测试点。",
        "habitable": 0,
        "status": "minor",
        "objectType": "star_system",
        "spectralClass": "M",
        "starCount": 1,
        "planetCount": 0,
        "confirmedPlanets": 0,
        "candidatePlanets": 0,
        "factionType": "自然/科研",
    },
    {
        "id": "eta-cas",
        "name": "Eta Cassiopeiae",
        "short": "Eta Cas",
        "octant": "-+-",
        "order": 3.9,
        "distance": 19.42,
        "arrival": 2297.42,
        "xyz": [-10.4, 16.3, -1.7],
        "faction": "自然天体/科研区",
        "rank": "-",
        "className": "G0V + K7V",
        "planets": "0 宜居确认；太阳型双星。",
        "reality": "近邻 G/K 双星，无确认行星。",
        "setting": "S&F 北侧的老牌航标和光谱标定站。",
        "habitable": 0,
        "status": "minor",
        "objectType": "star_system",
        "spectralClass": "G/K",
        "starCount": 2,
        "planetCount": 0,
        "confirmedPlanets": 0,
        "candidatePlanets": 0,
        "factionType": "自然/科研",
    },
    {
        "id": "36oph",
        "name": "36 Ophiuchi",
        "short": "36 Oph",
        "octant": "+-+",
        "order": 2.1,
        "distance": 19.50,
        "arrival": 2297.50,
        "xyz": [19.4, -0.6, 2.3],
        "faction": "自然天体/科研区",
        "rank": "-",
        "className": "K dwarf triple",
        "planets": "0 宜居确认；K 型三合星。",
        "reality": "近邻 K 型多星系统。",
        "setting": "南爪边境与 Ross 128 方向之间的多星稳定性研究点。",
        "habitable": 0,
        "status": "minor",
        "objectType": "star_system",
        "spectralClass": "K",
        "starCount": 3,
        "planetCount": 0,
        "confirmedPlanets": 0,
        "candidatePlanets": 0,
        "factionType": "自然/科研",
    },
    {
        "id": "delta-pav",
        "name": "Delta Pavonis",
        "short": "Delta Pav",
        "octant": "+--",
        "order": 4.5,
        "distance": 19.92,
        "arrival": 2297.92,
        "xyz": [14.5, -8.5, -10.7],
        "faction": "自然天体/科研区",
        "rank": "-",
        "className": "G8IV",
        "planets": "0 宜居确认；老化类太阳星。",
        "reality": "近邻类太阳亚巨星，无确认行星。",
        "setting": "南方外环的恒星演化与撤离工程案例库。",
        "habitable": 0,
        "status": "minor",
        "objectType": "star_system",
        "spectralClass": "G",
        "starCount": 1,
        "planetCount": 0,
        "confirmedPlanets": 0,
        "candidatePlanets": 0,
        "factionType": "自然/科研",
    },
    {
        "id": "eq-peg",
        "name": "EQ Pegasi",
        "short": "EQ Peg",
        "octant": "-+-",
        "order": 4.2,
        "distance": 20.43,
        "arrival": 2298.43,
        "xyz": [-2.4, 15.7, -12.9],
        "faction": "自然天体/科研区",
        "rank": "-",
        "className": "M dwarf binary",
        "planets": "0 宜居确认；活跃红矮星双星。",
        "reality": "近邻红矮星双星，无确认行星。",
        "setting": "S&F 与 GJ1002 之间的危险耀发中继点。",
        "habitable": 0,
        "status": "minor",
        "objectType": "star_system",
        "spectralClass": "M",
        "starCount": 2,
        "planetCount": 0,
        "confirmedPlanets": 0,
        "candidatePlanets": 0,
        "factionType": "自然/科研",
    },
    {
        "id": "gliese581",
        "name": "Gliese 581",
        "short": "GJ 581",
        "octant": "+-+",
        "order": 2.2,
        "distance": 20.55,
        "arrival": 2298.55,
        "xyz": [15.7, -1.6, 13.2],
        "faction": "许可/争议区",
        "rank": "-",
        "className": "M3V",
        "planets": "3 确认行星；早年宜居宣传争议大，2350 设为失败生物圈和清算区。",
        "reality": "历史上多宜居候选争议，后续许多候选被削弱或否定。",
        "setting": "美丽花园旧时代投机项目失败后，被 S&F 清算并改为医学与生态法证试验区。",
        "habitable": 0,
        "status": "license",
        "objectType": "star_system",
        "spectralClass": "M",
        "starCount": 1,
        "planetCount": 3,
        "confirmedPlanets": 3,
        "candidatePlanets": 0,
        "factionType": "争议/清算",
    },
    {
        "id": "xi-bootis",
        "name": "Xi Bootis",
        "short": "Xi Boo",
        "octant": "+++",
        "order": 4.5,
        "distance": 21.80,
        "arrival": 2299.80,
        "xyz": [9.6, 4.1, 19.1],
        "faction": "自然天体/科研区",
        "rank": "-",
        "className": "G8V + K4V",
        "planets": "0 宜居确认；G/K 双星。",
        "reality": "近邻双星，无确认行星。",
        "setting": "+++ 高纬的观测基准站，避免设为强巨企本土。",
        "habitable": 0,
        "status": "minor",
        "objectType": "star_system",
        "spectralClass": "G/K",
        "starCount": 2,
        "planetCount": 0,
        "confirmedPlanets": 0,
        "candidatePlanets": 0,
        "factionType": "自然/科研",
    },
    {
        "id": "gliese832",
        "name": "Gliese 832",
        "short": "GJ 832",
        "octant": "+--",
        "order": 2.8,
        "distance": 16.20,
        "arrival": 2294.20,
        "xyz": [11.0, -2.1, -11.7],
        "faction": "自然天体/科研区",
        "rank": "-",
        "className": "M1.5V",
        "planets": "1 巨行星确认；旧宜居候选后续被削弱。",
        "reality": "已知巨行星系统，曾有宜居候选争议。",
        "setting": "Epsilon Indi 到 GJ 682 之间的冷冻物流与燃料带。",
        "habitable": 0,
        "status": "minor",
        "objectType": "star_system",
        "spectralClass": "M",
        "starCount": 1,
        "planetCount": 1,
        "confirmedPlanets": 1,
        "candidatePlanets": 0,
        "factionType": "自然/科研",
    },
    {
        "id": "local-cloud",
        "name": "Local Interstellar Cloud / 本地星际云",
        "short": "本地星际云",
        "octant": "原点",
        "order": 0.2,
        "distance": 0.0,
        "arrival": 2278.0,
        "xyz": [0.0, 0.0, 0.0],
        "faction": "本地星际介质",
        "rank": "-",
        "className": "稀薄星际云",
        "planets": "非恒星系；局部星际介质，影响尘埃、粒子与通信噪声。",
        "reality": "太阳目前位于或接近本地星际云区域。",
        "setting": "作为太阳周边介质层显示，提醒星际航行并非真空白板。",
        "habitable": 0,
        "status": "cloud",
        "objectType": "diffuse_cloud",
        "spectralClass": "ISM",
        "starCount": 0,
        "planetCount": 0,
        "confirmedPlanets": 0,
        "candidatePlanets": 0,
        "factionType": "星际介质",
    },
    {
        "id": "g-cloud",
        "name": "G Cloud / G 云",
        "short": "G 云",
        "octant": "+-+",
        "order": 0.3,
        "distance": 5.0,
        "arrival": 2283.0,
        "xyz": [4.5, -0.6, 2.1],
        "faction": "本地星际介质",
        "rank": "-",
        "className": "稀薄星际云",
        "planets": "非恒星系；局部星际介质结构。",
        "reality": "太阳附近的星际云候选结构之一。",
        "setting": "近邻三角与 Ross 128 方向之间的尘埃/等离子体环境提示层。",
        "habitable": 0,
        "status": "cloud",
        "objectType": "diffuse_cloud",
        "spectralClass": "ISM",
        "starCount": 0,
        "planetCount": 0,
        "confirmedPlanets": 0,
        "candidatePlanets": 0,
        "factionType": "星际介质",
    },
]


SYSTEM_BODY_SEEDS = {
    "sol": [
        {"id": "sol-star", "name": "太阳", "bodyType": "star", "orbitAu": 0.0, "radiusLabel": "G2V；46 亿年", "summary": "人类母星系主星；主序期约 100 亿年，约 50 亿年后进入红巨星阶段。", "sortOrder": 0, "rule_info_time": 0.30},
        {"id": "mercury", "name": "水星", "bodyType": "planet", "orbitAu": 0.39, "radiusLabel": "岩石行星", "massLabel": "0.055 M⊕", "summary": "内侧高温岩石行星；现实平均轨道距离约 0.39 AU。", "sortOrder": 10},
        {"id": "venus", "name": "金星", "bodyType": "planet", "orbitAu": 0.72, "radiusLabel": "岩石行星", "massLabel": "0.815 M⊕", "summary": "高温浓厚大气世界；现实平均轨道距离约 0.72 AU。", "sortOrder": 20},
        {"id": "earth", "name": "地球", "bodyType": "planet", "orbitAu": 1.0, "radiusLabel": "类地行星", "massLabel": "1.0 M⊕", "habitable": 1, "summary": "人类母星；现实平均轨道距离 1 AU。", "sortOrder": 30, "rule_info_time": 0.18},
        {"id": "moon", "parentId": "earth", "name": "月球", "bodyType": "moon", "orbitAu": 1.00257, "radiusLabel": "地球卫星", "massLabel": "0.0123 M⊕；距地约 384,000 km", "summary": "地球卫星与早期深空工业基地；轨道距离折算约 0.00257 AU。", "sortOrder": 31, "rule_info_time": 0.08},
        {"id": "mars", "name": "火星", "bodyType": "planet", "orbitAu": 1.52, "radiusLabel": "岩石行星", "massLabel": "0.107 M⊕", "summary": "早期殖民与内战重要节点；现实平均轨道距离约 1.52 AU。", "sortOrder": 40},
        {"id": "asteroid-belt", "name": "主小行星带", "bodyType": "belt", "orbitAu": 2.80, "radiusLabel": "小行星带", "summary": "火星与木星之间的金属、水冰和小天体资源带。", "sortOrder": 50},
        {"id": "jupiter", "name": "木星", "bodyType": "planet", "orbitAu": 5.20, "radiusLabel": "气巨星", "massLabel": "317.8 M⊕", "summary": "外太阳系卫星群和深空工业重心；现实平均轨道距离约 5.20 AU。", "sortOrder": 60},
        {"id": "io", "parentId": "jupiter", "name": "木卫一 / Io", "bodyType": "moon", "orbitAu": 5.2028, "radiusLabel": "火山卫星", "summary": "强潮汐加热与火山活动卫星；木星近侧能源/地质实验节点。", "sortOrder": 61},
        {"id": "europa", "parentId": "jupiter", "name": "木卫二 / Europa", "bodyType": "moon", "orbitAu": 5.2045, "radiusLabel": "冰壳海洋卫星", "summary": "冰壳下海洋卫星；外太阳系生物与冰下工程研究重点。", "sortOrder": 62},
        {"id": "ganymede", "parentId": "jupiter", "name": "木卫三 / Ganymede", "bodyType": "moon", "orbitAu": 5.2072, "radiusLabel": "太阳系最大卫星", "summary": "太阳系最大卫星，距木星约 1,070,000 km；重要外太阳系工业节点。", "sortOrder": 63},
        {"id": "callisto", "parentId": "jupiter", "name": "木卫四 / Callisto", "bodyType": "moon", "orbitAu": 5.2126, "radiusLabel": "冰岩卫星", "summary": "辐射环境较温和的外侧大卫星，适合长期基地与补给。", "sortOrder": 64},
        {"id": "saturn", "name": "土星", "bodyType": "planet", "orbitAu": 9.58, "radiusLabel": "气巨星", "massLabel": "95.2 M⊕", "summary": "环系与卫星资源；现实平均轨道距离约 9.58 AU。", "sortOrder": 70},
        {"id": "titan", "parentId": "saturn", "name": "泰坦 / Titan", "bodyType": "moon", "orbitAu": 9.588, "radiusLabel": "厚大气大型卫星", "summary": "土星最大卫星，距土星约 1.2 百万 km；厚氮气大气与烃循环使其成为重要殖民/化工节点。", "sortOrder": 71, "rule_info_time": 0.07},
        {"id": "uranus", "name": "天王星", "bodyType": "planet", "orbitAu": 19.20, "radiusLabel": "冰巨星", "massLabel": "14.5 M⊕", "summary": "外太阳系冰巨星；现实平均轨道距离约 19.20 AU。", "sortOrder": 80},
        {"id": "neptune", "name": "海王星", "bodyType": "planet", "orbitAu": 30.05, "radiusLabel": "冰巨星", "massLabel": "17.1 M⊕", "summary": "外侧冰巨星；现实平均轨道距离约 30.05 AU。", "sortOrder": 90},
        {"id": "kuiper-belt", "name": "柯伊伯带", "bodyType": "belt", "orbitAu": 39.0, "radiusLabel": "冰小天体带", "summary": "外缘冰资源、远日点站群和长周期航道储备。", "sortOrder": 100},
    ],
    "alpha": [
        {"id": "alpha-a", "name": "Alpha Centauri A", "bodyType": "star", "orbitAu": 0.0, "radiusLabel": "G2V", "summary": "类太阳主星，旧太阳系军工反复争夺。", "sortOrder": 0},
        {"id": "alpha-b", "name": "Alpha Centauri B", "bodyType": "star", "orbitAu": 23.4, "radiusLabel": "K1V", "summary": "K 型伴星。", "sortOrder": 1},
        {"id": "proxima-star", "name": "Proxima Centauri", "bodyType": "star", "orbitAu": 13000.0, "radiusLabel": "M5.5Ve", "summary": "远距伴星。", "sortOrder": 2},
        {"id": "proxima-b", "parentId": "proxima-star", "name": "Proxima b", "bodyType": "planet", "orbitAu": 0.049, "radiusLabel": "岩石行星", "habitable": 1, "summary": "极端宜居带行星，耀斑与潮汐锁定风险高。", "sortOrder": 3},
        {"id": "alpha-ab-yard", "name": "_AB 船坞带_", "bodyType": "station", "orbitAu": 1.2, "radiusLabel": "轨道设施", "summary": "_设定_近邻军工托管区的核心船坞与试验场。", "sortOrder": 4},
    ],
    "li-hartman": [
        {"id": "li-star", "name": "_李-哈特曼_主星", "bodyType": "star", "orbitAu": 0.0, "radiusLabel": "K3V；0.74 M☉；0.21 L☉", "summary": "_设定_ 60 亿年橙矮星，黑子少、耀斑罕见，宜居带 0.36-0.62 AU。", "sortOrder": 0, "rule_info_time": 0.35},
        {"id": "wihiga", "name": "_炽页_ / _Vihiga_", "bodyType": "planet", "orbitAu": 0.18, "radiusLabel": "水星级岩石行星", "summary": "_设定_水星类潮汐锁定热岩石球，反射镜阵与无人采能站。", "sortOrder": 10},
        {"id": "pa-caoyuan", "name": "_草原星_ / _Pa-Caoyuan_", "bodyType": "planet", "orbitAu": 0.42, "radiusLabel": "半地球化类地；0.93 M⊕；1.04 g", "habitable": 1, "summary": "_设定_地球化未完工约 78%，全星约 52 万人，本作主舞台。", "sortOrder": 20, "rule_info_time": 0.16},
        {"id": "caoyuan-suo", "parentId": "pa-caoyuan", "name": "_朔_ / _Suo_", "bodyType": "moon", "orbitAu": 0.422, "radiusLabel": "草原星小卫星", "summary": "_设定_朔顶穹顶城与草原星通勤居住点所在，夜空常呈细弧朔相。", "sortOrder": 21, "rule_info_time": 0.06},
        {"id": "yuan-ye", "name": "_原野星_ / _Yuanye_", "bodyType": "planet", "orbitAu": 0.50, "radiusLabel": "天然类地；第一宜居", "habitable": 1, "summary": "_设定_天生类地，主居住地，约 3050 万人口，多个本地国家。", "sortOrder": 30, "rule_info_time": 0.20},
        {"id": "glaze", "name": "_釉海星_ / _Glaze_", "bodyType": "planet", "orbitAu": 0.58, "radiusLabel": "厚大气浮空文明", "habitable": 1, "summary": "_设定_第二大居住地，约 1200 万浮空城市民，厚云海和 50-60 km 浮空带。", "sortOrder": 40, "rule_info_time": 0.16},
        {"id": "glaze-hu", "parentId": "glaze", "name": "_瑚_ / _Hu_", "bodyType": "moon", "orbitAu": 0.582, "radiusLabel": "釉海星可改造卫星", "habitable": 1, "summary": "_设定_釉海星卫星，穹顶与部分裸露地球化工程节点。", "sortOrder": 41},
        {"id": "inner-belt", "name": "_内带小行星带_", "bodyType": "belt", "orbitAu": 0.95, "radiusLabel": "0.8-1.1 AU 小行星带", "summary": "_设定_铁镍和贵金属资源带。", "sortOrder": 50},
        {"id": "ringbox", "name": "_环匣_ / _Ringbox_", "bodyType": "planet", "orbitAu": 1.30, "radiusLabel": "迷你海王星", "summary": "_设定_金融中心，主卫星_匣_可半地球化，匣都人口约 600 万。", "sortOrder": 60, "rule_info_time": 0.14},
        {"id": "ringbox-xia", "parentId": "ringbox", "name": "_匣_ / _Xia_", "bodyType": "moon", "orbitAu": 1.306, "radiusLabel": "半地球化主卫星", "habitable": 1, "summary": "_设定_环匣主卫星，金融、保险和结算设施高度集中。", "sortOrder": 61, "rule_info_time": 0.12},
        {"id": "qiong", "name": "_阙穹_ / _Quevon_", "bodyType": "planet", "orbitAu": 3.40, "radiusLabel": "气巨星；76 卫星", "summary": "_设定_氦-3 心脏、环系空间站群和 76 颗卫星的外侧重心。", "sortOrder": 70, "rule_info_time": 0.10},
        {"id": "qiong-mo", "parentId": "qiong", "name": "_阙穹-墨_", "bodyType": "moon", "orbitAu": 3.43, "radiusLabel": "可改造卫星", "habitable": 1, "summary": "_设定_气巨星卫星中最有改造价值的一颗。", "sortOrder": 71, "rule_info_time": 0.08},
        {"id": "qiong-qing", "parentId": "qiong", "name": "_阙穹-罄_", "bodyType": "moon", "orbitAu": 3.46, "radiusLabel": "可改造卫星", "habitable": 1, "summary": "_设定_阙穹卫星群中另一颗具穹顶和早期地球化价值的卫星。", "sortOrder": 72},
        {"id": "middle-belt", "name": "_中带小行星带_", "bodyType": "belt", "orbitAu": 5.2, "radiusLabel": "4.5-5.5 AU 冰岩带", "summary": "_设定_受阙穹摄动，轨道复杂，海盗与走私活跃。", "sortOrder": 80},
        {"id": "mota", "name": "_穆塔_ / _Mota_", "bodyType": "planet", "orbitAu": 7.8, "radiusLabel": "冰巨星", "summary": "_设定_开发初期的外侧冰巨星。", "sortOrder": 90},
        {"id": "sokai", "name": "_锁阶_ / _Sokai_", "bodyType": "planet", "orbitAu": 11.2, "radiusLabel": "冰巨星", "summary": "_设定_测绘哨站和外缘补给点。", "sortOrder": 100},
        {"id": "li-outer-belt", "name": "_外带柯伊伯带_", "bodyType": "belt", "orbitAu": 18.0, "radiusLabel": "13-40 AU 冰小天体带", "summary": "_设定_长周期彗星、外缘测绘和远期未开发储备。", "sortOrder": 110},
    ],
    "gj1002": [
        {"id": "gj1002-star", "name": "GJ 1002", "bodyType": "star", "orbitAu": 0.0, "radiusLabel": "M5.5V；成熟低活动红矮星", "summary": "成熟近邻红矮星；现实发现两颗地球质量级宜居带行星。", "sortOrder": 0},
        {"id": "gj1002-b", "name": "GJ 1002 b", "bodyType": "planet", "orbitAu": 0.046, "radiusLabel": "地球质量级；约 10 日公转", "habitable": 1, "summary": "温暖宜居带行星，现实口径为地球质量级；_设定_为星蓝元素蓝生计划核心。", "sortOrder": 1},
        {"id": "gj1002-c", "name": "GJ 1002 c", "bodyType": "planet", "orbitAu": 0.074, "radiusLabel": "地球质量级；约 20 日公转", "habitable": 1, "summary": "较冷宜居带行星，现实口径为地球质量级；_设定_为智械/义体自治实验区。", "sortOrder": 2},
    ],
    "teegarden": [
        {"id": "teegarden-star", "name": "Teegarden's Star", "bodyType": "star", "orbitAu": 0.0, "radiusLabel": "M6.5V", "summary": "超冷红矮星。", "sortOrder": 0},
        {"id": "teegarden-b", "name": "Teegarden b", "bodyType": "planet", "orbitAu": 0.025, "radiusLabel": "地球质量级", "habitable": 1, "summary": "美丽花园的顶级生态地产。", "sortOrder": 1},
        {"id": "teegarden-c", "name": "Teegarden c", "bodyType": "planet", "orbitAu": 0.044, "radiusLabel": "地球质量级", "habitable": 1, "summary": "冷生态与长期封闭农业世界。", "sortOrder": 2},
        {"id": "teegarden-garden-ring", "name": "_花园轨道群_", "bodyType": "station", "orbitAu": 0.06, "radiusLabel": "轨道设施", "summary": "_设定_医疗、延寿与生态保全设施。", "sortOrder": 3},
    ],
    "tau-ceti": [
        {"id": "tau-star", "name": "Tau Ceti", "bodyType": "star", "orbitAu": 0.0, "radiusLabel": "G8.5V", "summary": "类太阳近邻恒星。", "sortOrder": 0},
        {"id": "tau-e", "name": "Tau Ceti e", "bodyType": "planet", "orbitAu": 0.55, "radiusLabel": "超级地球候选", "habitable": 1, "summary": "_设定_为半宜居海洋/花园化世界；现实口径保留争议。", "sortOrder": 1},
        {"id": "tau-f", "name": "Tau Ceti f", "bodyType": "planet", "orbitAu": 1.35, "radiusLabel": "冷超级地球候选", "summary": "冷边界世界。", "sortOrder": 2},
        {"id": "tau-dust", "name": "Tau Ceti 碎屑盘", "bodyType": "belt", "orbitAu": 35.0, "radiusLabel": "碎屑盘", "summary": "尘埃盘和生态工业原料。", "sortOrder": 3},
    ],
    "epsilon-eridani": [
        {"id": "eps-eri-star", "name": "Epsilon Eridani", "bodyType": "star", "orbitAu": 0.0, "radiusLabel": "K2V", "summary": "年轻活跃 K 型星。", "sortOrder": 0},
        {"id": "eps-eri-b", "name": "Epsilon Eridani b", "bodyType": "planet", "orbitAu": 3.5, "radiusLabel": "巨行星", "summary": "_设定_为造船联合体的卫星船坞群核心。", "sortOrder": 1},
        {"id": "eps-eri-debris", "name": "碎屑盘", "bodyType": "belt", "orbitAu": 20.0, "radiusLabel": "碎屑盘", "summary": "现实碎屑盘；_设定_为聚变燃料、冰尘和船坞材料来源。", "sortOrder": 2},
    ],
    "hd219134": [
        {"id": "hd219134-star", "name": "HD 219134", "bodyType": "star", "orbitAu": 0.0, "radiusLabel": "K3V；老年低活动", "summary": "近邻 K 型多行星系统；_设定_为 S&F 数据核心的主星。", "sortOrder": 0},
        {"id": "hd219134-b", "name": "HD 219134 b", "bodyType": "planet", "orbitAu": 0.03876, "radiusLabel": "热超级地球；3.1 日公转", "massLabel": "约 4.74 M⊕", "summary": "现实凌星热岩石行星；_设定_为数据与资产抵押样本。", "sortOrder": 1},
        {"id": "hd219134-c", "name": "HD 219134 c", "bodyType": "planet", "orbitAu": 0.065, "radiusLabel": "热超级地球", "summary": "热行星；_设定_为金融避难站轨道资产。", "sortOrder": 2},
        {"id": "hd219134-data-vault", "name": "_S&F 数据穹顶_", "bodyType": "station", "orbitAu": 0.4, "radiusLabel": "数据设施", "summary": "_设定_保险、清算与核心档案节点。", "sortOrder": 3},
    ],
}
